import React, { useState } from "react";
import { Redirect, useParams } from "react-router-dom";
import { Params } from "./globalSettings";

const blockList = {
  symbols: {
    "General Punctuation": "general-punctuation",
    "Superscripts and Subscripts": "superscripts-and-subscripts",
    "Currency Symbols": "currency-symbols",
    "Combining Diacritical Marks for Symbols":
      "combining-diacritical-marks-for-symbols",
    "Letterlike Symbols": "letterlike-symbols",
    "Number Forms": "number-forms",
    Arrows: "arrows",
    "Mathematical Operators": "mathematical-operators",
    "Miscellaneous Technical": "miscellaneous-technical",
    "Control Pictures": "control-pictures",
    "Optical Character Recognition": "optical-character-recognition",
    "Enclosed Alphanumerics": "enclosed-alphanumerics",
    "Box Drawing": "box-drawing",
    "Block Elements": "block-elements",
    "Geometric Shapes": "geometric-shapes",
    "Miscellaneous Symbols": "miscellaneous-symbols",
    Dingbats: "dingbats",
    "Miscellaneous Mathematical Symbols-A":
      "miscellaneous-mathematical-symbols-a",
    "Supplemental Arrows-A": "supplemental-arrows-a",
    "Braille Patterns": "braille-patterns",
    "Supplemental Arrows-B": "supplemental-arrows-b",
    "Miscellaneous Mathematical Symbols-B":
      "miscellaneous-mathematical-symbols-b",
    "Supplemental Mathematical Operators":
      "supplemental-mathematical-operators",
    "Miscellaneous Symbols and Arrows": "miscellaneous-symbols-and-arrows",
    "Supplemental Punctuation": "supplemental-punctuation",
    "Small Form Variants": "small-form-variants",
    "Mathematical Alphanumeric Symbols": "mathematical-alphanumeric-symbols",
    "Mahjong Tiles": "mahjong-tiles",
    "Domino Tiles": "domino-tiles",
    "Playing Cards": "playing-cards",
    "Enclosed Alphanumeric Supplement": "enclosed-alphanumeric-supplement",
    "Enclosed Ideographic Supplement": "enclosed-ideographic-supplement",
    "Miscellaneous Symbols and Pictographs":
      "miscellaneous-symbols-and-pictographs",
    Emoticons: "emoticons",
    "Ornamental Dingbats": "ornamental-dingbats",
    "Transport and Map Symbols": "transport-and-map-symbols",
    "Alchemical Symbols": "alchemical-symbols",
    "Geometric Shapes Extended": "geometric-shapes-extended",
    "Supplemental Arrows-C": "supplemental-arrows-c",
    "Supplemental Symbols and Pictographs":
      "supplemental-symbols-and-pictographs",
    "Chess Symbols": "chess-symbols",
    "Symbols and Pictographs Extended-A": "symbols-and-pictographs-extended-a",
    "Symbols for Legacy Computing": "symbols-for-legacy-computing",
  },
  languages: {
    "Basic Latin": "basic-latin",
    "Latin-1 Supplement": "latin-1-supplement",
    "Latin Extended-A": "latin-extended-a",
    "Latin Extended-B": "latin-extended-b",
    "IPA Extensions": "ipa-extensions",
    "Spacing Modifier Letters": "spacing-modifier-letters",
    "Combining Diacritical Marks": "combining-diacritical-marks",
    "Greek and Coptic": "greek-and-coptic",
    Cyrillic: "cyrillic",
    "Cyrillic Supplement": "cyrillic-supplement",
    Armenian: "armenian",
    Hebrew: "hebrew",
    Arabic: "arabic",
    Syriac: "syriac",
    "Arabic Supplement": "arabic-supplement",
    Thaana: "thaana",
    NKo: "nko",
    Samaritan: "samaritan",
    Mandaic: "mandaic",
    "Syriac Supplement": "syriac-supplement",
    "Arabic Extended-A": "arabic-extended-a",
    Devanagari: "devanagari",
    Bengali: "bengali",
    Gurmukhi: "gurmukhi",
    Gujarati: "gujarati",
    Oriya: "oriya",
    Tamil: "tamil",
    Telugu: "telugu",
    Kannada: "kannada",
    Malayalam: "malayalam",
    Sinhala: "sinhala",
    Thai: "thai",
    Lao: "lao",
    Tibetan: "tibetan",
    Myanmar: "myanmar",
    Georgian: "georgian",
    "Hangul Jamo": "hangul-jamo",
    Ethiopic: "ethiopic",
    "Ethiopic Supplement": "ethiopic-supplement",
    Cherokee: "cherokee",
    "Unified Canadian Aboriginal Syllabics":
      "unified-canadian-aboriginal-syllabics",
    Ogham: "ogham",
    Runic: "runic",
    Tagalog: "tagalog",
    Hanunoo: "hanunoo",
    Buhid: "buhid",
    Tagbanwa: "tagbanwa",
    Khmer: "khmer",
    Mongolian: "mongolian",
    "Unified Canadian Aboriginal Syllabics Extended":
      "unified-canadian-aboriginal-syllabics-extended",
    Limbu: "limbu",
    "Tai Le": "tai-le",
    "New Tai Lue": "new-tai-lue",
    "Khmer Symbols": "khmer-symbols",
    Buginese: "buginese",
    "Tai Tham": "tai-tham",
    "Combining Diacritical Marks Extended":
      "combining-diacritical-marks-extended",
    Balinese: "balinese",
    Sundanese: "sundanese",
    Batak: "batak",
    Lepcha: "lepcha",
    "Ol Chiki": "ol-chiki",
    "Cyrillic Extended-C": "cyrillic-extended-c",
    "Georgian Extended": "georgian-extended",
    "Sundanese Supplement": "sundanese-supplement",
    "Vedic Extensions": "vedic-extensions",
    "Phonetic Extensions": "phonetic-extensions",
    "Phonetic Extensions Supplement": "phonetic-extensions-supplement",
    "Combining Diacritical Marks Supplement":
      "combining-diacritical-marks-supplement",
    "Latin Extended Additional": "latin-extended-additional",
    "Greek Extended": "greek-extended",
    Glagolitic: "glagolitic",
    "Latin Extended-C": "latin-extended-c",
    Coptic: "coptic",
    "Georgian Supplement": "georgian-supplement",
    Tifinagh: "tifinagh",
    "Ethiopic Extended": "ethiopic-extended",
    "Cyrillic Extended-A": "cyrillic-extended-a",
    "Old Sogdian": "old-sogdian",
    "CJK Radicals Supplement": "cjk-radicals-supplement",
    "Kangxi Radicals": "kangxi-radicals",
    "Ideographic Description Characters": "ideographic-description-characters",
    "CJK Symbols and Punctuation": "cjk-symbols-and-punctuation",
    Hiragana: "hiragana",
    Katakana: "katakana",
    Bopomofo: "bopomofo",
    "Hangul Compatibility Jamo": "hangul-compatibility-jamo",
    Kanbun: "kanbun",
    "Bopomofo Extended": "bopomofo-extended",
    "CJK Strokes": "cjk-strokes",
    "Katakana Phonetic Extensions": "katakana-phonetic-extensions",
    "Enclosed CJK Letters and Months": "enclosed-cjk-letters-and-months",
    "CJK Compatibility": "cjk-compatibility",
    "CJK Unified Ideographs Extension A": "cjk-unified-ideographs-extension-a",
    "Yijing Hexagram Symbols": "yijing-hexagram-symbols",
    "CJK Unified Ideographs": "cjk-unified-ideographs",
    "Yi Syllables": "yi-syllables",
    "Yi Radicals": "yi-radicals",
    Lisu: "lisu",
    Vai: "vai",
    "Cyrillic Extended-B": "cyrillic-extended-b",
    Bamum: "bamum",
    "Modifier Tone Letters": "modifier-tone-letters",
    "Latin Extended-D": "latin-extended-d",
    "Syloti Nagri": "syloti-nagri",
    "Common Indic Number Forms": "common-indic-number-forms",
    "Phags-pa": "phags-pa",
    Saurashtra: "saurashtra",
    "Devanagari Extended": "devanagari-extended",
    "Kayah Li": "kayah-li",
    Rejang: "rejang",
    "Hangul Jamo Extended-A": "hangul-jamo-extended-a",
    Javanese: "javanese",
    "Myanmar Extended-B": "myanmar-extended-b",
    Cham: "cham",
    "Myanmar Extended-A": "myanmar-extended-a",
    "Tai Viet": "tai-viet",
    "Meetei Mayek Extensions": "meetei-mayek-extensions",
    "Ethiopic Extended-A": "ethiopic-extended-a",
    "Latin Extended-E": "latin-extended-e",
    "Cherokee Supplement": "cherokee-supplement",
    "Meetei Mayek": "meetei-mayek",
    "Hangul Syllables": "hangul-syllables",
    "Hangul Jamo Extended-B": "hangul-jamo-extended-b",
    // "High Surrogates": "high-surrogates",
    // "High Private Use Surrogates": "high-private-use-surrogates",
    // "Low Surrogates": "low-surrogates",
    // "Private Use Area": "private-use-area",
    "CJK Compatibility Ideographs": "cjk-compatibility-ideographs",
    "Alphabetic Presentation Forms": "alphabetic-presentation-forms",
    "Arabic Presentation Forms-A": "arabic-presentation-forms-a",
    "Variation Selectors": "variation-selectors",
    "Vertical Forms": "vertical-forms",
    "Combining Half Marks": "combining-half-marks",
    "CJK Compatibility Forms": "cjk-compatibility-forms",
    "Arabic Presentation Forms-B": "arabic-presentation-forms-b",
    "Halfwidth and Fullwidth Forms": "halfwidth-and-fullwidth-forms",
    Specials: "specials",
    "Linear B Syllabary": "linear-b-syllabary",
    "Linear B Ideograms": "linear-b-ideograms",
    "Aegean Numbers": "aegean-numbers",
    "Ancient Greek Numbers": "ancient-greek-numbers",
    "Ancient Symbols": "ancient-symbols",
    "Phaistos Disc": "phaistos-disc",
    Lycian: "lycian",
    Carian: "carian",
    "Coptic Epact Numbers": "coptic-epact-numbers",
    "Old Italic": "old-italic",
    Gothic: "gothic",
    "Old Permic": "old-permic",
    Ugaritic: "ugaritic",
    "Old Persian": "old-persian",
    Deseret: "deseret",
    Shavian: "shavian",
    Osmanya: "osmanya",
    Osage: "osage",
    Elbasan: "elbasan",
    "Caucasian Albanian": "caucasian-albanian",
    "Linear A": "linear-a",
    "Cypriot Syllabary": "cypriot-syllabary",
    "Imperial Aramaic": "imperial-aramaic",
    Palmyrene: "palmyrene",
    Nabataean: "nabataean",
    Hatran: "hatran",
    Phoenician: "phoenician",
    Lydian: "lydian",
    "Meroitic Hieroglyphs": "meroitic-hieroglyphs",
    "Meroitic Cursive": "meroitic-cursive",
    Kharoshthi: "kharoshthi",
    "Old South Arabian": "old-south-arabian",
    "Old North Arabian": "old-north-arabian",
    Manichaean: "manichaean",
    Avestan: "avestan",
    "Inscriptional Parthian": "inscriptional-parthian",
    "Inscriptional Pahlavi": "inscriptional-pahlavi",
    "Psalter Pahlavi": "psalter-pahlavi",
    "Old Turkic": "old-turkic",
    "Old Hungarian": "old-hungarian",
    "Hanifi Rohingya": "hanifi-rohingya",
    "Rumi Numeral Symbols": "rumi-numeral-symbols",
    Yezidi: "yezidi",
    Sogdian: "sogdian",
    Chorasmian: "chorasmian",
    Elymaic: "elymaic",
    Brahmi: "brahmi",
    Kaithi: "kaithi",
    "Sora Sompeng": "sora-sompeng",
    Chakma: "chakma",
    Mahajani: "mahajani",
    Sharada: "sharada",
    "Sinhala Archaic Numbers": "sinhala-archaic-numbers",
    Khojki: "khojki",
    Multani: "multani",
    Khudawadi: "khudawadi",
    Grantha: "grantha",
    Newa: "newa",
    Tirhuta: "tirhuta",
    Siddham: "siddham",
    Modi: "modi",
    "Mongolian Supplement": "mongolian-supplement",
    Takri: "takri",
    Ahom: "ahom",
    Dogra: "dogra",
    "Warang Citi": "warang-citi",
    "Dives Akuru": "dives-akuru",
    Nandinagari: "nandinagari",
    "Zanabazar Square": "zanabazar-square",
    Soyombo: "soyombo",
    "Pau Cin Hau": "pau-cin-hau",
    Bhaiksuki: "bhaiksuki",
    Marchen: "marchen",
    "Masaram Gondi": "masaram-gondi",
    "Gunjala Gondi": "gunjala-gondi",
    Makasar: "makasar",
    "Lisu Supplement": "lisu-supplement",
    "Tamil Supplement": "tamil-supplement",
    Cuneiform: "cuneiform",
    "Cuneiform Numbers and Punctuation": "cuneiform-numbers-and-punctuation",
    "Early Dynastic Cuneiform": "early-dynastic-cuneiform",
    "Egyptian Hieroglyphs": "egyptian-hieroglyphs",
    "Egyptian Hieroglyph Format Controls":
      "egyptian-hieroglyph-format-controls",
    "Anatolian Hieroglyphs": "anatolian-hieroglyphs",
    "Bamum Supplement": "bamum-supplement",
    Mro: "mro",
    "Bassa Vah": "bassa-vah",
    "Pahawh Hmong": "pahawh-hmong",
    Medefaidrin: "medefaidrin",
    Miao: "miao",
    "Ideographic Symbols and Punctuation":
      "ideographic-symbols-and-punctuation",
    Tangut: "tangut",
    "Tangut Components": "tangut-components",
    "Khitan Small Script": "khitan-small-script",
    "Tangut Supplement": "tangut-supplement",
    "Kana Supplement": "kana-supplement",
    "Kana Extended-A": "kana-extended-a",
    "Small Kana Extension": "small-kana-extension",
    Nushu: "nushu",
    Duployan: "duployan",
    "Shorthand Format Controls": "shorthand-format-controls",
    "Byzantine Musical Symbols": "byzantine-musical-symbols",
    "Musical Symbols": "musical-symbols",
    "Ancient Greek Musical Notation": "ancient-greek-musical-notation",
    "Mayan Numerals": "mayan-numerals",
    "Tai Xuan Jing Symbols": "tai-xuan-jing-symbols",
    "Counting Rod Numerals": "counting-rod-numerals",
    "Sutton SignWriting": "sutton-signwriting",
    "Glagolitic Supplement": "glagolitic-supplement",
    "Nyiakeng Puachue Hmong": "nyiakeng-puachue-hmong",
    Wancho: "wancho",
    "Mende Kikakui": "mende-kikakui",
    Adlam: "adlam",
    "Indic Siyaq Numbers": "indic-siyaq-numbers",
    "Ottoman Siyaq Numbers": "ottoman-siyaq-numbers",

    "Arabic Mathematical Alphabetic Symbols":
      "arabic-mathematical-alphabetic-symbols",

    "CJK Unified Ideographs Extension B": "cjk-unified-ideographs-extension-b",
    "CJK Unified Ideographs Extension C": "cjk-unified-ideographs-extension-c",
    "CJK Unified Ideographs Extension D": "cjk-unified-ideographs-extension-d",
    "CJK Unified Ideographs Extension E": "cjk-unified-ideographs-extension-e",
    "CJK Unified Ideographs Extension F": "cjk-unified-ideographs-extension-f",
    "CJK Compatibility Ideographs Supplement":
      "cjk-compatibility-ideographs-supplement",
    "CJK Unified Ideographs Extension G": "cjk-unified-ideographs-extension-g",
    Tags: "tags",
    "Variation Selectors Supplement": "variation-selectors-supplement",
    // "Supplementary Private Use Area-A": "supplementary-private-use-area-a",
    // "Supplementary Private Use Area-B": "supplementary-private-use-area-b",
  },
};

export const BlockSelector: React.FC = (props) => {
  const [selectedBlock, setSelectedBlock] = useState("");
  let { blockSlug } = useParams<Params>();
  return (
    <>
      <label>
        Select block:{" "}
        <select
          name="blockSelector"
          onChange={(e) => setSelectedBlock(e.currentTarget.value)}
          value={blockSlug || ""}
        >
          <option value="" key="symbols">
            --- SYMBOLS ---
          </option>
          {Object.keys(blockList["symbols"])
            .sort()
            .map((block, idx) => (
              <option
                key={`symbols-${idx}`}
                value={Reflect.get(blockList["symbols"], block)}
              >
                {"\xa0\xa0" + block}
              </option>
            ))}
          <option value="" key="languages">
            --- LANGUAGES ---
          </option>
          {Object.keys(blockList["languages"])
            .sort()
            .map((block, idx) => (
              <option
                key={`languages-${idx}`}
                value={Reflect.get(blockList["languages"], block)}
              >
                {"\xa0\xa0" + block}
              </option>
            ))}
        </select>
      </label>
      {selectedBlock && <Redirect push to={`/block/${selectedBlock}`} />}
    </>
  );
};
