cachedBlocks = {'BASIC LATIN': {'slug': 'basic-latin', 'start': 0},
 'LATIN-1 SUPPLEMENT': {'slug': 'latin-1-supplement', 'start': 128},
 'LATIN EXTENDED-A': {'slug': 'latin-extended-a', 'start': 256},
 'LATIN EXTENDED-B': {'slug': 'latin-extended-b', 'start': 384},
 'IPA EXTENSIONS': {'slug': 'ipa-extensions', 'start': 592},
 'SPACING MODIFIER LETTERS': {'slug': 'spacing-modifier-letters',
  'start': 688},
 'COMBINING DIACRITICAL MARKS': {'slug': 'combining-diacritical-marks',
  'start': 768},
 'GREEK AND COPTIC': {'slug': 'greek-and-coptic', 'start': 880},
 'CYRILLIC': {'slug': 'cyrillic', 'start': 1024},
 'CYRILLIC SUPPLEMENT': {'slug': 'cyrillic-supplement', 'start': 1280},
 'ARMENIAN': {'slug': 'armenian', 'start': 1328},
 'HEBREW': {'slug': 'hebrew', 'start': 1424},
 'ARABIC': {'slug': 'arabic', 'start': 1536},
 'SYRIAC': {'slug': 'syriac', 'start': 1792},
 'ARABIC SUPPLEMENT': {'slug': 'arabic-supplement', 'start': 1872},
 'THAANA': {'slug': 'thaana', 'start': 1920},
 'NKO': {'slug': 'nko', 'start': 1984},
 'SAMARITAN': {'slug': 'samaritan', 'start': 2048},
 'MANDAIC': {'slug': 'mandaic', 'start': 2112},
 'SYRIAC SUPPLEMENT': {'slug': 'syriac-supplement', 'start': 2144},
 'ARABIC EXTENDED-A': {'slug': 'arabic-extended-a', 'start': 2208},
 'DEVANAGARI': {'slug': 'devanagari', 'start': 2304},
 'BENGALI': {'slug': 'bengali', 'start': 2432},
 'GURMUKHI': {'slug': 'gurmukhi', 'start': 2560},
 'GUJARATI': {'slug': 'gujarati', 'start': 2688},
 'ORIYA': {'slug': 'oriya', 'start': 2816},
 'TAMIL': {'slug': 'tamil', 'start': 2944},
 'TELUGU': {'slug': 'telugu', 'start': 3072},
 'KANNADA': {'slug': 'kannada', 'start': 3200},
 'MALAYALAM': {'slug': 'malayalam', 'start': 3328},
 'SINHALA': {'slug': 'sinhala', 'start': 3456},
 'THAI': {'slug': 'thai', 'start': 3584},
 'LAO': {'slug': 'lao', 'start': 3712},
 'TIBETAN': {'slug': 'tibetan', 'start': 3840},
 'MYANMAR': {'slug': 'myanmar', 'start': 4096},
 'GEORGIAN': {'slug': 'georgian', 'start': 4256},
 'HANGUL JAMO': {'slug': 'hangul-jamo', 'start': 4352},
 'ETHIOPIC': {'slug': 'ethiopic', 'start': 4608},
 'ETHIOPIC SUPPLEMENT': {'slug': 'ethiopic-supplement', 'start': 4992},
 'CHEROKEE': {'slug': 'cherokee', 'start': 5024},
 'OGHAM': {'slug': 'ogham', 'start': 5760},
 'RUNIC': {'slug': 'runic', 'start': 5792},
 'TAGALOG': {'slug': 'tagalog', 'start': 5888},
 'HANUNOO': {'slug': 'hanunoo', 'start': 5920},
 'BUHID': {'slug': 'buhid', 'start': 5952},
 'TAGBANWA': {'slug': 'tagbanwa', 'start': 5984},
 'KHMER': {'slug': 'khmer', 'start': 6016},
 'MONGOLIAN': {'slug': 'mongolian', 'start': 6144},
 'UNIFIED CANADIAN ABORIGINAL SYLLABICS EXTENDED': {'slug': 'unified-canadian-aboriginal-syllabics-extended',
  'start': 6320},
 'LIMBU': {'slug': 'limbu', 'start': 6400},
 'TAI LE': {'slug': 'tai-le', 'start': 6480},
 'NEW TAI LUE': {'slug': 'new-tai-lue', 'start': 6528},
 'KHMER SYMBOLS': {'slug': 'khmer-symbols', 'start': 6624},
 'BUGINESE': {'slug': 'buginese', 'start': 6656},
 'TAI THAM': {'slug': 'tai-tham', 'start': 6688},
 'COMBINING DIACRITICAL MARKS EXTENDED': {'slug': 'combining-diacritical-marks-extended',
  'start': 6832},
 'BALINESE': {'slug': 'balinese', 'start': 6912},
 'SUNDANESE': {'slug': 'sundanese', 'start': 7040},
 'BATAK': {'slug': 'batak', 'start': 7104},
 'LEPCHA': {'slug': 'lepcha', 'start': 7168},
 'OL CHIKI': {'slug': 'ol-chiki', 'start': 7248},
 'CYRILLIC EXTENDED-C': {'slug': 'cyrillic-extended-c', 'start': 7296},
 'GEORGIAN EXTENDED': {'slug': 'georgian-extended', 'start': 7312},
 'SUNDANESE SUPPLEMENT': {'slug': 'sundanese-supplement', 'start': 7360},
 'VEDIC EXTENSIONS': {'slug': 'vedic-extensions', 'start': 7376},
 'PHONETIC EXTENSIONS': {'slug': 'phonetic-extensions', 'start': 7424},
 'PHONETIC EXTENSIONS SUPPLEMENT': {'slug': 'phonetic-extensions-supplement',
  'start': 7552},
 'COMBINING DIACRITICAL MARKS SUPPLEMENT': {'slug': 'combining-diacritical-marks-supplement',
  'start': 7616},
 'LATIN EXTENDED ADDITIONAL': {'slug': 'latin-extended-additional',
  'start': 7680},
 'GREEK EXTENDED': {'slug': 'greek-extended', 'start': 7936},
 'GENERAL PUNCTUATION': {'slug': 'general-punctuation', 'start': 8192},
 'SUPERSCRIPTS AND SUBSCRIPTS': {'slug': 'superscripts-and-subscripts',
  'start': 8304},
 'CURRENCY SYMBOLS': {'slug': 'currency-symbols', 'start': 8352},
 'COMBINING DIACRITICAL MARKS FOR SYMBOLS': {'slug': 'combining-diacritical-marks-for-symbols',
  'start': 8400},
 'LETTERLIKE SYMBOLS': {'slug': 'letterlike-symbols', 'start': 8448},
 'NUMBER FORMS': {'slug': 'number-forms', 'start': 8528},
 'ARROWS': {'slug': 'arrows', 'start': 8592},
 'MATHEMATICAL OPERATORS': {'slug': 'mathematical-operators', 'start': 8704},
 'MISCELLANEOUS TECHNICAL': {'slug': 'miscellaneous-technical', 'start': 8960},
 'CONTROL PICTURES': {'slug': 'control-pictures', 'start': 9216},
 'OPTICAL CHARACTER RECOGNITION': {'slug': 'optical-character-recognition',
  'start': 9280},
 'ENCLOSED ALPHANUMERICS': {'slug': 'enclosed-alphanumerics', 'start': 9312},
 'BOX DRAWING': {'slug': 'box-drawing', 'start': 9472},
 'BLOCK ELEMENTS': {'slug': 'block-elements', 'start': 9600},
 'GEOMETRIC SHAPES': {'slug': 'geometric-shapes', 'start': 9632},
 'MISCELLANEOUS SYMBOLS': {'slug': 'miscellaneous-symbols', 'start': 9728},
 'DINGBATS': {'slug': 'dingbats', 'start': 9984},
 'MISCELLANEOUS MATHEMATICAL SYMBOLS-A': {'slug': 'miscellaneous-mathematical-symbols-a',
  'start': 10176},
 'SUPPLEMENTAL ARROWS-A': {'slug': 'supplemental-arrows-a', 'start': 10224},
 'BRAILLE PATTERNS': {'slug': 'braille-patterns', 'start': 10240},
 'SUPPLEMENTAL ARROWS-B': {'slug': 'supplemental-arrows-b', 'start': 10496},
 'MISCELLANEOUS MATHEMATICAL SYMBOLS-B': {'slug': 'miscellaneous-mathematical-symbols-b',
  'start': 10624},
 'SUPPLEMENTAL MATHEMATICAL OPERATORS': {'slug': 'supplemental-mathematical-operators',
  'start': 10752},
 'MISCELLANEOUS SYMBOLS AND ARROWS': {'slug': 'miscellaneous-symbols-and-arrows',
  'start': 11008},
 'GLAGOLITIC': {'slug': 'glagolitic', 'start': 11264},
 'LATIN EXTENDED-C': {'slug': 'latin-extended-c', 'start': 11360},
 'COPTIC': {'slug': 'coptic', 'start': 11392},
 'GEORGIAN SUPPLEMENT': {'slug': 'georgian-supplement', 'start': 11520},
 'TIFINAGH': {'slug': 'tifinagh', 'start': 11568},
 'ETHIOPIC EXTENDED': {'slug': 'ethiopic-extended', 'start': 11648},
 'CYRILLIC EXTENDED-A': {'slug': 'cyrillic-extended-a', 'start': 11744},
 'SUPPLEMENTAL PUNCTUATION': {'slug': 'supplemental-punctuation',
  'start': 11776},
 'OLD SOGDIAN': {'slug': 'old-sogdian', 'start': 69376},
 'CJK RADICALS SUPPLEMENT': {'slug': 'cjk-radicals-supplement',
  'start': 11904},
 'KANGXI RADICALS': {'slug': 'kangxi-radicals', 'start': 12032},
 'IDEOGRAPHIC DESCRIPTION CHARACTERS': {'slug': 'ideographic-description-characters',
  'start': 12272},
 'CJK SYMBOLS AND PUNCTUATION': {'slug': 'cjk-symbols-and-punctuation',
  'start': 12288},
 'HIRAGANA': {'slug': 'hiragana', 'start': 12352},
 'KATAKANA': {'slug': 'katakana', 'start': 12448},
 'BOPOMOFO': {'slug': 'bopomofo', 'start': 12544},
 'HANGUL COMPATIBILITY JAMO': {'slug': 'hangul-compatibility-jamo',
  'start': 12592},
 'KANBUN': {'slug': 'kanbun', 'start': 12688},
 'BOPOMOFO EXTENDED': {'slug': 'bopomofo-extended', 'start': 12704},
 'CJK STROKES': {'slug': 'cjk-strokes', 'start': 12736},
 'KATAKANA PHONETIC EXTENSIONS': {'slug': 'katakana-phonetic-extensions',
  'start': 12784},
 'ENCLOSED CJK LETTERS AND MONTHS': {'slug': 'enclosed-cjk-letters-and-months',
  'start': 12800},
 'CJK COMPATIBILITY': {'slug': 'cjk-compatibility', 'start': 13056},
 'YIJING HEXAGRAM SYMBOLS': {'slug': 'yijing-hexagram-symbols',
  'start': 19904},
 'YI RADICALS': {'slug': 'yi-radicals', 'start': 42128},
 'LISU': {'slug': 'lisu', 'start': 42192},
 'VAI': {'slug': 'vai', 'start': 42240},
 'CYRILLIC EXTENDED-B': {'slug': 'cyrillic-extended-b', 'start': 42560},
 'BAMUM': {'slug': 'bamum', 'start': 42656},
 'MODIFIER TONE LETTERS': {'slug': 'modifier-tone-letters', 'start': 42752},
 'LATIN EXTENDED-D': {'slug': 'latin-extended-d', 'start': 42784},
 'SYLOTI NAGRI': {'slug': 'syloti-nagri', 'start': 43008},
 'COMMON INDIC NUMBER FORMS': {'slug': 'common-indic-number-forms',
  'start': 43056},
 'PHAGS-PA': {'slug': 'phags-pa', 'start': 43072},
 'SAURASHTRA': {'slug': 'saurashtra', 'start': 43136},
 'DEVANAGARI EXTENDED': {'slug': 'devanagari-extended', 'start': 43232},
 'KAYAH LI': {'slug': 'kayah-li', 'start': 43264},
 'REJANG': {'slug': 'rejang', 'start': 43312},
 'HANGUL JAMO EXTENDED-A': {'slug': 'hangul-jamo-extended-a', 'start': 43360},
 'JAVANESE': {'slug': 'javanese', 'start': 43392},
 'MYANMAR EXTENDED-B': {'slug': 'myanmar-extended-b', 'start': 43488},
 'CHAM': {'slug': 'cham', 'start': 43520},
 'MYANMAR EXTENDED-A': {'slug': 'myanmar-extended-a', 'start': 43616},
 'TAI VIET': {'slug': 'tai-viet', 'start': 43648},
 'MEETEI MAYEK EXTENSIONS': {'slug': 'meetei-mayek-extensions',
  'start': 43744},
 'ETHIOPIC EXTENDED-A': {'slug': 'ethiopic-extended-a', 'start': 43776},
 'LATIN EXTENDED-E': {'slug': 'latin-extended-e', 'start': 43824},
 'CHEROKEE SUPPLEMENT': {'slug': 'cherokee-supplement', 'start': 43888},
 'MEETEI MAYEK': {'slug': 'meetei-mayek', 'start': 43968},
 'HANGUL JAMO EXTENDED-B': {'slug': 'hangul-jamo-extended-b', 'start': 55216},
 'HIGH SURROGATES': {'slug': 'high-surrogates', 'start': 55296},
 'HIGH PRIVATE USE SURROGATES': {'slug': 'high-private-use-surrogates',
  'start': 56192},
 'LOW SURROGATES': {'slug': 'low-surrogates', 'start': 56320},
 'PRIVATE USE AREA': {'slug': 'private-use-area', 'start': 57344},
 'CJK COMPATIBILITY IDEOGRAPHS': {'slug': 'cjk-compatibility-ideographs',
  'start': 63744},
 'ALPHABETIC PRESENTATION FORMS': {'slug': 'alphabetic-presentation-forms',
  'start': 64256},
 'ARABIC PRESENTATION FORMS-A': {'slug': 'arabic-presentation-forms-a',
  'start': 64336},
 'VARIATION SELECTORS': {'slug': 'variation-selectors', 'start': 65024},
 'VERTICAL FORMS': {'slug': 'vertical-forms', 'start': 65040},
 'COMBINING HALF MARKS': {'slug': 'combining-half-marks', 'start': 65056},
 'CJK COMPATIBILITY FORMS': {'slug': 'cjk-compatibility-forms',
  'start': 65072},
 'SMALL FORM VARIANTS': {'slug': 'small-form-variants', 'start': 65104},
 'ARABIC PRESENTATION FORMS-B': {'slug': 'arabic-presentation-forms-b',
  'start': 65136},
 'HALFWIDTH AND FULLWIDTH FORMS': {'slug': 'halfwidth-and-fullwidth-forms',
  'start': 65280},
 'SPECIALS': {'slug': 'specials', 'start': 65520},
 'LINEAR B SYLLABARY': {'slug': 'linear-b-syllabary', 'start': 65536},
 'LINEAR B IDEOGRAMS': {'slug': 'linear-b-ideograms', 'start': 65664},
 'AEGEAN NUMBERS': {'slug': 'aegean-numbers', 'start': 65792},
 'ANCIENT GREEK NUMBERS': {'slug': 'ancient-greek-numbers', 'start': 65856},
 'ANCIENT SYMBOLS': {'slug': 'ancient-symbols', 'start': 65936},
 'PHAISTOS DISC': {'slug': 'phaistos-disc', 'start': 66000},
 'LYCIAN': {'slug': 'lycian', 'start': 66176},
 'CARIAN': {'slug': 'carian', 'start': 66208},
 'COPTIC EPACT NUMBERS': {'slug': 'coptic-epact-numbers', 'start': 66272},
 'OLD ITALIC': {'slug': 'old-italic', 'start': 66304},
 'GOTHIC': {'slug': 'gothic', 'start': 66352},
 'OLD PERMIC': {'slug': 'old-permic', 'start': 66384},
 'UGARITIC': {'slug': 'ugaritic', 'start': 66432},
 'OLD PERSIAN': {'slug': 'old-persian', 'start': 66464},
 'DESERET': {'slug': 'deseret', 'start': 66560},
 'SHAVIAN': {'slug': 'shavian', 'start': 66640},
 'OSMANYA': {'slug': 'osmanya', 'start': 66688},
 'OSAGE': {'slug': 'osage', 'start': 66736},
 'ELBASAN': {'slug': 'elbasan', 'start': 66816},
 'CAUCASIAN ALBANIAN': {'slug': 'caucasian-albanian', 'start': 66864},
 'LINEAR A': {'slug': 'linear-a', 'start': 67072},
 'CYPRIOT SYLLABARY': {'slug': 'cypriot-syllabary', 'start': 67584},
 'IMPERIAL ARAMAIC': {'slug': 'imperial-aramaic', 'start': 67648},
 'PALMYRENE': {'slug': 'palmyrene', 'start': 67680},
 'NABATAEAN': {'slug': 'nabataean', 'start': 67712},
 'HATRAN': {'slug': 'hatran', 'start': 67808},
 'PHOENICIAN': {'slug': 'phoenician', 'start': 67840},
 'LYDIAN': {'slug': 'lydian', 'start': 67872},
 'MEROITIC HIEROGLYPHS': {'slug': 'meroitic-hieroglyphs', 'start': 67968},
 'MEROITIC CURSIVE': {'slug': 'meroitic-cursive', 'start': 68000},
 'KHAROSHTHI': {'slug': 'kharoshthi', 'start': 68096},
 'OLD SOUTH ARABIAN': {'slug': 'old-south-arabian', 'start': 68192},
 'OLD NORTH ARABIAN': {'slug': 'old-north-arabian', 'start': 68224},
 'MANICHAEAN': {'slug': 'manichaean', 'start': 68288},
 'AVESTAN': {'slug': 'avestan', 'start': 68352},
 'INSCRIPTIONAL PARTHIAN': {'slug': 'inscriptional-parthian', 'start': 68416},
 'INSCRIPTIONAL PAHLAVI': {'slug': 'inscriptional-pahlavi', 'start': 68448},
 'PSALTER PAHLAVI': {'slug': 'psalter-pahlavi', 'start': 68480},
 'OLD TURKIC': {'slug': 'old-turkic', 'start': 68608},
 'OLD HUNGARIAN': {'slug': 'old-hungarian', 'start': 68736},
 'HANIFI ROHINGYA': {'slug': 'hanifi-rohingya', 'start': 68864},
 'RUMI NUMERAL SYMBOLS': {'slug': 'rumi-numeral-symbols', 'start': 69216},
 'YEZIDI': {'slug': 'yezidi', 'start': 69248},
 'HANGUL SYLLABLES': {'slug': 'hangul-syllables', 'start': 44032},
 'YI SYLLABLES': {'slug': 'yi-syllables', 'start': 40960},
 'SOGDIAN': {'slug': 'sogdian', 'start': 69424},
 'CHORASMIAN': {'slug': 'chorasmian', 'start': 69552},
 'ELYMAIC': {'slug': 'elymaic', 'start': 69600},
 'BRAHMI': {'slug': 'brahmi', 'start': 69632},
 'KAITHI': {'slug': 'kaithi', 'start': 69760},
 'SORA SOMPENG': {'slug': 'sora-sompeng', 'start': 69840},
 'CHAKMA': {'slug': 'chakma', 'start': 69888},
 'MAHAJANI': {'slug': 'mahajani', 'start': 69968},
 'SHARADA': {'slug': 'sharada', 'start': 70016},
 'SINHALA ARCHAIC NUMBERS': {'slug': 'sinhala-archaic-numbers',
  'start': 70112},
 'KHOJKI': {'slug': 'khojki', 'start': 70144},
 'MULTANI': {'slug': 'multani', 'start': 70272},
 'KHUDAWADI': {'slug': 'khudawadi', 'start': 70320},
 'GRANTHA': {'slug': 'grantha', 'start': 70400},
 'NEWA': {'slug': 'newa', 'start': 70656},
 'TIRHUTA': {'slug': 'tirhuta', 'start': 70784},
 'SIDDHAM': {'slug': 'siddham', 'start': 71040},
 'MODI': {'slug': 'modi', 'start': 71168},
 'MONGOLIAN SUPPLEMENT': {'slug': 'mongolian-supplement', 'start': 71264},
 'TAKRI': {'slug': 'takri', 'start': 71296},
 'AHOM': {'slug': 'ahom', 'start': 71424},
 'DOGRA': {'slug': 'dogra', 'start': 71680},
 'WARANG CITI': {'slug': 'warang-citi', 'start': 71840},
 'DIVES AKURU': {'slug': 'dives-akuru', 'start': 71936},
 'NANDINAGARI': {'slug': 'nandinagari', 'start': 72096},
 'ZANABAZAR SQUARE': {'slug': 'zanabazar-square', 'start': 72192},
 'SOYOMBO': {'slug': 'soyombo', 'start': 72272},
 'PAU CIN HAU': {'slug': 'pau-cin-hau', 'start': 72384},
 'BHAIKSUKI': {'slug': 'bhaiksuki', 'start': 72704},
 'MARCHEN': {'slug': 'marchen', 'start': 72816},
 'MASARAM GONDI': {'slug': 'masaram-gondi', 'start': 72960},
 'GUNJALA GONDI': {'slug': 'gunjala-gondi', 'start': 73056},
 'MAKASAR': {'slug': 'makasar', 'start': 73440},
 'LISU SUPPLEMENT': {'slug': 'lisu-supplement', 'start': 73648},
 'TAMIL SUPPLEMENT': {'slug': 'tamil-supplement', 'start': 73664},
 'CUNEIFORM NUMBERS AND PUNCTUATION': {'slug': 'cuneiform-numbers-and-punctuation',
  'start': 74752},
 'EARLY DYNASTIC CUNEIFORM': {'slug': 'early-dynastic-cuneiform',
  'start': 74880},
 'EGYPTIAN HIEROGLYPH FORMAT CONTROLS': {'slug': 'egyptian-hieroglyph-format-controls',
  'start': 78896},
 'MRO': {'slug': 'mro', 'start': 92736},
 'BASSA VAH': {'slug': 'bassa-vah', 'start': 92880},
 'PAHAWH HMONG': {'slug': 'pahawh-hmong', 'start': 92928},
 'MEDEFAIDRIN': {'slug': 'medefaidrin', 'start': 93760},
 'MIAO': {'slug': 'miao', 'start': 93952},
 'IDEOGRAPHIC SYMBOLS AND PUNCTUATION': {'slug': 'ideographic-symbols-and-punctuation',
  'start': 94176},
 'KHITAN SMALL SCRIPT': {'slug': 'khitan-small-script', 'start': 101120},
 'TANGUT SUPPLEMENT': {'slug': 'tangut-supplement', 'start': 101632},
 'KANA SUPPLEMENT': {'slug': 'kana-supplement', 'start': 110592},
 'KANA EXTENDED-A': {'slug': 'kana-extended-a', 'start': 110848},
 'SMALL KANA EXTENSION': {'slug': 'small-kana-extension', 'start': 110896},
 'NUSHU': {'slug': 'nushu', 'start': 110960},
 'DUPLOYAN': {'slug': 'duployan', 'start': 113664},
 'SHORTHAND FORMAT CONTROLS': {'slug': 'shorthand-format-controls',
  'start': 113824},
 'BYZANTINE MUSICAL SYMBOLS': {'slug': 'byzantine-musical-symbols',
  'start': 118784},
 'MUSICAL SYMBOLS': {'slug': 'musical-symbols', 'start': 119040},
 'ANCIENT GREEK MUSICAL NOTATION': {'slug': 'ancient-greek-musical-notation',
  'start': 119296},
 'MAYAN NUMERALS': {'slug': 'mayan-numerals', 'start': 119520},
 'TAI XUAN JING SYMBOLS': {'slug': 'tai-xuan-jing-symbols', 'start': 119552},
 'COUNTING ROD NUMERALS': {'slug': 'counting-rod-numerals', 'start': 119648},
 'GLAGOLITIC SUPPLEMENT': {'slug': 'glagolitic-supplement', 'start': 122880},
 'NYIAKENG PUACHUE HMONG': {'slug': 'nyiakeng-puachue-hmong', 'start': 123136},
 'WANCHO': {'slug': 'wancho', 'start': 123584},
 'MENDE KIKAKUI': {'slug': 'mende-kikakui', 'start': 124928},
 'ADLAM': {'slug': 'adlam', 'start': 125184},
 'INDIC SIYAQ NUMBERS': {'slug': 'indic-siyaq-numbers', 'start': 126064},
 'OTTOMAN SIYAQ NUMBERS': {'slug': 'ottoman-siyaq-numbers', 'start': 126208},
 'ARABIC MATHEMATICAL ALPHABETIC SYMBOLS': {'slug': 'arabic-mathematical-alphabetic-symbols',
  'start': 126464},
 'MAHJONG TILES': {'slug': 'mahjong-tiles', 'start': 126976},
 'DOMINO TILES': {'slug': 'domino-tiles', 'start': 127024},
 'PLAYING CARDS': {'slug': 'playing-cards', 'start': 127136},
 'ENCLOSED ALPHANUMERIC SUPPLEMENT': {'slug': 'enclosed-alphanumeric-supplement',
  'start': 127232},
 'ENCLOSED IDEOGRAPHIC SUPPLEMENT': {'slug': 'enclosed-ideographic-supplement',
  'start': 127488},
 'EMOTICONS': {'slug': 'emoticons', 'start': 128512},
 'ORNAMENTAL DINGBATS': {'slug': 'ornamental-dingbats', 'start': 128592},
 'TRANSPORT AND MAP SYMBOLS': {'slug': 'transport-and-map-symbols',
  'start': 128640},
 'ALCHEMICAL SYMBOLS': {'slug': 'alchemical-symbols', 'start': 128768},
 'GEOMETRIC SHAPES EXTENDED': {'slug': 'geometric-shapes-extended',
  'start': 128896},
 'SUPPLEMENTAL ARROWS-C': {'slug': 'supplemental-arrows-c', 'start': 129024},
 'SUPPLEMENTAL SYMBOLS AND PICTOGRAPHS': {'slug': 'supplemental-symbols-and-pictographs',
  'start': 129280},
 'CHESS SYMBOLS': {'slug': 'chess-symbols', 'start': 129536},
 'SYMBOLS AND PICTOGRAPHS EXTENDED-A': {'slug': 'symbols-and-pictographs-extended-a',
  'start': 129648},
 'SYMBOLS FOR LEGACY COMPUTING': {'slug': 'symbols-for-legacy-computing',
  'start': 129792},
 'TAGS': {'slug': 'tags', 'start': 917504},
 'CJK UNIFIED IDEOGRAPHS EXTENSION C': {'slug': 'cjk-unified-ideographs-extension-c',
  'start': 173824},
 'CJK UNIFIED IDEOGRAPHS EXTENSION D': {'slug': 'cjk-unified-ideographs-extension-d',
  'start': 177984},
 'CJK UNIFIED IDEOGRAPHS EXTENSION E': {'slug': 'cjk-unified-ideographs-extension-e',
  'start': 178208},
 'CJK UNIFIED IDEOGRAPHS EXTENSION F': {'slug': 'cjk-unified-ideographs-extension-f',
  'start': 183984},
 'CJK UNIFIED IDEOGRAPHS EXTENSION G': {'slug': 'cjk-unified-ideographs-extension-g',
  'start': 196608},
 'TANGUT': {'slug': 'tangut', 'start': 94208},
 'CUNEIFORM': {'slug': 'cuneiform', 'start': 73728},
 'EGYPTIAN HIEROGLYPHS': {'slug': 'egyptian-hieroglyphs', 'start': 77824},
 'ANATOLIAN HIEROGLYPHS': {'slug': 'anatolian-hieroglyphs', 'start': 82944},
 'BAMUM SUPPLEMENT': {'slug': 'bamum-supplement', 'start': 92160},
 'TANGUT COMPONENTS': {'slug': 'tangut-components', 'start': 100352},
 'MATHEMATICAL ALPHANUMERIC SYMBOLS': {'slug': 'mathematical-alphanumeric-symbols',
  'start': 119808},
 'SUTTON SIGNWRITING': {'slug': 'sutton-signwriting', 'start': 120832},
 'CJK COMPATIBILITY IDEOGRAPHS SUPPLEMENT': {'slug': 'cjk-compatibility-ideographs-supplement',
  'start': 194560},
 'VARIATION SELECTORS SUPPLEMENT': {'slug': 'variation-selectors-supplement',
  'start': 917760},
 'SUPPLEMENTARY PRIVATE USE AREA-A': {'slug': 'supplementary-private-use-area-a',
  'start': 983040},
 'SUPPLEMENTARY PRIVATE USE AREA-B': {'slug': 'supplementary-private-use-area-b',
  'start': 1048576},
 'CJK UNIFIED IDEOGRAPHS EXTENSION B': {'slug': 'cjk-unified-ideographs-extension-b',
  'start': 131072},
 'CJK UNIFIED IDEOGRAPHS': {'slug': 'cjk-unified-ideographs', 'start': 19968},
 'UNIFIED CANADIAN ABORIGINAL SYLLABICS': {'slug': 'unified-canadian-aboriginal-syllabics',
  'start': 5120},
 'CJK UNIFIED IDEOGRAPHS EXTENSION A': {'slug': 'cjk-unified-ideographs-extension-a',
  'start': 13312},
 'MISCELLANEOUS SYMBOLS AND PICTOGRAPHS': {'slug': 'miscellaneous-symbols-and-pictographs',
  'start': 127744}}