# Generated by Django 3.0.7 on 2020-06-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='sequences',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='variantVers',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
