# Generated by Django 3.0.7 on 2020-06-21 07:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0002_auto_20200621_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('codePoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officialName', models.CharField(blank=True, max_length=100, null=True)),
                ('cpList', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('isEmoji', models.NullBooleanField(default=False)),
                ('glyphs', models.ManyToManyField(to='charChecker.Glyph')),
                ('minUnicodeVersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charChecker.UnicodeVersion')),
            ],
        ),
        migrations.AddField(
            model_name='font',
            name='sequences',
            field=models.ManyToManyField(blank=True, to='charChecker.Sequence'),
        ),
    ]
