# Generated by Django 3.0.7 on 2020-06-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0004_sequence_isprovisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyph',
            name='variantVers',
            field=models.ManyToManyField(blank=True, to='charChecker.Variant'),
        ),
    ]
