# Generated by Django 3.0.7 on 2020-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0005_glyph_variantvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='font',
            name='fileType',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
