# Generated by Django 3.0.7 on 2020-12-25 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0006_auto_20200621_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='cpList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, unique=True),
        ),
    ]
