# Generated by Django 3.0.7 on 2020-12-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0007_auto_20201225_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyph',
            name='emojiVersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glyphEmojiVersion', to='charChecker.UnicodeVersion'),
        ),
        migrations.AddField(
            model_name='glyph',
            name='hasBwEmoji',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='glyph',
            name='hasColorEmoji',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='emojiVersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seqEmojiVersion', to='charChecker.UnicodeVersion'),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='isEmoji',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='isNonCharacter',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='isReserved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
