# Generated by Django 3.0.7 on 2020-12-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0009_auto_20201225_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='cachedSupportPercent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
