# Generated by Django 3.0.7 on 2020-12-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0010_sequence_cachedsupportpercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='hasBwEmoji',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='hasColorEmoji',
        ),
    ]
