# Generated by Django 3.0.7 on 2020-12-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0011_auto_20201226_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='variantVers',
            field=models.ManyToManyField(blank=True, related_name='_sequence_variantVers_+', to='charChecker.Sequence'),
        ),
    ]
