# Generated by Django 3.0.7 on 2020-12-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0012_sequence_variantvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyph',
            name='bitmapSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charChecker.Font'),
        ),
    ]
