# Generated by Django 3.0.7 on 2020-12-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0013_glyph_bitmapsource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='font',
            unique_together={('name', 'version', 'style', 'fileName')},
        ),
    ]
