# Generated by Django 3.0.7 on 2020-12-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0014_auto_20201227_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicodeversion',
            name='isEmojiVersion',
            field=models.BooleanField(default=False),
        ),
    ]
