# Generated by Django 3.0.7 on 2020-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0015_unicodeversion_isemojiversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicodeversion',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='unicodeversion',
            unique_together={('number', 'isEmojiVersion')},
        ),
    ]
