# Generated by Django 3.0.7 on 2020-12-28 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charChecker', '0016_auto_20201227_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unicodeversion',
            options={'verbose_name': 'Unicode & Emoji version', 'verbose_name_plural': 'Unicode & Emoji versions'},
        ),
    ]
