fontList = [
    "Aharoni Bold",
    "Andalus",
    "Angsana New",
    "Angsana New Bold",
    "Angsana New Bold Italic",
    "Angsana New Italic",
    "AngsanaUPC",
    "AngsanaUPC Bold",
    "AngsanaUPC Bold Italic",
    "AngsanaUPC Italic",
    "Arabic Typesetting",
    "Arial",
    "Arial Black",
    "Arial Bold",
    "Arial Bold Italic",
    "Arial Italic",
    "Batang",
    "BatangChe",
    "Browallia New",
    "Browallia New Bold",
    "Browallia New Bold Italic",
    "Browallia New Italic",
    "BrowalliaUPC",
    "BrowalliaUPC Bold",
    "BrowalliaUPC Bold Italic",
    "BrowalliaUPC Italic",
    "Calibri",
    "Calibri Bold",
    "Calibri Bold Italic",
    "Calibri Italic",
    "Cambria",
    "Cambria Bold",
    "Cambria Bold Italic",
    "Cambria Italic",
    "Cambria Math",
    "Candara",
    "Candara Bold",
    "Candara Bold Italic",
    "Candara Italic",
    "Comic Sans MS",
    "Comic Sans MS Bold",
    "Consolas",
    "Consolas Bold",
    "Consolas Bold Italic",
    "Consolas Italic",
    "Constantia",
    "Constantia Bold",
    "Constantia Bold Italic",
    "Constantia Italic",
    "Corbel",
    "Corbel Bold",
    "Corbel Bold Italic",
    "Corbel Italic",
    "Cordia New",
    "Cordia New Bold",
    "Cordia New Bold Italic",
    "Cordia New Italic",
    "CordiaUPC",
    "CordiaUPC Bold",
    "CordiaUPC Bold Italic",
    "CordiaUPC Italic",
    "Courier New",
    "Courier New Bold",
    "Courier New Bold Italic",
    "Courier New Italic",
    "DaunPenh",
    "David",
    "David Bold",
    "DFKai-SB",
    "DilleniaUPC",
    "DilleniaUPC Bold",
    "DilleniaUPC Bold Italic",
    "DilleniaUPC Italic",
    "DokChampa",
    "Dotum",
    "DotumChe",
    "Estrangelo Edessa",
    "EucrosiaUPC",
    "EucrosiaUPC Bold",
    "EucrosiaUPC Bold Italic",
    "EucrosiaUPC Italic",
    "Euphemia",
    "FangSong",
    "Franklin Gothic Medium",
    "Franklin Gothic Medium Italic",
    "FrankRuehl",
    "FreesiaUPC",
    "FreesiaUPC Bold",
    "FreesiaUPC Bold Italic",
    "FreesiaUPC Italic",
    "Gautami",
    "Georgia",
    "Georgia Bold",
    "Georgia Bold Italic",
    "Georgia Italic",
    "Gisha",
    "Gisha Bold",
    "Gulim",
    "GulimChe",
    "Gungsuh",
    "GungsuhChe",
    "Impact",
    "IrisUPC",
    "IrisUPC Bold",
    "IrisUPC Bold Italic",
    "IrisUPC Italic",
    "Iskoola Pota",
    "JasmineUPC",
    "JasmineUPC Bold",
    "JasmineUPC Bold Italic",
    "JasmineUPC Italic",
    "KaiTi",
    "Kalinga",
    "Kartika",
    "KodchiangUPC",
    "KodchiangUPC Bold",
    "KodchiangUPC Bold Italic",
    "KodchiangUPC Italic",
    "Latha",
    "Leelawadee",
    "Leelawadee Bold",
    "Levenim MT",
    "Levenim MT Bold",
    "LilyUPC",
    "LilyUPC Bold",
    "LilyUPC Bold Italic",
    "LilyUPC Italic",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Malgun Gothic",
    "Malgun Gothic Bold",
    "Mangal",
    "Marlett",
    "Meiryo",
    "Meiryo Bold",
    "Meiryo Bold Italic",
    "Meiryo Italic",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Bold",
    "Microsoft Sans Serif",
    "Microsoft Uighur",
    "Microsoft YaHei",
    "Microsoft YaHei Bold",
    "Microsoft Yi Baiti",
    "MingLiU",
    "MingLiU_HKSCS",
    "MingLiU_HKSCS-ExtB",
    "MingLiU-ExtB",
    "Miriam",
    "Miriam Fixed",
    "Mongolian Baiti",
    "MoolBoran",
    "MS Gothic",
    "MS Mincho",
    "MS PGothic",
    "MS PMincho",
    "MS UI Gothic",
    "MV Boli",
    "Narkisim",
    "NSimSun",
    "Nyala",
    "Palatino Linotype",
    "Palatino Linotype Bold",
    "Palatino Linotype Bold Italic",
    "Palatino Linotype Italic",
    "Plantagenet Cherokee",
    "PMingLiU",
    "PMingLiU-ExtB",
    "Raavi",
    "Rod",
    "Segoe Print",
    "Segoe Print Bold",
    "Segoe Script",
    "Segoe Script Bold",
    "Segoe UI",
    "Segoe UI Bold",
    "Segoe UI Bold Italic",
    "Segoe UI Italic",
    "Shruti",
    "SimHei",
    "Simplified Arabic",
    "Simplified Arabic Bold",
    "Simplified Arabic Fixed",
    "SimSun",
    "SimSun-ExtB",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Tahoma Bold",
    "Times New Roman",
    "Times New Roman Bold",
    "Times New Roman Bold Italic",
    "Times New Roman Italic",
    "Traditional Arabic",
    "Traditional Arabic Bold",
    "Trebuchet MS",
    "Trebuchet MS Bold",
    "Trebuchet MS Bold Italic",
    "Trebuchet MS Italic",
    "Tunga",
    "Verdana",
    "Verdana Bold",
    "Verdana Bold Italic",
    "Verdana Italic",
    "Vrinda",
    "Webdings",
    "Wingdings"
]