iFonts = [["Academy Engraved Let Plain", "5", "4.3", "8", "—"],
["Al Nile", "Bold", "7", "7", "8", "—"],
["Al Nile", "7", "7", "8", "—"],
["American Typewriter", "3", "4.3", "8", "—"],
["American Typewriter", "Bold", "3", "4.3", "8", "—"],
["American Typewriter", "Condensed", "5", "5", "8", "—"],
["American Typewriter", "Condensed Bold", "5", "5", "8", "—"],
["American Typewriter", "Condensed Light", "5", "5", "8", "—"],
["American Typewriter", "Light", "5", "5", "8", "—"],
["Apple Color Emoji", "3", "4.3", "8", "9"],
["Apple SD Gothic Neo", "Thin", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "UltraLight", "9", "9", "9", "9"],
["Apple SD Gothic Neo", "Light", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "Regular", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "Medium", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "SemiBold", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "Bold", "7", "7", "8", "9"],
["Apple SD Gothic Neo", "Medium", "4.3", "4.3", "8", "—"],
["Arial MT", "3", "4.3", "8", "—"],
["Arial", "Bold Italic MT", "3", "4.3", "8", "—"],
["Arial", "Bold MT", "3", "4.3", "8", "—"],
["Arial", "Italic MT", "3", "4.3", "8", "—"],
["Arial Hebrew", "3", "4.3", "8", "9"],
["Arial Hebrew", "Bold", "3", "4.3", "8", "9"],
["Arial Hebrew", "Light", "8", "8", "8", "9"],
["Arial Rounded MT Bold", "3", "4.3", "8", "—"],
["Avenir Black", "Regular", "6", "6", "8", "9"],
["Avenir Black", "Oblique", "6", "6", "8", "9"],
["Avenir Book", "Regular", "6", "6", "8", "9"],
["Avenir Book", "Oblique", "6", "6", "8", "9"],
["Avenir Heavy", "Regular", "6", "6", "8", "9"],
["Avenir Heavy", "Oblique", "6", "6", "8", "9"],
["Avenir Light", "Regular", "6", "6", "8", "9"],
["Avenir Light", "Oblique", "6", "6", "8", "9"],
["Avenir Medium", "Regular", "6", "6", "8", "9"],
["Avenir Medium", "Oblique", "6", "6", "8", "9"],
["Avenir", "Oblique", "6", "6", "8", "9"],
["Avenir", "Roman", "6", "6", "8", "9"],
["Avenir Next", "Bold", "6", "6", "8", "9"],
["Avenir Next", "Bold Italic", "6", "6", "8", "9"],
["Avenir Next", "Demi Bold", "6", "6", "8", "9"],
["Avenir Next", "Demi Bold Italic", "6", "6", "8", "9"],
["Avenir Next", "Heavy", "6", "6", "8", "9"],
["Avenir Next", "Heavy Italic", "6", "6", "8", "9"],
["Avenir Next", "Italic", "6", "6", "8", "9"],
["Avenir Next", "Medium", "6", "6", "8", "9"],
["Avenir Next", "Medium Italic", "6", "6", "8", "9"],
["Avenir Next", "Regular", "6", "6", "8", "9"],
["Avenir Next", "Ultra Light", "6", "6", "8", "9"],
["Avenir Next", "Ultra Light Italic", "6", "6", "8", "9"],
["Avenir Next Condensed", "Bold", "6", "6", "8", "—"],
["Avenir Next Condensed", "Bold Italic", "6", "6", "8", "—"],
["Avenir Next Condensed", "Demi Bold", "6", "6", "8", "—"],
["Avenir Next Condensed", "Demi Bold Italic", "6", "6", "8", "—"],
["Avenir Next Condensed", "Heavy", "6", "6", "8", "—"],
["Avenir Next Condensed", "Heavy Italic", "6", "6", "8", "—"],
["Avenir Next Condensed", "Italic", "6", "6", "8", "—"],
["Avenir Next Condensed", "Medium", "6", "6", "8", "—"],
["Avenir Next Condensed", "Medium Italic", "6", "6", "8", "—"],
["Avenir Next Condensed", "Regular", "6", "6", "8", "—"],
["Avenir Next Condensed", "Ultra Light", "6", "6", "8", "—"],
["Avenir Next Condensed", "Ultra Light Italic", "6", "6", "8", "—"],
["Bangla Sangam MN", "3", "4.3", "8", "—"],
["Bangla Sangam MN", "Bold", "3", "4.3", "8", "—"],
["Baskerville", "3", "4.3", "8", "—"],
["Baskerville", "Bold", "3", "4.3", "8", "—"],
["Baskerville", "Bold Italic", "3", "4.3", "8", "—"],
["Baskerville", "Italic", "3", "4.3", "8", "—"],
["Baskerville", "Semi Bold", "5", "5", "8", "—"],
["Baskerville", "Semi Bold Italic", "5", "5", "8", "—"],
["Bodoni Ornaments", "Regular", "5", "4.3", "8", "—"],
["Bodoni 72", "Bold", "5", "4.3", "8", "—"],
["Bodoni 72", "Book", "5", "4.3", "8", "—"],
["Bodoni 72", "Book Italic", "5", "4.3", "8", "—"],
["Bodoni 72 Oldstyle", "Bold", "5", "4.3", "8", "—"],
["Bodoni 72 Oldstyle", "Book", "5", "4.3", "8", "—"],
["Bodoni 72 Oldstyle", "Book Italic", "5", "4.3", "8", "—"],
["Bodoni 72 Smallcaps", "Book", "5", "4.3", "8", "—"],
["Bradley Hand", "Bold", "6", "4.3", "8", "—"],
["Chalkboard SE", "Bold", "3", "4.3", "8", "—"],
["Chalkboard SE", "Light", "5", "5", "8", "—"],
["Chalkboard SE", "Regular", "3", "4.3", "8", "—"],
["Chalkduster", "5", "4.3", "8", "—"],
["Cochin", "3", "4.3", "8", "—"],
["Cochin", "Bold", "3", "4.3", "8", "—"],
["Cochin", "Bold Italic", "3", "4.3", "8", "—"],
["Cochin", "Italic", "3", "4.3", "8", "—"],
["Copperplate", "5", "4.3", "8", "9"],
["Copperplate", "Bold", "5", "4.3", "8", "9"],
["Copperplate", "Light", "5", "5", "8", "9"],
["Courier", "3", "4.3", "8", "9"],
["Courier", "Bold", "3", "4.3", "8", "9"],
["Courier", "Bold Oblique", "3", "4.3", "8", "9"],
["Courier", "Oblique", "3", "4.3", "8", "9"],
["Courier New PS", "Bold Italic MT", "3", "4.3", "8", "9"],
["Courier New PS", "Bold MT", "3", "4.3", "8", "9"],
["Courier New PS", "Italic MT", "3", "4.3", "8", "9"],
["Courier New PSMT", "3", "4.3", "8", "9"],
["DBLCDTemp Black", "☠", "6", "☠", "6", "—", "—"],
["DINAlternate", "Bold", "7", "7", "8", "—"],
["DINCondensed", "Bold", "7", "7", "8", "—"],
["Damascus Bold", "7", "7", "8", "—"],
["Damascus", "7", "7", "8", "—"],
["Damascus Light", "8", "8", "8", "—"],
["Damascus Medium", "7", "7", "8", "—"],
["Damascus Semi Bold", "7", "7", "8", "—"],
["Devanagari Sangam MN", "3", "4.3", "8", "—"],
["Devanagari Sangam MN", "Bold", "3", "4.3", "8", "—"],
["Didot", "5", "4.3", "8", "—"],
["Didot", "Bold", "5", "4.3", "8", "—"],
["Didot", "Italic", "5", "4.3", "8", "—"],
["Diwan Mishafi", "7", "7", "8", "—"],
["Euphemia UCAS", "6", "6", "8", "9"],
["Euphemia UCAS", "Bold", "6", "6", "8", "9"],
["Euphemia UCAS", "Italic", "6", "6", "8", "9"],
["Farah", "7", "7", "8", "—"],
["Futura", "Condensed Extra Bold", "3", "4.3", "8", "—"],
["Futura", "Condensed Medium", "5", "5", "8", "—"],
["Futura", "Medium", "3", "4.3", "8", "—"],
["Futura", "Medium Italic", "3", "4.3", "8", "—"],
["Geeza Pro", "3", "4.3", "8", "9"],
["Geeza Pro", "Bold", "3", "4.3", "8", "9"],
["Georgia", "3", "4.3", "8", "—"],
["Georgia", "Bold", "3", "4.3", "8", "—"],
["Georgia", "Bold Italic", "3", "4.3", "8", "—"],
["Georgia", "Italic", "3", "4.3", "8", "—"],
["Gill Sans", "5", "4.3", "8", "—"],
["Gill Sans", "Semi Bold", "9", "9", "9", "—"],
["Gill Sans", "Semi Bold Italic", "9", "9", "9", "—"],
["Gill Sans", "Bold", "5", "4.3", "8", "—"],
["Gill Sans", "Bold Italic", "5", "4.3", "8", "—"],
["Gill Sans", "Ultra Bold", "9", "9", "9", "—"],
["Gill Sans", "Italic", "5", "4.3", "8", "—"],
["Gill Sans", "Light", "5", "5", "8", "—"],
["Gill Sans", "Light Italic", "5", "5", "8", "—"],
["Gujarati Sangam MN", "3", "4.3", "8", "9"],
["Gujarati Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Gurmukhi MN", "3", "4.3", "8", "9"],
["Gurmukhi MN", "Bold", "3", "4.3", "8", "9"],
["Heiti SC", "Light", "3", "4.3", "8", "—"],
["Heiti SC", "Medium", "3", "4.3", "8", "—"],
["Heiti TC", "Light", "3", "4.3", "8", "—"],
["Heiti TC", "Medium", "3", "4.3", "8", "—"],
["Helvetica", "3", "4.3", "8", "9"],
["Helvetica", "Bold", "3", "4.3", "8", "9"],
["Helvetica", "Bold Oblique", "3", "4.3", "8", "9"],
["Helvetica", "Light", "5", "5", "8", "9"],
["Helvetica", "Light Oblique", "5", "5", "8", "9"],
["Helvetica", "Oblique", "3", "4.3", "8", "9"],
["Helvetica Neue", "3", "4.3", "8", "9"],
["Helvetica Neue", "Bold", "3", "4.3", "8", "9"],
["Helvetica Neue", "Bold Italic", "3", "4.3", "8", "9"],
["Helvetica Neue", "Condensed Black", "5", "5", "8", "9"],
["Helvetica Neue", "Condensed Bold", "5", "5", "8", "9"],
["Helvetica Neue", "Italic", "3", "4.3", "8", "9"],
["Helvetica Neue", "Light", "5", "5", "8", "9"],
["Helvetica Neue", "Light Italic", "5", "5", "8", "9"],
["Helvetica Neue", "Medium", "5", "5", "8", "9"],
["Helvetica Neue", "Medium Italic", "7", "7", "8", "9"],
["Helvetica Neue", "Ultra Light", "5", "5", "8", "9"],
["Helvetica Neue", "Ultra Light Italic", "5", "5", "8", "9"],
["Helvetica Neue", "Thin", "7", "7", "8", "9"],
["Helvetica Neue", "Thin Italic", "7", "7", "8", "9"],
["Hira Kaku Pro N", "W3", "☠", "9", "☠", "9", "☠", "9", "—"],
["Hira Kaku Pro N", "W6", "☠", "9", "☠", "9", "☠", "9", "—"],
["Hira Min Pro N", "W3", "3", "4.3", "8", "—"],
["Hira Min Pro N", "W6", "3", "4.3", "8", "—"],
["Hiragino Sans", "W3", "9", "9", "9", "—"],
["Hiragino Sans", "W6", "9", "9", "9", "—"],
["Hoefler Text", "Black", "5", "4.3", "8", "—"],
["Hoefler Text", "Black Italic", "5", "4.3", "8", "—"],
["Hoefler Text", "Italic", "5", "4.3", "8", "—"],
["Hoefler Text", "Regular", "5", "4.3", "8", "—"],
["Iowan Old Style", "Bold", "7", "7", "8", "9"],
["Iowan Old Style", "Bold Italic", "7", "7", "8", "9"],
["Iowan Old Style", "Italic", "7", "7", "8", "9"],
["Iowan Old Style", "Roman", "7", "7", "8", "9"],
["Kailasa", "3", "4.3", "8", "9"],
["Kailasa", "Bold", "3", "4.3", "8", "9"],
["Kannada Sangam MN", "3", "4.3", "8", "9"],
["Kannada Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Khmer Sangam MN", "8", "8", "8", "—"],
["Kohinoor Bangla", "Light", "9", "9", "9", "9"],
["Kohinoor Bangla", "Regular", "9", "9", "9", "9"],
["Kohinoor Bangla", "Semibold", "9", "9", "9", "9"],
["Kohinoor Devanagari", "Book", "8", "8", "8", "9"],
["Kohinoor Devanagari", "Light", "8", "8", "8", "9"],
["Kohinoor Devanagari", "Medium", "8", "8", "8", "9"],
["Kohinoor Telugu", "Light", "8", "8", "8", "9"],
["Kohinoor Telugu", "Regular", "8", "8", "8", "9"],
["Kohinoor Telugu", "Medium", "8", "8", "8", "9"],
["Lao Sangam MN", "8", "8", "8", "9"],
["Malayalam Sangam MN", "3", "4.3", "8", "9"],
["Malayalam Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Menlo", "Bold Italic", "7", "7", "8", "9"],
["Menlo", "Regular", "7", "7", "8", "9"],
["Menlo", "Bold", "7", "7", "8", "9"],
["Menlo", "Italic", "7", "7", "8", "9"],
["Marion", "Bold", "☠", "9", "☠", "9", "☠", "9", "—"],
["Marion", "Italic", "5", "9.0", "☠", "9", "☠", "9", "—"],
["Marion", "Regular", "☠", "9", "☠", "9", "☠", "9", "—"],
["Marker Felt", "Thin", "3", "4.3", "8", "—"],
["Marker Felt", "Wide", "3", "4.3", "8", "—"],
["Noteworthy", "Bold", "5", "5", "8", "—"],
["Noteworthy", "Light", "5", "5", "8", "—"],
["Optima", "Bold", "5", "4.3", "8", "—"],
["Optima", "Bold Italic", "5", "4.3", "8", "—"],
["Optima", "Extra Black", "5", "5", "8", "—"],
["Optima", "Italic", "5", "4.3", "8", "—"],
["Optima", "Regular", "5", "4.3", "8", "—"],
["Oriya Sangam MN", "3", "4.3", "8", "9"],
["Oriya Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Palatino", "Bold", "3", "4.3", "8", "—"],
["Palatino", "Bold Italic", "3", "4.3", "8", "—"],
["Palatino", "Italic", "3", "4.3", "8", "—"],
["Palatino", "Roman", "3", "4.3", "8", "—"],
["Papyrus", "5", "4.3", "8", "—"],
["Papyrus", "Condensed", "3", "5", "8", "—"],
["Party Let Plain", "5", "4.3", "8", "—"],
["PingFang HK", "Ultralight", "9", "9", "9", "9"],
["PingFang HK", "Light", "9", "9", "9", "9"],
["PingFang HK", "Thin", "9", "9", "9", "9"],
["PingFang HK", "Regular", "9", "9", "9", "9"],
["PingFang HK", "Medium", "9", "9", "9", "9"],
["PingFang HK", "Semibold", "9", "9", "9", "9"],
["PingFang SC", "Ultralight", "9", "9", "9", "9"],
["PingFang SC", "Light", "9", "9", "9", "9"],
["PingFang SC", "Thin", "9", "9", "9", "9"],
["PingFang SC", "Regular", "9", "9", "9", "9"],
["PingFang SC", "Medium", "9", "9", "9", "9"],
["PingFang SC", "Semibold", "9", "9", "9", "9"],
["PingFang TC", "Ultralight", "9", "9", "9", "9"],
["PingFang TC", "Light", "9", "9", "9", "9"],
["PingFang TC", "Thin", "9", "9", "9", "9"],
["PingFang TC", "Regular", "9", "9", "9", "9"],
["PingFang TC", "Medium", "9", "9", "9", "9"],
["PingFang TC", "Semibold", "9", "9", "9", "9"],
["SF Compact Display", "Black", "—", "—", "8.3", "—"],
["SF Compact Display", "Bold", "—", "—", "8.3", "—"],
["SF Compact Display", "Heavy", "—", "—", "8.3", "—"],
["SF Compact Display", "Light", "—", "—", "8.3", "—"],
["SF Compact Display", "Medium", "—", "—", "8.3", "—"],
["SF Compact Display", "Regular", "—", "—", "8.3", "—"],
["SF Compact Display", "Semibold", "—", "—", "8.3", "—"],
["SF Compact Display", "Thin", "—", "—", "8.3", "—"],
["SF Compact Display", "Ultralight", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Black", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Bold", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Heavy", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Light", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Medium", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Regular", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Semibold", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Thin", "—", "—", "8.3", "—"],
["SF Compact Rounded", "Ultralight", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold G1", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold G2", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold G3", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold Italic G1", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold Italic G2", "—", "—", "8.3", "—"],
["SF Compact Text", "Bold Italic G3", "—", "—", "8.3", "—"],
["SF Compact Text", "Heavy", "—", "—", "8.3", "—"],
["SF Compact Text", "Heavy Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Light", "—", "—", "8.3", "—"],
["SF Compact Text", "Light Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Medium", "—", "—", "8.3", "—"],
["SF Compact Text", "Medium Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular G1", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular G2", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular G3", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular Italic G1", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular Italic G2", "—", "—", "8.3", "—"],
["SF Compact Text", "Regular Italic G3", "—", "—", "8.3", "—"],
["SF Compact Text", "Semibold", "—", "—", "8.3", "—"],
["SF Compact Text", "Semibold Italic", "—", "—", "8.3", "—"],
["SF Compact Text", "Thin", "—", "—", "8.3", "—"],
["SF Compact Text", "Thin Italic", "—", "—", "8.3", "—"],
["Savoye LET Plain", "7", "7", "8", "8"],
["Sinhala Sangam MN", "3", "4.3", "8", "9"],
["Sinhala Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Snell Roundhand", "3", "4.3", "8", "—"],
["Snell Roundhand", "Black", "5", "5", "8", "—"],
["Snell Roundhand", "Bold", "3", "4.3", "8", "—"],
["Superclarendon", "Regular", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Bold Italic", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Light", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Black Italic", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Italic", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Light Italic", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Bold", "☠", "9", "☠", "9", "☠", "9", "—"],
["Superclarendon", "Black", "☠", "9", "☠", "9", "☠", "9", "—"],
["Symbol", "6", "6", "8", "9"],
["Tamil Sangam MN", "3", "4.3", "8", "9"],
["Tamil Sangam MN", "Bold", "3", "4.3", "8", "9"],
["Telugu Sangam MN", "3", "4.3", "8", "—"],
["Telugu Sangam MN", "Bold", "3", "4.3", "8", "—"],
["Thonburi", "3", "4.3", "8", "9"],
["Thonburi", "Bold", "3", "4.3", "8", "9"],
["Thonburi", "Light", "8", "8", "8", "9"],
["Times New Roman", "Bold Italic", "3", "4.3", "8", "9"],
["Times New Roman", "Bold", "3", "4.3", "8", "9"],
["Times New Roman", "Italic", "3", "4.3", "8", "9"],
["Times New Roman", "Regular", "3", "4.3", "8", "9"],
["Trebuchet", "Bold Italic", "3", "4.3", "8", "9"],
["Trebuchet MS", "3", "4.3", "8", "9"],
["Trebuchet MS", "Bold", "3", "4.3", "8", "9"],
["Trebuchet MS", "Italic", "3", "4.3", "8", "9"],
["Verdana", "3", "4.3", "8", "—"],
["Verdana", "Bold", "3", "4.3", "8", "—"],
["Verdana", "Bold Italic", "3", "4.3", "8", "—"],
["Verdana", "Italic", "3", "4.3", "8", "—"],
["Zapf Dingbats", "Regular", "5", "4.3", "8", "9"],
["Zapfino", "3", "4.3", "8", "—"]]

notFoundIfonts = [
    'Academy Engraved Let Plain Regular',
    '.Apple SDGothic Neo Thin',
    '.Apple SDGothic Neo Ultra Light',
    '.Apple SDGothic Neo Light',
    '.Apple SDGothic Neo Regular',
    '.Apple SDGothic Neo Medium',
    '.Apple SDGothic Neo Semi Bold',
    '.Apple SDGothic Neo Bold',
    '.Apple SDGothic Neo Medium',
    'Arial MT Regular',
    'Arial Rounded MTBold Regular',
    'Avenir Black',
    'Avenir Black Oblique',
    'Avenir Book',
    'Avenir Book Oblique',
    'Avenir Heavy',
    'Avenir Heavy Oblique',
    'Avenir Light',
    'Avenir Light Oblique',
    'Avenir Medium',
    'Avenir Medium Oblique',
    'Bodoni Ornaments ITCTT Regular',
    'Bodoni 72 ITCTT Bold',
    'Bodoni 72 ITCTT Book',
    'Bodoni 72 ITCTT Book Ita',
    'Bodoni 72 OSITCTT Bold',
    'Bodoni 72 OSITCTT Book',
    'Bodoni 72 OSITCTT Book It',
    'Bodoni 72 SCITCTT Book',
    'Bradley Hand ITCTT Bold',
    'Courier New PS Bold Italic MT',
    'Courier New PS Bold MT',
    'Courier New PS Italic MT',
    'Courier New PSMT Regular',
    'DINAlternate Bold',
    'DINCondensed Bold',
    'Damascus Bold Regular',
    'Damascus Light Regular',
    'Damascus Medium Regular',
    'Damascus Semi Bold Regular',
    'Diwan Mishafi Regular',
    'Futura Condensed Extra Bold',
    'Kailasa Bold',
    'Kohinoor Bangla Light',
    'Kohinoor Bangla Semibold',
    'Kohinoor Telugu Light',
    'Kohinoor Telugu Medium',
    'Party Let Plain Regular',
    'SF Compact Display Regular',
    'SF Compact Rounded Regular',
    'SF Compact Text Bold G1',
    'SF Compact Text Bold G2',
    'SF Compact Text Bold G3',
    'SF Compact Text Bold Italic G1',
    'SF Compact Text Bold Italic G2',
    'SF Compact Text Bold Italic G3',
    'SF Compact Text Regular',
    'SF Compact Text Regular G1',
    'SF Compact Text Regular G2',
    'SF Compact Text Regular G3',
    'SF Compact Text Regular Italic',
    'SF Compact Text Regular Italic G1',
    'SF Compact Text Regular Italic G2',
    'SF Compact Text Regular Italic G3',
    'Savoye Let Plain Regular',
    'Times New Roman PS Bold Italic MT',
    'Times New Roman PS Bold MT',
    'Times New Roman PS Italic MT',
    'Times New Roman PSMT Regular',
    'Trebuchet Bold Italic',
    'Zapf Dingbats ITC Regular'
]