#"Document Fonts", False, iOS 13", "macOS Catalina ],

ios13DocList = [
    ["Academy Engraved LET Plain:1.0", "13.0d1e2", False, True ],
    ["Al Firat Regular", "13.0d2e10", False, True ],
    ["Al Khalil Bold", "13.0d2e3", False, True ],
    ["Al Khalil Regular", "13.0d2e3", False, True ],
    ["Al Rafidain Al Fanni", "13.0d2e2", False, True ],
    ["Al Rafidain Regular", "13.0d2e1", False, True ],
    ["Algiers Regular", "13.0d2e1", False, True ],
    ["Asphalt Medium", "13.1d1e1", True, True ],
    ["Athelas Bold", "13.0d1e3", True, True ],
    ["Athelas Bold Italic", "13.0d1e3", True, True ],
    ["Athelas Italic", "13.0d1e3", True, True ],
    ["Athelas Regular", "13.0d1e3", True, True ],
    ["Balega Regular", "13.0d1e4", True, True ],
    ["Bank Gothic Light", "13.0d1e3", False, True ],
    ["Bank Gothic Medium", "13.0d1e3", False, True ],
    ["Basra Bold", "13.0d1e3", False, True ],
    ["Basra Regular", "13.0d1e3", False, True ],
    ["Bebas Neue", "13.0d1e1", True, False ],
    ["Blackmoor LET Plain:2.0", "13.0d1e4", False, True ],
    ["BlairMdITC TT Medium", "13.0d1e2", False, True ],
    ["Bodoni 72 Bold", "13.0d2e1", False, True ],
    ["Bodoni 72 Book", "13.0d2e1", False, True ],
    ["Bodoni 72 Book Italic", "13.0d2e1", False, True ],
    ["Bodoni 72 Oldstyle Bold", "13.0d2e1", False, True ],
    ["Bodoni 72 Oldstyle Book", "13.0d2e1", False, True ],
    ["Bodoni 72 Oldstyle Book Italic", "13.0d2e1", False, True ],
    ["Bodoni 72 Smallcaps Book", "13.0d2e1", False, True ],
    ["Bodoni Ornaments", "13.0d2e1", False, True ],
    ["Book Antiqua", "13.0d1e2", False, True ],
    ["Book Antiqua Bold", "13.0d1e2", False, True ],
    ["Book Antiqua Bold Italic", "13.0d1e2", False, True ],
    ["Book Antiqua Italic", "13.0d1e2", False, True ],
    ["Bookman Old Style", "13.0d1e3", False, True ],
    ["Bookman Old Style Bold", "13.0d1e3", False, True ],
    ["Bookman Old Style Bold Italic", "13.0d1e3", False, True ],
    ["Bookman Old Style Italic", "13.0d1e3", False, True ],
    ["Bordeaux Roman Bold LET Plain", "13.0d3e2", False, True ],
    ["Bradley Hand Bold", "14.0d0e1", False, True ],
    ["Braganza", "13.0d1e3", False, True ],
    ["Capitals", "13.0d1e2", False, True ],
    ["Carlito", "1.103", True, True ],
    ["Carlito Bold", "1.103", True, True ],
    ["Carlito Bold Italic", "1.103", True, True ],
    ["Carlito Italic", "1.103", True, True ],
    ["Century Gothic", "13.0d1e4", False, True ],
    ["Century Gothic Bold", "13.0d1e4", False, True ],
    ["Century Gothic Bold Italic", "13.0d1e4", False, True ],
    ["Century Gothic Italic", "13.0d1e4", False, True ],
    ["Century Schoolbook", "13.0d1e2", False, True ],
    ["Century Schoolbook Bold", "13.0d1e2", False, True ],
    ["Century Schoolbook Bold Italic", "13.0d1e2", False, True ],
    ["Century Schoolbook Italic", "13.0d1e2", False, True ],
    ["Charcoal CY", "13.0d1e2", False, True ],
    ["Dear Joe Four", "13.0d2e4", False, True ],
    ["Dear Joe Four Small", "13.0d2e4", False, True ],
    ["Dear Joe Four Small Semibold", "13.0d2e4", True, True ],
    ["Dijla Regular", "13.0d2e1", False, True ],
    ["Druk Heavy Italic", "14.0d2e2", True, True ],
    ["Druk Text Bold", "14.0d2e2", True, True ],
    ["Druk Wide Medium", "14.0d3e6", True, True ],
    ["Fakt Slab Stencil Pro Medium", "13.0d3e7", True, True ],
    ["Forgotten Futurist Bold", "13.0d1e3", False, True ],
    ["Forgotten Futurist Bold Italic", "13.0d1e3", False, True ],
    ["Forgotten Futurist Italic", "13.0d1e3", False, True ],
    ["Forgotten Futurist Regular", "13.0d1e3", False, True ],
    ["Forgotten Futurist Shadow", "13.0d1e3", False, True ],
    ["Garamond", "13.0d1e2", False, True ],
    ["Garamond Bold", "13.0d1e2", False, True ],
    ["Garamond Bold Italic", "13.0d1e2", False, True ],
    ["Garamond Italic", "13.0d1e2", False, True ],
    ["Geneva CY", "13.0d1e1", False, True ],
    ["Helvetica CY Bold", "13.0d1e2", False, True ],
    ["Helvetica CY BoldOblique", "13.0d1e2", False, True ],
    ["Helvetica CY Oblique", "13.0d1e2", False, True ],
    ["Helvetica CY Plain", "13.0d1e2", False, True ],
    ["Hiragino Kaku Gothic Pro W3", "15.0d1e5", True, True ],
    ["Hiragino Kaku Gothic Pro W6", "15.0d1e5", True, True ],
    ["Hiragino Kaku Gothic ProN W3", "15.0d1e5", True, True ],
    ["Hiragino Kaku Gothic ProN W6", "15.0d1e5", True, True ],
    ["Hiragino Kaku Gothic Std W8", "15.0d1e5", False, True ],
    ["Hiragino Kaku Gothic StdN W8", "15.0d1e5", False, True ],
    ["Hiragino Maru Gothic Pro W4", "15.0d1e2", True, True ],
    ["Hiragino Mincho Pro W3", "15.0d1e2", True, True ],
    ["Hiragino Mincho Pro W6", "15.0d1e2", True, True ],
    ["Hopper Script Regular", "13.0d1e4", False, True ],
    ["Iowan Old Style Black", "14.0d1e1", False, True ],
    ["Iowan Old Style Black Italic", "14.0d1e1", False, True ],
    ["Iowan Old Style Bold", "14.0d1e1", True, True ],
    ["Iowan Old Style Bold Italic", "14.0d1e1", True, True ],
    ["Iowan Old Style Italic", "14.0d1e1", True, True ],
    ["Iowan Old Style Roman", "14.0d1e1", True, True ],
    ["Iowan Old Style Titling", "14.0d1e1", False, True ],
    ["Jazz LET Plain:1.0", "13.0d1e3", False, True ],
    ["Journal Sans New Inline", "13.0d4e1", True, True ],
    ["Koufi Abjadi Regular", "13.0d1e5", False, True ],
    ["Laimoon Regular", "13.0d1e5", False, True ],
    ["Lantinghei TC Extralight", "13.0d2e1", False, True ],
    ["Marion Bold", "13.0d1e2", True, True ],
    ["Marion Italic", "13.0d1e2", True, True ],
    ["Marion Regular", "13.0d1e2", True, True ],
    ["Mona Lisa Solid ITC TT", "13.0d3e2", False, True ],
    ["Nisan Regular", "13.0d1e4", False, True ],
    ["Noto Sans Armenian Black", "15.0d1e2", False, True ],
    ["Noto Sans Armenian Bold", "15.0d1e2", True, True ],
    ["Noto Sans Armenian ExtraBold", "15.0d1e2", False, True ],
    ["Noto Sans Armenian ExtraLight", "15.0d1e2", False, True ],
    ["Noto Sans Armenian Light", "15.0d1e2", True, True ],
    ["Noto Sans Armenian Medium", "15.0d1e2", False, True ],
    ["Noto Sans Armenian Regular", "15.0d1e2", True, True ],
    ["Noto Sans Avestan Regular", "Version 2.000", True, True ],
    ["Noto Sans Armenian SemiBold", "15.0d1e2", False, True ],
    ["Noto Sans Armenian Thin", "15.0d1e2", False, True ],
    ["Noto Sans Avestan Regular", "Version 2.000", False, True ],
    ["Noto Sans Bamum Regular/td>", "Version 2.000", True, True ],
    ["Noto Sans Batak Regular", "Version 2.000", True, True ],
    ["Noto Sans Brahmi Regular", "Version 2.000", True, True ],
    ["Noto Sans Buginese Regular", "Version 2.000", True, True ],
    ["Noto Sans Buhid Regular", "Version 2.000", True, True ],
    ["Noto Sans Carian Regular", "Version 2.000", True, True ],
    ["Noto Sans Chakma Regular", "Version 2.001", True, True ],
    ["Noto Sans Cham Regular", "Version 2.000", True, True ],
    ["Noto Sans Coptic Regular", "Version 2.000", True, True ],
    ["Noto Sans Cuneiform Regular", "Version 2.000", True, True ],
    ["Noto Sans Cypriot", "Version 2.000", True, True ],
    ["Noto Sans Egyptian Hieroglyphs", "Version 2.000", True, True ],
    ["Noto Sans Glagolitic", "Version 2.000", True, True ],
    ["Noto Sans Gothic Regular", "Version 2.000", True, True ],
    ["Noto Sans Hanunoo Regular", "Version 2.000", True, True ],
    ["Noto Sans Imperial Aramaic Regular", "Version 2.000", True, True ],
    ["Noto Sans Inscriptional Pahlavi Regular", "Version 2.000", True, True ],
    ["Noto Sans Inscriptional Parthian Regular", "Version 2.000", True, True ],
    ["Noto Sans Kaithi Regular", "Version 2.000", True, True ],
    ["Noto Sans Kayah Li Regular", "Version 2.000", True, True ],
    ["Noto Sans Kharoshthi Regular", "Version 2.000", True, True ],
    ["Noto Sans Lepcha Regular", "Version 2.000", True, True ],
    ["Noto Sans Limbu Regular", "Version 2.000", True, True ],
    ["Noto Sans Linear B Regular", "Version 2.000", True, True ],
    ["Noto Sans Lisu Regular", "Version 2.000", True, True ],
    ["Noto Sans Lycian Regular", "Version 2.000", True, True ],
    ["Noto Sans Lydian Regular", "Version 2.000", True, True ],
    ["Noto Sans Mandaic Regular", "Version 2.000", True, True ],
    ["Noto Sans Meetei Mayek Regular", "Version 2.000", True, True ],
    ["Noto Sans Mongolian", "Version 2.000", True, True ],
    ["Noto Sans NKo Regular", "Version 2.000", True, True ],
    ["Noto Sans New Tai Lue Regular", "Version 2.000", True, True ],
    ["Noto Sans Ogham Regular", "Version 2.000", True, True ],
    ["Noto Sans Ol Chiki Regular", "Version 2.000", True, True ],
    ["Noto Sans Old Italic Regular", "Version 2.000", True, True ],
    ["Noto Sans Old Persian Regular", "Version 2.000", True, True ],
    ["Noto Sans Old South Arabian Regular", "Version 2.000", True, True ],
    ["Noto Sans Old Turkic Regular", "Version 2.000", True, True ],
    ["Noto Sans Osmanya Regular", "Version 2.000", True, True ],
    ["Noto Sans Phags Pa Regular", "Version 2.000", True, True ],
    ["Noto Sans Phoenician Regular", "Version 2.000", True, True ],
    ["Noto Sans Rejang Regular", "Version 2.000", True, True ],
    ["Noto Sans Runic Regular Regular", "Version 2.000", True, True ],
    ["Noto Sans Samaritan Regular", "Version 2.000", True, True ],
    ["Noto Sans Saurashtra Regular", "Version 2.000", True, True ],
    ["Noto Sans Shavian Regular", "Version 2.000", True, True ],
    ["Noto Sans Sundanese Regular", "Version 2.000", True, True ],
    ["Noto Sans Syloti Nagri Regular", "Version 2.000", True, True ],
    ["Noto Sans Syriac Eastern Regular", "Version 2.000", True, True ],
    ["Noto Sans Tagalog Regular", "Version 2.000", True, True ],
    ["Noto Sans Tagbanwa Regular", "Version 2.000", True, True ],
    ["Noto Sans Tai Le Regular", "Version 2.000", True, True ],
    ["Noto Sans Tai Tham", "Version 2.000", True, True ],
    ["Noto Sans Tai Viet Regular", "Version 2.000", True, True ],
    ["Noto Sans Thaana Regular", "Version 2.000", True, True ],
    ["Noto Sans Tifinagh Regular", "Version 2.000", True, True ],
    ["Noto Sans Ugaritic Regular", "Version 2.000", True, True ],
    ["Noto Sans Vai Regular", "Version 2.000", True, True ],
    ["Noto Sans Yi Regular", "Version 2.000", True, True ],
    ["Noto Sans Zawgyi Black", "14.0d4e1", False, True ],
    ["Noto Sans Zawgyi Bold", "14.0d4e1", True, True ],
    ["Noto Sans Zawgyi ExtraBold", "14.0d4e1", False, True ],
    ["Noto Sans Zawgyi ExtraLight", "14.0d4e1", False, True ],
    ["Noto Sans Zawgyi Light", "14.0d4e1", True, True ],
    ["Noto Sans Zawgyi Medium", "14.0d4e1", False, True ],
    ["Noto Sans Zawgyi Regular", "14.0d4e1", True, True ],
    ["Noto Sans Zawgyi SemiBold", "14.0d4e1", False, True ],
    ["Noto Sans Zawgyi Thin", "14.0d4e1", False, True ],
    ["Noto Serif Balinese Regular", "Version 2.000", True, True ],
    ["Party LET Plain", "13.0d1e2", False, True ],
    ["PortagoITC TT", "13.0d1e4", False, True ],
    ["Princetown LET", "13.0d1e2", False, True ],
    ["Raya Regular", "13.0d1e4", False, True ],
    ["Santa Fe LET Plain:1.0", "13.0d1e3", False, True ],
    ["STIXGeneral Bold", "Version 1.1.0", True, False ],
    ["STIXGeneral BoldItalic", "Version 1.1.0", True, False ],
    ["STIXGeneral Italic", "Version 1.1.0", True, False ],
    ["STIXGeneral Regular", "Version 1.1.0", True, False ],
    ["STIXIntegralsD Bold", "Version 1.1.0", True, False ],
    ["STIXIntegralsD Regular", "Version 1.1.0", True, False ],
    ["STIXIntegralsSm Bold", "Version 1.1.0", True, False ],
    ["STIXIntegralsSm Regular", "Version 1.1.0", True, False ],
    ["STIXIntegralsUp Bold", "Version 1.1.0", True, False ],
    ["STIXIntegralsUp Regular", "Version 1.1.0", True, False ],
    ["STIXIntegralsUpD Bold", "Version 1.1.0", True, False ],
    ["STIXIntegralsUpD Regular", "Version 1.1.0", True, False ],
    ["STIXIntegralsUpSm Bold", "Version 1.1.0", True, False ],
    ["STIXIntegralsUpSm Regular", "Version 1.1.0", True, False ],
    ["STIXNonUnicode Bold", "Version 1.1.0", True, False ],
    ["STIXNonUnicode BoldItalic", "Version 1.1.0", True, False ],
    ["STIXNonUnicode Italic", "Version 1.1.0", True, False ],
    ["STIXNonUnicode Regular", "Version 1.1.0", True, False ],
    ["STIXSizeFiveSym Regular", "Version 1.1.0", True, False ],
    ["STIXSizeFourSym Bold", "Version 1.1.0", True, False ],
    ["STIXSizeFourSym Regular", "Version 1.1.0", True, False ],
    ["STIXSizeOneSym Bold", "Version 1.1.0", True, False ],
    ["STIXSizeOneSym Regular", "Version 1.1.0", True, False ],
    ["STIXSizeThreeSym Bold", "Version 1.1.0", True, False ],
    ["STIXSizeThreeSym Regular", "Version 1.1.0", True, False ],
    ["STIXSizeTwoSym Bold", "Version 1.1.0", True, False ],
    ["STIXSizeTwoSym Regular", "Version 1.1.0", True, False ],
    ["STIXVariants Bold", "Version 1.1.0", True, False ],
    ["STIXVariants Regular", "Version 1.1.0", True, False ],
    ["Scheme Bold", "13.0d3e1", True, True ],
    ["Seravek", "13.0d3e2", True, True ],
    ["Seravek Bold", "13.0d3e2", True, True ],
    ["Seravek Bold Italic", "13.0d3e2", True, True ],
    ["Seravek ExtraLight", "13.0d3e2", True, True ],
    ["Seravek ExtraLight Italic", "13.0d3e2", True, True ],
    ["Seravek Italic", "13.0d3e2", True, True ],
    ["Seravek Light", "13.0d3e2", True, True ],
    ["Seravek Light Italic", "13.0d3e2", True, True ],
    ["Seravek Medium", "13.0d3e2", True, True ],
    ["Seravek Medium Italic", "13.0d3e2", True, True ],
    ["SignPainter-HouseScript Semibold", "14.0d1e1", True, False ],
    ["Somer Regular", "13.0d1e4", False, True ],
    ["Stone Sans ITC TT Bold", "13.0d2e1", False, True ],
    ["Stone Sans Sem ITC TT Semi", "13.0d2e1", False, True ],
    ["Stone Sans Sem ITC TT SemiIta", "13.0d2e1", False, True ],
    ["Superclarendon Black", "13.0d1e4", True, True ],
    ["Superclarendon Black Italic", "13.0d1e4", True, True ],
    ["Superclarendon Bold", "13.0d1e4", True, True ],
    ["Superclarendon Bold Italic", "13.0d1e4", True, True ],
    ["Superclarendon Italic", "13.0d1e4", True, True ],
    ["Superclarendon Light", "13.0d1e4", True, True ],
    ["Superclarendon Light Italic", "13.0d1e4", True, True ],
    ["Superclarendon Regular", "13.0d1e4", True, True ],
    ["Synchro LET", "13.0d4e1", False, True ],
    ["The Hand Serif Semibold", "13.1d1e1", True, True ],
    ["Tw Cen MT", "13.0d1e2", False, True ],
    ["Tw Cen MT Bold", "13.0d1e2", False, True ],
    ["Tw Cen MT Bold Italic", "13.0d1e2", False, True ],
    ["Tw Cen MT Italic", "13.0d1e2", False, True ],
    ["Type Embellishments One LET Plain:1.0", "13.0d2e7", False, True ],
    ["Yaziji Regular", "13.0d1e4", False, True ],
    ["Zawra Bold", "13.0d1e5", False, True ],
    ["Zawra Heavy", "13.0d1e5", False, True ],
]