#"Preinstalled Fonts", ",iOS 12", "macOS Mojave

iosList = [
    ["Academy Engraved LET Plain:1.0", "13.0d1e2", True, False],
    ["Al Bayan Bold", "13.0d1e6", False, True],
    ["Al Bayan Plain", "13.0d1e6", False, True],
    ["Al Nile", "13.0d2e2", True, True],
    ["Al Nile Bold", "13.0d2e2", True, True],
    ["Al Tarikh Regular", "13.0d2e1", False, True],
    ["American Typewriter", "13.0d1e4", True, True],
    ["American Typewriter Bold", "13.0d1e4", True, True],
    ["American Typewriter Condensed", "13.0d1e4", True, True],
    ["American Typewriter Condensed Bold", "13.0d1e4", True, True],
    ["American Typewriter Condensed Light", "13.0d1e4", True, True],
    ["American Typewriter Light", "13.0d1e4", True, True],
    ["American Typewriter Semibold", "13.0d1e4", True, True],
    ["Andale Mono", "Version 2.00x", False, True],
    ["Apple Braille", "13.0d2e27", False, True],
    ["Apple Braille Outline 6 Dot", "13.0d2e27", False, True],
    ["Apple Braille Outline 8 Dot", "13.0d2e27", False, True],
    ["Apple Braille Pinpoint 6 Dot", "13.0d2e27", False, True],
    ["Apple Braille Pinpoint 8 Dot", "13.0d2e27", False, True],
    ["Apple Chancery", "13.0d1e4", False, True],
    ["Apple Color Emoji", "13.2d1e1", True, True],
    ["Apple SD Gothic Neo Bold", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo Heavy", "13.0d1e9", False, True],
    ["Apple SD Gothic Neo Light", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo Medium", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo Regular", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo SemiBold", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo Thin", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo UltraLight", "13.0d1e9", True, True],
    ["Apple SD Gothic Neo ExtraBold", "13.0d1e9", False, True],
    ["Apple Symbols", "13.0d1e7", False, True],
    ["AppleGothic Regular", "13.0d1e3", False, True],
    ["AppleMyungjo Regular", "13.0d1e6", False, True],
    ["Arial", "Version 5.01.2x", True, False],
    ["Arial Black", "Version 5.00.1x", False, True],
    ["Arial Bold", "Version 5.01.2x", True, True],
    ["Arial Bold Italic", "Version 5.00.2x", True, True],
    ["Arial Hebrew", "13.0d1e1", True, True],
    ["Arial Hebrew Bold", "13.0d1e1", True, True],
    ["Arial Hebrew Light", "13.0d1e1", True, True],
    ["Arial Hebrew Scholar", "13.0d1e1", False, True],
    ["Arial Hebrew Scholar Bold", "13.0d1e1", False, True],
    ["Arial Hebrew Scholar Light", "13.0d1e1", False, True],
    ["Arial Italic", "Version 5.00.2x", True, True],
    ["Arial Narrow", "Version 2.38.1x", False, True],
    ["Arial Narrow Bold", "Version 2.38.1x", False, True],
    ["Arial Narrow Bold Italic", "Version 2.38.1x", False, True],
    ["Arial Narrow Italic", "Version 2.38.1x", False, True],
    ["Arial Rounded MT Bold", "Version 1.51x", True, True],
    ["Arial Unicode MS", "Version 1.01x", False, True],
    ["Avenir Black", "13.0d3e1", True, True],
    ["Avenir Black Oblique", "13.0d3e1", True, True],
    ["Avenir Book", "13.0d3e1", True, True],
    ["Avenir Book Oblique", "13.0d3e1", True, True],
    ["Avenir Heavy", "13.0d3e1", True, True],
    ["Avenir Heavy Oblique", "13.0d3e1", True, True],
    ["Avenir Light", "13.0d3e1", True, True],
    ["Avenir Light Oblique", "13.0d3e1", True, True],
    ["Avenir Medium", "13.0d3e1", True, True],
    ["Avenir Medium Oblique", "13.0d3e1", True, True],
    ["Avenir Next Bold", "13.0d1e10", True, True],
    ["Avenir Next Bold Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Bold", "13.0d1e10", True, True],
    ["Avenir Next Condensed Bold Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Demi Bold", "13.0d1e10", True, True],
    ["Avenir Next Condensed Demi Bold Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Heavy", "13.0d1e10", True, True],
    ["Avenir Next Condensed Heavy Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Medium", "13.0d1e10", True, True],
    ["Avenir Next Condensed Medium Italic", "13.0d1e10", True, True],
    ["Avenir Next Condensed Regular", "13.0d1e10", True, True],
    ["Avenir Next Condensed Ultra Light", "13.0d1e10", True, True],
    ["Avenir Next Condensed Ultra Light Italic", "13.0d1e10", True, True],
    ["Avenir Next Demi Bold", "13.0d1e10", True, True],
    ["Avenir Next Demi Bold Italic", "13.0d1e10", True, True],
    ["Avenir Next Heavy", "13.0d1e10", True, True],
    ["Avenir Next Heavy Italic", "13.0d1e10", True, True],
    ["Avenir Next Italic", "13.0d1e10", True, True],
    ["Avenir Next Medium", "13.0d1e10", True, True],
    ["Avenir Next Medium Italic", "13.0d1e10", True, True],
    ["Avenir Next Regular", "13.0d1e10", True, True],
    ["Avenir Next Ultra Light", "13.0d1e10", True, True],
    ["Avenir Next Ultra Light Italic", "13.0d1e10", True, True],
    ["Avenir Oblique", "13.0d3e1", True, True],
    ["Avenir Roman", "13.0d3e1", True, True],
    ["Ayuthaya", "13.0d1e7", False, True],
    ["Baghdad Regular", "13.0d1e5", False, True],
    ["Bangla MN", "14.0d1e2", False, True],
    ["Bangla MN Bold", "14.0d1e2", False, True],
    ["Bangla Sangam MN", "14.0d1e1", False, True],
    ["Bangla Sangam MN Bold", "14.0d1e1", False, True],
    ["Baskerville", "13.0d1e10", True, True],
    ["Baskerville Bold", "13.0d1e10", True, True],
    ["Baskerville Bold Italic", "13.0d1e10", True, True],
    ["Baskerville Italic", "13.0d1e10", True, True],
    ["Baskerville SemiBold", "13.0d1e10", True, True],
    ["Baskerville SemiBold Italic", "13.0d1e10", True, True],
    ["Bodoni 72 Bold", "13.0d2e1", True, True],
    ["Bodoni 72 Book", "13.0d2e1", True, True],
    ["Bodoni 72 Book Italic", "13.0d2e1", True, True],
    ["Bodoni 72 Oldstyle Bold", "13.0d2e1", True, True],
    ["Bodoni 72 Oldstyle Book", "13.0d2e1", True, True],
    ["Bodoni 72 Oldstyle Book Italic", "13.0d2e1", True, True],
    ["Bodoni 72 Smallcaps Book", "13.0d2e1", True, True],
    ["Bodoni Ornaments", "13.0d2e1", True, True],
    ["Bradley Hand Bold", "13.0d1e2", True, True],
    ["Brush Script MT Italic", "Version 1.52x-1", False, True],
    ["Chalkboard", "13.0d1e2", False, True],
    ["Chalkboard Bold", "13.0d1e2", False, True],
    ["Chalkboard SE Bold", "13.0d1e2", True, True],
    ["Chalkboard SE Light", "13.0d1e2", True, True],
    ["Chalkboard SE Regular", "13.0d1e2", True, True],
    ["Chalkduster", "13.0d2e1", True, True],
    ["Charter Black", "14.0d2e1", True, True],
    ["Charter Black Italic", "14.0d2e1", True, True],
    ["Charter Bold", "14.0d2e1", True, True],
    ["Charter Bold Italic", "14.0d2e1", True, True],
    ["Charter Italic", "14.0d2e1", True, True],
    ["Charter Roman", "14.0d2e1", True, True],
    ["Cochin", "13.0d2e1", True, True],
    ["Cochin Bold", "13.0d2e1", True, True],
    ["Cochin Bold Italic", "13.0d2e1", True, True],
    ["Cochin Italic", "13.0d2e1", True, True],
    ["Copperplate", "13.0d1e2", True, True],
    ["Copperplate Bold", "13.0d1e2", True, True],
    ["Copperplate Light", "13.0d1e2", True, True],
    ["Corsiva Hebrew", "13.0d1e4", False, True],
    ["Corsiva Hebrew Bold", "13.0d1e4", False, True],
    ["Courier", "13.0d1e1", True, True],
    ["Courier Bold", "13.0d1e1", True, True],
    ["Courier Bold Oblique", "13.0d1e1", True, True],
    ["Courier New", "Version 5.00.2x", True, True],
    ["Courier New Bold", "Version 5.00.2x", True, True],
    ["Courier New Bold Italic", "Version 5.00x", True, True],
    ["Courier New Italic", "Version 5.00.1x", True, True],
    ["Courier Oblique", "13.0d1e1", True, True],
    ["DIN Alternate Bold", "13.0d3e1", True, True],
    ["DIN Condensed Bold", "13.2d2e1", True, True],
    ["Damascus Bold", "13.0d3e9", True, True],
    ["Damascus Light", "13.0d3e9", True, True],
    ["Damascus Medium", "13.0d3e9", True, True],
    ["Damascus Regular", "13.0d3e9", True, True],
    ["Damascus Semi Bold", "13.0d3e9", True, True],
    ["DecoType Naskh Regular", "14.0d0e1", False, True],
    ["Devanagari MT", "13.0d1e3", False, True],
    ["Devanagari MT Bold", "13.0d1e3", False, True],
    ["Devanagari Sangam MN", "14.0d1e12", True, True],
    ["Devanagari Sangam MN Bold", "14.0d1e12", True, True],
    ["Didot", "13.0d1e3", True, True],
    ["Didot Bold", "13.0d1e3", True, True],
    ["Didot Italic", "13.0d1e3", True, True],
    ["Diwan Kufi Regular", "13.0d2e1", False, True],
    ["Diwan Thuluth Regular", "13.0d1e5", False, True],
    ["Euphemia UCAS", "13.0d1e2", True, True],
    ["Euphemia UCAS Bold", "13.0d1e2", True, True],
    ["Euphemia UCAS Italic", "13.0d1e2", True, True],
    ["Farah Regular", "13.0d2e3", True, True],
    ["Farisi Regular", "13.0d1e3", False, True],
    ["Futura Bold", "13.0d1e3", True, True],
    ["Futura Condensed ExtraBold", "13.0d1e3", True, True],
    ["Futura Condensed Medium", "13.0d1e3", True, True],
    ["Futura Medium", "13.0d1e3", True, True],
    ["Futura Medium Italic", "13.0d1e3", True, True],
    ["GB18030 Bitmap", "13.0d1e1", False, True],
    ["Geeza Pro Bold", "14.0d1e4", True, True],
    ["Geeza Pro Regular", "14.0d1e4", True, True],
    ["Geneva", "13.0d2e1", False, True],
    ["Georgia", "Version 5.00x-4", True, True],
    ["Georgia Bold", "Version 5.00x-4", True, True],
    ["Georgia Bold Italic", "Version 5.00x-4", True, True],
    ["Georgia Italic", "Version 5.00x-4", True, True],
    ["Gill Sans", "13.0d1e4", True, True],
    ["Gill Sans Bold", "13.0d1e4", True, True],
    ["Gill Sans Bold Italic", "13.0d1e4", True, True],
    ["Gill Sans Italic", "13.0d1e4", True, True],
    ["Gill Sans Light", "13.0d1e4", True, True],
    ["Gill Sans Light Italic", "13.0d1e4", True, True],
    ["Gill Sans SemiBold", "13.0d1e4", True, True],
    ["Gill Sans SemiBold Italic", "13.0d1e4", True, True],
    ["Gill Sans UltraBold", "13.0d1e4", True, True],
    ["Gujarati MT", "13.0d1e2", False, True],
    ["Gujarati MT Bold", "13.0d1e2", False, True],
    ["Gujarati Sangam MN", "14.0d2e1", True, True],
    ["Gujarati Sangam MN Bold", "14.0d2e1", True, True],
    ["Gurmukhi MN", "14.0d1e2", True, True],
    ["Gurmukhi MN Bold", "14.0d1e2", True, True],
    ["Gurmukhi MT", "13.0d1e4", False, True],
    ["Gurmukhi Sangam MN", "14.0d3e1", False, True],
    ["Gurmukhi Sangam MN Bold", "14.0d3e1", False, True],
    ["Heiti SC Light", "13.0d1e1", False, True],
    ["Heiti SC Medium", "13.0d1e1", False, True],
    ["Heiti TC Light", "13.0d1e1", False, True],
    ["Heiti TC Medium", "13.0d1e1", False, True],
    ["Helvetica", "13.0d1e1", True, True],
    ["Helvetica Bold", "13.0d1e1", True, True],
    ["Helvetica Bold Oblique", "13.0d1e1", True, True],
    ["Helvetica Light", "13.0d1e1", True, True],
    ["Helvetica Light Oblique", "13.0d1e1", True, True],
    ["Helvetica Neue", "13.0d2e2", True, True],
    ["Helvetica Neue Bold", "13.0d2e2", True, True],
    ["Helvetica Neue Bold Italic", "13.0d2e2", True, True],
    ["Helvetica Neue Condensed Black", "13.0d2e2", True, True],
    ["Helvetica Neue Condensed Bold", "13.0d2e2", True, True],
    ["Helvetica Neue Italic", "13.0d2e2", True, True],
    ["Helvetica Neue Light", "13.0d2e2", True, True],
    ["Helvetica Neue Light Italic", "13.0d2e2", True, True],
    ["Helvetica Neue Medium", "13.0d2e2", True, True],
    ["Helvetica Neue Medium Italic", "13.0d2e2", True, True],
    ["Helvetica Neue Thin", "13.0d2e2", True, True],
    ["Helvetica Neue Thin Italic", "13.0d2e2", True, True],
    ["Helvetica Neue UltraLight", "13.0d2e2", True, True],
    ["Helvetica Neue UltraLight Italic", "13.0d2e2", True, True],
    ["Helvetica Oblique", "13.0d1e1", True, True],
    ["Hiragino Kaku Gothic StdN W8", "13.0d2e7", False, True],
    ["Hiragino Maru Gothic ProN W4", "13.0d1e3", True, True],
    ["Hiragino Mincho ProN W3", "13.0d2e9", True, True],
    ["Hiragino Mincho ProN W6", "13.0d2e9", True, True],
    ["Hiragino Sans GB W3", "13.0d2e3", False, True],
    ["Hiragino Sans GB W6", "13.0d2e3", False, True],
    ["Hiragino Sans W0", "13.0d2e7", False, True],
    ["Hiragino Sans W1", "13.0d2e7", False, True],
    ["Hiragino Sans W2", "13.0d2e7", False, True],
    ["Hiragino Sans W3", "13.0d2e7", True, True],
    ["Hiragino Sans W4", "13.0d2e7", False, True],
    ["Hiragino Sans W5", "13.0d2e7", False, True],
    ["Hiragino Sans W6", "13.0d2e7", True, True],
    ["Hiragino Sans W7", "13.0d2e7", False, True],
    ["Hiragino Sans W8", "13.0d2e7", False, True],
    ["Hiragino Sans W9", "13.0d2e7", False, True],
    ["Hoefler Text", "13.0d2e20", True, True],
    ["Hoefler Text Black", "13.0d2e20", True, True],
    ["Hoefler Text Black Italic", "13.0d2e20", True, True],
    ["Hoefler Text Italic", "13.0d2e20", True, True],
    ["Hoefler Text Ornaments", "13.0d2e20", False, True],
    ["ITF Devanagari Bold", "14.0d3e6", False, True],
    ["ITF Devanagari Book", "14.0d3e6", False, True],
    ["ITF Devanagari Demi", "14.0d3e6", False, True],
    ["ITF Devanagari Light", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Bold", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Book", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Demi", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Light", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Medium", "14.0d3e6", False, True],
    ["ITF Devanagari Medium", "14.0d3e6", False, True],
    ["Impact", "Version 5.00x", False, True],
    ["InaiMathi", "13.0d1e5", False, True],
    ["InaiMathi Bold", "13.0d1e5", False, True],
    ["Kailasa Bold", "13.0d1e3", True, True],
    ["Kailasa Regular", "13.0d1e3", True, True],
    ["Kannada MN", "14.0d1e6", False, True],
    ["Kannada MN Bold", "14.0d1e6", False, True],
    ["Kannada Sangam MN", "14.0d2e4", True, True],
    ["Kannada Sangam MN Bold", "14.0d2e4", True, True],
    ["Kefa Bold", "13.0d1e3", False, True],
    ["Kefa Regular", "13.0d1e3", True, True],
    ["Khmer MN", "14.0d1e1", False, True],
    ["Khmer MN Bold", "14.0d1e1", False, True],
    ["Khmer Sangam MN", "14.0d1e9", True, True],
    ["Kohinoor Bangla", "14.0d2e3", True, True],
    ["Kohinoor Bangla Bold", "14.0d2e3", False, True],
    ["Kohinoor Bangla Light", "14.0d2e3", True, True],
    ["Kohinoor Bangla Medium", "14.0d2e3", False, True],
    ["Kohinoor Bangla Semibold", "14.0d2e3", True, True],
    ["Kohinoor Devanagari Bold", "14.0d4e1", False, True],
    ["Kohinoor Devanagari Light", "14.0d4e1", True, True],
    ["Kohinoor Devanagari Medium", "14.0d4e1", False, True],
    ["Kohinoor Devanagari Regular", "14.0d4e1", True, True],
    ["Kohinoor Devanagari Semibold", "14.0d4e1", True, True],
    ["Kohinoor Telugu", "14.0d1e3", True, True],
    ["Kohinoor Telugu Bold", "14.0d1e3", False, True],
    ["Kohinoor Telugu Light", "14.0d1e3", True, True],
    ["Kohinoor Telugu Medium", "14.0d1e3", True, True],
    ["Kohinoor Telugu Semibold", "14.0d1e3", False, True],
    ["Kokonor Regular", "13.0d1e3", False, True],
    ["Krungthep", "14.0d1e1", False, True],
    ["KufiStandardGK Regular", "13.0d1e11", False, True],
    ["Lao MN", "14.0d1e9", False, True],
    ["Lao MN Bold", "14.0d1e9", False, True],
    ["Lao Sangam MN", "14.0d1e6", True, True],
    ["Lucida Grande", "13.0d1e1", False, True],
    ["Lucida Grande Bold", "13.0d1e1", False, True],
    ["Luminari", "13.0d1e2", False, True],
    ["Malayalam MN", "14.0d1e6", False, True],
    ["Malayalam MN Bold", "14.0d1e6", False, True],
    ["Malayalam Sangam MN", "14.0d1e1", True, True],
    ["Malayalam Sangam MN Bold", "14.0d1e1", True, True],
    ["Marker Felt Thin", "13.0d1e1", True, True],
    ["Marker Felt Wide", "13.0d1e1", True, True],
    ["Menlo Bold", "13.0d1e3", True, True],
    ["Menlo Bold Italic", "13.0d1e3", True, True],
    ["Menlo Italic", "13.0d1e3", True, True],
    ["Menlo Regular", "13.0d1e3", True, True],
    ["Microsoft Sans Serif", "Version 5.00.1x", False, True],
    ["Mishafi Gold Regular", "13.0d2e1", False, True],
    ["Mishafi Regular", "13.0d2e1", True, True],
    ["Monaco", "13.0d1e2", False, True],
    ["Mshtakan", "14.0d1e1", False, True],
    ["Mshtakan Bold", "14.0d1e1", False, True],
    ["Mshtakan BoldOblique", "14.0d1e1", False, True],
    ["Mshtakan Oblique", "14.0d1e1", False, True],
    ["Muna Black", "13.0d1e4", False, True],
    ["Muna Bold", "13.0d1e4", False, True],
    ["Muna Regular", "13.0d1e4", False, True],
    ["Myanmar MN", "14.0d1e2", False, True],
    ["Myanmar MN Bold", "14.0d1e2", False, True],
    ["Myanmar Sangam MN", "14.0d1e8", True, True],
    ["Myanmar Sangam MN Bold", "14.0d1e8", True, True],
    ["Nadeem Regular", "13.0d1e3", False, True],
    ["New Peninim MT", "13.0d1e4", False, True],
    ["New Peninim MT Bold", "13.0d1e4", False, True],
    ["New Peninim MT Bold Inclined", "13.0d1e4", False, True],
    ["New Peninim MT Inclined", "13.0d1e4", False, True],
    ["Noteworthy Bold", "13.0d1e11", True, True],
    ["Noteworthy Light", "13.0d1e11", True, True],
    ["Noto Nastaliq Urdu", "13.0d1e2", True, True],
    ["Optima Bold", "13.0d1e2", True, True],
    ["Optima Bold Italic", "13.0d1e2", True, True],
    ["Optima ExtraBlack", "13.0d1e2", True, True],
    ["Optima Italic", "13.0d1e2", True, True],
    ["Optima Regular", "13.0d1e2", True, True],
    ["Oriya MN", "14.0d1e6", False, True],
    ["Oriya MN Bold", "14.0d1e6", False, True],
    ["Oriya Sangam MN", "14.0d1e2", True, True],
    ["Oriya Sangam MN Bold", "14.0d1e2", True, True],
    ["PT Mono", "13.0d2e4", False, True],
    ["PT Mono Bold", "13.0d2e4", False, True],
    ["PT Sans", "13.0d3e2", False, True],
    ["PT Sans Bold", "13.0d3e2", False, True],
    ["PT Sans Bold Italic", "13.0d3e2", False, True],
    ["PT Sans Caption", "13.0d3e2", False, True],
    ["PT Sans Caption Bold", "13.0d3e2", False, True],
    ["PT Sans Italic", "13.0d3e2", False, True],
    ["PT Sans Narrow", "13.0d3e2", False, True],
    ["PT Sans Narrow Bold", "13.0d3e2", False, True],
    ["PT Serif", "13.0d2e1", False, True],
    ["PT Serif Bold", "13.0d2e1", False, True],
    ["PT Serif Bold Italic", "13.0d2e1", False, True],
    ["PT Serif Caption", "13.0d2e1", False, True],
    ["PT Serif Caption Italic", "13.0d2e1", False, True],
    ["PT Serif Italic", "13.0d2e1", False, True],
    ["Palatino", "13.0d1e2", True, True],
    ["Palatino Bold", "13.0d1e2", True, True],
    ["Palatino Bold Italic", "13.0d1e2", True, True],
    ["Palatino Italic", "13.0d1e2", True, True],
    ["Papyrus", "13.0d1e2", True, True],
    ["Papyrus Condensed", "13.0d1e2", True, True],
    ["Party LET Plain", "13.0d1e2", True, False],
    ["Phosphate Inline", "13.0d1e2", False, True],
    ["Phosphate Solid", "13.0d1e2", False, True],
    ["PingFang HK Light", "13.0d1e3", True, True],
    ["PingFang HK Medium", "13.0d1e3", True, True],
    ["PingFang HK Regular", "13.0d1e3", True, True],
    ["PingFang HK Semibold", "13.0d1e3", True, True],
    ["PingFang HK Thin", "13.0d1e3", True, True],
    ["PingFang HK Ultralight", "13.0d1e3", True, True],
    ["PingFang SC Light", "13.0d1e3", True, True],
    ["PingFang SC Medium", "13.0d1e3", True, True],
    ["PingFang SC Regular", "13.0d1e3", True, True],
    ["PingFang SC Semibold", "13.0d1e3", True, True],
    ["PingFang SC Thin", "13.0d1e3", True, True],
    ["PingFang SC Ultralight", "13.0d1e3", True, True],
    ["PingFang TC Light", "13.0d1e3", True, True],
    ["PingFang TC Medium", "13.0d1e3", True, True],
    ["PingFang TC Regular", "13.0d1e3", True, True],
    ["PingFang TC Semibold", "13.0d1e3", True, True],
    ["PingFang TC Thin", "13.0d1e3", True, True],
    ["PingFang TC Ultralight", "13.0d1e3", True, True],
    ["Plantagenet Cherokee", "13.0d1e3", False, True],
    ["Raanana", "13.0d1e3", False, True],
    ["Raanana Bold", "13.0d1e3", False, True],
    ["Rockwell", "13.0d2e1", True, True],
    ["Rockwell Bold", "13.0d2e1", True, True],
    ["Rockwell Bold Italic", "13.0d2e1", True, True],
    ["Rockwell Italic", "13.0d2e1", True, True],
    ["STIXGeneral-Bold", "Version 1.1.0", False, True],
    ["STIXGeneral-BoldItalic", "Version 1.1.0", False, True],
    ["STIXGeneral-Italic", "Version 1.1.0", False, True],
    ["STIXGeneral-Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsD-Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsD-Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsSm-Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsSm-Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUp-Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUp-Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUpD-Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUpD-Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUpSm-Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUpSm-Regular", "Version 1.1.0", False, True],
    ["STIXNonUnicode-Bold", "Version 1.1.0", False, True],
    ["STIXNonUnicode-BoldItalic", "Version 1.1.0", False, True],
    ["STIXNonUnicode-Italic", "Version 1.1.0", False, True],
    ["STIXNonUnicode-Regular", "Version 1.1.0", False, True],
    ["STIXSizeFiveSym-Regular", "Version 1.1.0", False, True],
    ["STIXSizeFourSym-Bold", "Version 1.1.0", False, True],
    ["STIXSizeFourSym-Regular", "Version 1.1.0", False, True],
    ["STIXSizeOneSym-Bold", "Version 1.1.0", False, True],
    ["STIXSizeOneSym-Regular", "Version 1.1.0", False, True],
    ["STIXSizeThreeSym-Bold", "Version 1.1.0", False, True],
    ["STIXSizeThreeSym-Regular", "Version 1.1.0", False, True],
    ["STIXSizeTwoSym-Bold", "Version 1.1.0", False, True],
    ["STIXSizeTwoSym-Regular", "Version 1.1.0", False, True],
    ["STIXVariants-Bold", "Version 1.1.0", False, True],
    ["STIXVariants-Regular", "Version 1.1.0", False, True],
    ["STSong", "13.0d3e2", False, True],
    ["Sana Regular", "13.0d1e4", False, True],
    ["Sathu", "14.0d1e1", False, True],
    ["Savoye LET Plain:1.0", "13.0d2e4", True, True],
    ["Shree Devanagari 714", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Bold", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Bold Italic", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Italic", "13.0d2e1", False, True],
    ["SignPainter-HouseScript", "13.0d1e5", False, True],
    ["SignPainter-HouseScript Semibold", "13.0d1e5", False, True],
    ["Silom", "14.0d1e1", False, True],
    ["Sinhala MN", "14.0d1e1", False, True],
    ["Sinhala MN Bold", "14.0d1e1", False, True],
    ["Sinhala Sangam MN", "14.0d1e2", True, True],
    ["Sinhala Sangam MN Bold", "14.0d1e2", True, True],
    ["Skia Black", "13.0d1e54", False, True],
    ["Skia Black Condensed", "13.0d1e54", False, True],
    ["Skia Black Extended", "13.0d1e54", False, True],
    ["Skia Bold", "13.0d1e54", False, True],
    ["Skia Condensed", "13.0d1e54", False, True],
    ["Skia Extended", "13.0d1e54", False, True],
    ["Skia Light", "13.0d1e54", False, True],
    ["Skia Light Condensed", "13.0d1e54", False, True],
    ["Skia Light Extended", "13.0d1e54", False, True],
    ["Skia Regular", "13.0d1e54", False, True],
    ["Snell Roundhand", "13.0d1e1", True, True],
    ["Snell Roundhand Black", "13.0d1e1", True, True],
    ["Snell Roundhand Bold", "13.0d1e1", True, True],
    ["Songti SC Black", "13.0d3e2", False, True],
    ["Songti SC Bold", "13.0d3e2", False, True],
    ["Songti SC Light", "13.0d3e2", False, True],
    ["Songti SC Regular", "13.0d3e2", False, True],
    ["Songti TC Bold", "13.0d3e2", False, True],
    ["Songti TC Light", "13.0d3e2", False, True],
    ["Songti TC Regular", "13.0d3e2", False, True],
    ["Sukhumvit Set Bold", "13.0d1e6", False, True],
    ["Sukhumvit Set Light", "13.0d1e", False, True],
    ["Sukhumvit Set Medium", "13.0d1e6", False, True],
    ["Sukhumvit Set Semi Bold", "13.0d1e6", False, True],
    ["Sukhumvit Set Text", "13.0d1e6", False, True],
    ["Sukhumvit Set Thin", "13.0d1e6", False, True],
    ["Symbol", "13.0d2e2", True, True],
    ["Tahoma", "Version 5.01.2x", False, True],
    ["Tahoma Bold", "Version 5.01.1x", False, True],
    ["Tamil MN", "14.0d1e7", False, True],
    ["Tamil MN Bold", "14.0d1e7", False, True],
    ["Tamil Sangam MN", "14.0d1e15", True, True],
    ["Tamil Sangam MN Bold", "14.0d1e15", True, True],
    ["Telugu MN", "14.0d1e2", False, True],
    ["Telugu MN Bold", "14.0d1e2", False, True],
    ["Telugu Sangam MN", "14.0d1e4", False, True],
    ["Telugu Sangam MN Bold", "14.0d1e4", False, True],
    ["Thonburi", "13.0d1e1", True, True],
    ["Thonburi Bold", "13.0d1e1", True, True],
    ["Thonburi Light", "13.0d1e1", True, True],
    ["Times Bold", "14.0d1e4", False, True],
    ["Times Bold Italic", "14.0d1e4", False, True],
    ["Times Italic", "14.0d1e4", False, True],
    ["Times New Roman", "Version 5.01.3x", True, True],
    ["Times New Roman Bold", "Version 5.01.3x", True, True],
    ["Times New Roman Bold Italic", "Version 5.00.3x", True, True],
    ["Times New Roman Italic", "Version 5.00.3x", True, True],
    ["Times Roman", "14.0d1e4", False, True],
    ["Trattatello", "13.0d2e2", False, True],
    ["Trebuchet MS", "Version 5.00x", True, True],
    ["Trebuchet MS Bold", "Version 5.00x", True, True],
    ["Trebuchet MS Bold Italic", "Version 5.00x", True, True],
    ["Trebuchet MS Italic", "Version 5.00x", True, True],
    ["Verdana", "Version 5.01x", True, True],
    ["Verdana Bold", "Version 5.01x", True, True],
    ["Verdana Bold Italic", "Version 5.01x", True, True],
    ["Verdana Italic", "Version 5.01x", True, True],
    ["Waseem Light", "13.0d1e2", False, True],
    ["Waseem Regular", "13.0d1e2", False, True],
    ["Webdings", "Version 5.00x", False, True],
    ["Wingdings", "Version 5.00x", False, True],
    ["Wingdings 2", "Version 1.55x", False, True],
    ["Wingdings 3", "Version 1.55x", False, True],
    ["Zapf Dingbats", "13.0d1e2", True, True],
    ["Zapfino", "13.0d1e2", True, True],
    ["Academy Engraved LET Plain:1.0", "13.0d1e2", False, True],
    ["Al Firat Regular", "13.0d2e10", False, True],
    ["Al Khalil Bold", "13.0d2e3", False, True],
    ["Al Khalil Regular", "13.0d2e3", False, True],
    ["Al Rafidain Al Fanni", "13.0d2e2", False, True],
    ["Al Rafidain Regular", "13.0d2e1", False, True],
    ["Algiers Regular", "13.0d2e1", False, True],
    ["Asphalt Medium", "13.1d1e1", True, True],
    ["Athelas Bold", "13.0d1e3", True, True],
    ["Athelas Bold Italic", "13.0d1e3", True, True],
    ["Athelas Italic", "13.0d1e3", True, True],
    ["Athelas Regular", "13.0d1e3", True, True],
    ["Balega Regular", "13.0d1e4", True, True],
    ["Bank Gothic Light", "13.0d1e3", False, True],
    ["Bank Gothic Medium", "13.0d1e3", False, True],
    ["Basra Bold", "13.0d1e3", False, True],
    ["Basra Regular", "13.0d1e3", False, True],
    ["Bebas Neue", "13.0d1e1", True, False],
    ["Blackmoor LET Plain:2.0", "13.0d1e4", False, True],
    ["BlairMdITC TT Medium", "13.0d1e2", False, True],
    ["Bodoni 72 Bold", "13.0d2e1", False, True],
    ["Bodoni 72 Book", "13.0d2e1", False, True],
    ["Bodoni 72 Book Italic", "13.0d2e1", False, True],
    ["Bodoni 72 Oldstyle Bold", "13.0d2e1", False, True],
    ["Bodoni 72 Oldstyle Book", "13.0d2e1", False, True],
    ["Bodoni 72 Oldstyle Book Italic", "13.0d2e1", False, True],
    ["Bodoni 72 Smallcaps Book", "13.0d2e1", False, True],
    ["Bodoni Ornaments", "13.0d2e1", False, True],
    ["Book Antiqua", "13.0d1e2", False, True],
    ["Book Antiqua Bold", "13.0d1e2", False, True],
    ["Book Antiqua Bold Italic", "13.0d1e2", False, True],
    ["Book Antiqua Italic", "13.0d1e2", False, True],
    ["Bookman Old Style", "13.0d1e3", False, True],
    ["Bookman Old Style Bold", "13.0d1e3", False, True],
    ["Bookman Old Style Bold Italic", "13.0d1e3", False, True],
    ["Bookman Old Style Italic", "13.0d1e3", False, True],
    ["Bordeaux Roman Bold LET Plain", "13.0d3e2", False, True],
    ["Bradley Hand Bold", "13.0d1e2", False, True],
    ["Braganza", "13.0d1e3", False, True],
    ["Capitals", "13.0d1e2", False, True],
    ["Century Gothic", "13.0d1e4", False, True],
    ["Century Gothic Bold", "13.0d1e4", False, True],
    ["Century Gothic Bold Italic", "13.0d1e4", False, True],
    ["Century Gothic Italic", "13.0d1e4", False, True],
    ["Century Schoolbook", "13.0d1e2", False, True],
    ["Century Schoolbook Bold", "13.0d1e2", False, True],
    ["Century Schoolbook Bold Italic", "13.0d1e2", False, True],
    ["Century Schoolbook Italic", "13.0d1e2", False, True],
    ["Charcoal CY", "13.0d1e2", False, True],
    ["Dear Joe Four", "13.0d2e4", False, True],
    ["Dear Joe Four Small", "13.0d2e4", False, True],
    ["Dear Joe Four Small Semibold", "13.0d2e4", True, True],
    ["Dijla Regular", "13.0d2e1", False, True],
    ["Druk Heavy Italic", "13.0d1e2", True, True],
    ["Fakt Slab Stencil Pro Medium", "13.0d3e7", True, True],
    ["Forgotten Futurist Bold", "13.0d1e3", False, True],
    ["Forgotten Futurist Bold Italic", "13.0d1e3", False, True],
    ["Forgotten Futurist Italic", "13.0d1e3", False, True],
    ["Forgotten Futurist Regular", "13.0d1e3", False, True],
    ["Forgotten Futurist Shadow", "13.0d1e3", False, True],
    ["Garamond", "13.0d1e2", False, True],
    ["Garamond Bold", "13.0d1e2", False, True],
    ["Garamond Bold Italic", "13.0d1e2", False, True],
    ["Garamond Italic", "13.0d1e2", False, True],
    ["Geneva CY", "13.0d1e1", False, True],
    ["Helvetica CY Bold", "13.0d1e2", False, True],
    ["Helvetica CY BoldOblique", "13.0d1e2", False, True],
    ["Helvetica CY Oblique", "13.0d1e2", False, True],
    ["Helvetica CY Plain", "13.0d1e2", False, True],
    ["Hiragino Kaku Gothic Pro W3", "13.0d2e7", True, True],
    ["Hiragino Kaku Gothic Pro W6", "13.0d2e7", True, True],
    ["Hiragino Kaku Gothic ProN W3", "13.0d2e7", True, True],
    ["Hiragino Kaku Gothic ProN W6", "13.0d2e7", True, True],
    ["Hiragino Kaku Gothic Std W8", "13.0d2e7", False, True],
    ["Hiragino Maru Gothic Pro W4", "13.0d1e3", True, True],
    ["Hiragino Mincho Pro W3", "13.0d2e9", True, True],
    ["Hiragino Mincho Pro W6", "13.0d2e9", True, True],
    ["Hopper Script Regular", "13.0d1e4", False, True],
    ["Iowan Old Style Black", "13.0d1e4", False, True],
    ["Iowan Old Style Black Italic", "13.0d1e4", False, True],
    ["Iowan Old Style Bold", "13.0d1e4", True, True],
    ["Iowan Old Style Bold Italic", "13.0d1e4", True, True],
    ["Iowan Old Style Italic", "13.0d1e4", True, True],
    ["Iowan Old Style Roman", "13.0d1e4", True, True],
    ["Iowan Old Style Titling", "13.0d1e4", False, True],
    ["Jazz LET Plain:1.0", "13.0d1e3", False, True],
    ["Journal Sans New Inline", "13.0d4e1", True, True],
    ["Koufi Abjadi Regular", "13.0d1e5", False, True],
    ["Laimoon Regular", "13.0d1e5", False, True],
    ["Lantinghei TC Extralight", "13.0d2e1", False, True],
    ["Lock Clock Light", "6.1d5e1", True, False],
    ["Marion Bold", "13.0d1e2", True, True],
    ["Marion Italic", "13.0d1e2", True, True],
    ["Marion Regular", "13.0d1e2", True, True],
    ["Mona Lisa Solid ITC TT", "13.0d3e2", False, True],
    ["Nisan Regular", "13.0d1e4", False, True],
    ["Noto Sans Avestan", "Version 1.04 uh", True, True],
    ["Noto Sans Balinese", "Version 1.03 uh", True, True],
    ["Noto Sans Bamum", "Version 1.03 uh", True, True],
    ["Noto Sans Batak", "Version 1.05 uh", True, True],
    ["Noto Sans Brahmi", "Version 1.03 uh", True, True],
    ["Noto Sans Buginese", "Version 1.05 uh", True, True],
    ["Noto Sans Buhid", "Version 1.03 uh", True, True],
    ["Noto Sans Carian", "Version 1.05 uh", True, True],
    ["Noto Sans Cham", "Version 1.01 uh", True, True],
    ["Noto Sans Coptic", "Version 1.03 uh", True, True],
    ["Noto Sans Cuneiform", "Version 1.05 uh", True, True],
    ["Noto Sans Cypriot", "Version 1.03 uh", True, True],
    ["Noto Sans Egyptian Hieroglyphs", "Version 1.04 uh", True, True],
    ["Noto Sans Glagolitic", "Version 1.04 uh", True, True],
    ["Noto Sans Gothic", "Version 1.03 uh", True, True],
    ["Noto Sans Hanunoo", "Version 1.04 uh", True, True],
    ["Noto Sans Imperial Aramaic", "Version 1.03 uh", True, True],
    ["Noto Sans Inscriptional Pahlavi", "Version 1.02 uh", True, True],
    ["Noto Sans Inscriptional Parthian", "Version 1.03 uh", True, True],
    ["Noto Sans Javanese", "Version 1.05 uh", True, True],
    ["Noto Sans Kaithi", "Version 1.05 uh", True, True],
    ["Noto Sans Kayah Li", "Version 1.02 uh", True, True],
    ["Noto Sans Kharoshthi", "Version 1.03 uh", True, True],
    ["Noto Sans Lepcha", "Version 1.03 uh", True, True],
    ["Noto Sans Limbu", "Version 1.05 uh", True, True],
    ["Noto Sans Linear B", "Version 1.04 uh", True, True],
    ["Noto Sans Lisu", "Version 1.03 uh", True, True],
    ["Noto Sans Lycian", "Version 1.04 uh", True, True],
    ["Noto Sans Lydian", "Version 1.03 uh", True, True],
    ["Noto Sans Mandaic", "Version 1.02 uh", True, True],
    ["Noto Sans Meetei Mayek", "Version 1.04 uh", True, True],
    ["Noto Sans Mongolian", "Version 1.04 uh", True, True],
    ["Noto Sans N'Ko", "Version 1.02 uh", True, True],
    ["Noto Sans New Tai Lue", "Version 1.05 uh", True, True],
    ["Noto Sans Ogham", "Version 1.04 uh", True, True],
    ["Noto Sans Ol Chiki", "Version 1.03 uh", True, True],
    ["Noto Sans Old Italic", "Version 1.02 uh", True, True],
    ["Noto Sans Old Persian", "Version 1.04 uh", True, True],
    ["Noto Sans Old South Arabian", "Version 1.03 uh", True, True],
    ["Noto Sans Old Turkic", "Version 1.02 uh", True, True],
    ["Noto Sans Osmanya", "Version 1.03 uh", True, True],
    ["Noto Sans Phags Pa", "Version 1.03 uh", True, True],
    ["Noto Sans Phoenician", "Version 1.04 uh", True, True],
    ["Noto Sans Rejang", "Version 1.05 uh", True, True],
    ["Noto Sans Runic", "Version 1.02 uh", True, True],
    ["Noto Sans Samaritan", "Version 1.03 uh", True, True],
    ["Noto Sans Saurashtra", "Version 1.04 uh", True, True],
    ["Noto Sans Shavian", "Version 1.03 uh", True, True],
    ["Noto Sans Sundanese", "Version 1.05 uh", True, True],
    ["Noto Sans Syloti Nagri", "Version 1.04 uh", True, True],
    ["Noto Sans Syriac Eastern", "Version 1.03 uh", True, True],
    ["Noto Sans Tagalog", "Version 1.03 uh", True, True],
    ["Noto Sans Tagbanwa", "Version 1.04 uh", True, True],
    ["Noto Sans Tai Le", "Version 1.04 uh", True, True],
    ["Noto Sans Tai Tham", "Version 1.04 uh", True, True],
    ["Noto Sans Tai Viet", "Version 1.03 uh", True, True],
    ["Noto Sans Thaana", "Version 1.02 uh", True, True],
    ["Noto Sans Tifinagh", "Version 1.05 uh", True, True],
    ["Noto Sans Ugaritic", "Version 1.02 uh", True, True],
    ["Noto Sans Vai", "Version 1.02 uh", True, True],
    ["Noto Sans Yi", "Version 1.02 uh", True, True],
    ["Party LET Plain", "13.0d1e2", False, True],
    ["PhonepadTwo", "13.0d0e3", True, False],
    ["PortagoITC TT", "13.0d1e4", False, True],
    ["Princetown LET", "13.0d1e2", False, True],
    ["Raya Regular", "13.0d1e4", False, True],
    ["Santa Fe LET Plain:1.0", "13.0d1e3", False, True],
    ["STIXGeneral-Bold", "Version 1.1.0", True, False],
    ["STIXGeneral-BoldItalic", "Version 1.1.0", True, False],
    ["STIXGeneral-Italic", "Version 1.1.0", True, False],
    ["STIXGeneral-Regular", "Version 1.1.0", True, False],
    ["STIXIntegralsD-Bold", "Version 1.1.0", True, False],
    ["STIXIntegralsD-Regular", "Version 1.1.0", True, False],
    ["STIXIntegralsSm-Bold", "Version 1.1.0", True, False],
    ["STIXIntegralsSm-Regular", "Version 1.1.0", True, False],
    ["STIXIntegralsUp-Bold", "Version 1.1.0", True, False],
    ["STIXIntegralsUp-Regular", "Version 1.1.0", True, False],
    ["STIXIntegralsUpD-Bold", "Version 1.1.0", True, False],
    ["STIXIntegralsUpD-Regular", "Version 1.1.0", True, False],
    ["STIXIntegralsUpSm-Bold", "Version 1.1.0", True, False],
    ["STIXIntegralsUpSm-Regular", "Version 1.1.0", True, False],
    ["STIXNonUnicode-Bold", "Version 1.1.0", True, False],
    ["STIXNonUnicode-BoldItalic", "Version 1.1.0", True, False],
    ["STIXNonUnicode-Italic", "Version 1.1.0", True, False],
    ["STIXNonUnicode-Regular", "Version 1.1.0", True, False],
    ["STIXSizeFiveSym-Regular", "Version 1.1.0", True, False],
    ["STIXSizeFourSym-Bold", "Version 1.1.0", True, False],
    ["STIXSizeFourSym-Regular", "Version 1.1.0", True, False],
    ["STIXSizeOneSym-Bold", "Version 1.1.0", True, False],
    ["STIXSizeOneSym-Regular", "Version 1.1.0", True, False],
    ["STIXSizeThreeSym-Bold", "Version 1.1.0", True, False],
    ["STIXSizeThreeSym-Regular", "Version 1.1.0", True, False],
    ["STIXSizeTwoSym-Bold", "Version 1.1.0", True, False],
    ["STIXSizeTwoSym-Regular", "Version 1.1.0", True, False],
    ["STIXVariants-Bold", "Version 1.1.0", True, False],
    ["STIXVariants-Regular", "Version 1.1.0", True, False],
    ["Scheme-Bold", "13.0d3e1", True, True],
    ["Seravek", "13.0d3e2", True, True],
    ["Seravek Bold", "13.0d3e2", True, True],
    ["Seravek Bold Italic", "13.0d3e2", True, True],
    ["Seravek ExtraLight", "13.0d3e2", True, True],
    ["Seravek ExtraLight Italic", "13.0d3e2", True, True],
    ["Seravek Italic", "13.0d3e2", True, True],
    ["Seravek Light", "13.0d3e2", True, True],
    ["Seravek Light Italic", "13.0d3e2", True, True],
    ["Seravek Medium", "13.0d3e2", True, True],
    ["Seravek Medium Italic", "13.0d3e2", True, True],
    ["SignPainter-HouseScript Semibold", "13.0d1e5", True, False],
    ["Somer Regular", "13.0d1e4", False, True],
    ["Stone Sans ITC TT Bold", "13.0d2e1", False, True],
    ["Stone Sans Sem ITC TT Semi", "13.0d2e1", False, True],
    ["Stone Sans Sem ITC TT SemiIta", "13.0d2e1", False, True],
    ["Superclarendon Black", "13.0d1e4", True, True],
    ["Superclarendon Black Italic", "13.0d1e4", True, True],
    ["Superclarendon Bold", "13.0d1e4", True, True],
    ["Superclarendon Bold Italic", "13.0d1e4", True, True],
    ["Superclarendon Italic", "13.0d1e4", True, True],
    ["Superclarendon Light", "13.0d1e4", True, True],
    ["Superclarendon Light Italic", "13.0d1e4", True, True],
    ["Superclarendon Regular", "13.0d1e4", True, True],
    ["Synchro LET", "13.0d4e1", False, True],
    ["The Hand Serif Semibold", "13.1d1e1", True, False],
    ["Tw Cen MT", "13.0d1e2", False, True],
    ["Tw Cen MT Bold", "13.0d1e2", False, True],
    ["Tw Cen MT Bold Italic", "13.0d1e2", False, True],
    ["Tw Cen MT Italic", "13.0d1e2", False, True],
    ["Type Embellishments One LET Plain:1.0", "13.0d2e7", False, True],
    ["Yaziji Regular", "13.0d1e4", False, True],
    ["Zawra Bold", "13.0d1e5", False, True],
    ["Zawra Heavy", "13.0d1e5", False, True]
]