#"Preinstalled Fonts,, "iOS 13"", ""macOS Catalina""]

newIosList = [
    ["Academy Engraved LET Plain:1.0", "13.0d1e2",True, False],
    ["Al Bayan Bold", "13.0d1e6", False, True],
    ["Al Bayan Plain", "13.0d1e6", False, True],
    ["Al Nile", "13.0d2e2",True,True],
    ["Al Nile Bold", "13.0d2e2",True,True],
    ["Al Tarikh Regular", "13.0d2e1", False, True],
    ["American Typewriter", "13.0d1e4",True,True],
    ["American Typewriter Bold", "13.0d1e4",True,True],
    ["American Typewriter Condensed", "13.0d1e4",True,True],
    ["American Typewriter Condensed Bold", "13.0d1e4",True,True],
    ["American Typewriter Condensed Light", "13.0d1e4",True,True],
    ["American Typewriter Light", "13.0d1e4",True,True],
    ["American Typewriter Semibold", "13.0d1e4",True,True],
    ["Andale Mono", "Version 2.00x", False, True],
    ["Apple Braille", "13.0d2e27", False, True],
    ["Apple Braille Outline 6 Dot", "13.0d2e27", False, True],
    ["Apple Braille Outline 8 Dot", "13.0d2e27", False, True],
    ["Apple Braille Pinpoint 6 Dot", "13.0d2e27", False, True],
    ["Apple Braille Pinpoint 8 Dot", "13.0d2e27", False, True],
    ["Apple Chancery", "13.0d1e4", False, True],
    ["Apple Color Emoji", "15.0d4e3",True,True],
    ["Apple SD Gothic Neo Bold", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo Heavy", "13.0d1e9", False, True],
    ["Apple SD Gothic Neo Light", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo Medium", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo Regular", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo SemiBold", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo Thin", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo UltraLight", "13.0d1e9",True,True],
    ["Apple SD Gothic Neo ExtraBold", "13.0d1e9", False, True],
    ["Apple Symbols", "15.0d1e2",True,True],
    ["AppleGothic Regular", "13.0d1e3", False, True],
    ["AppleMyungjo Regular", "13.0d1e6", False, True],
    ["Arial", "Version 5.01.2x",True,True],
    ["Arial Black", "Version 5.00.1x", False, True],
    ["Arial Bold", "Version 5.01.2x",True,True],
    ["Arial Bold Italic", "Version 5.00.2x",True,True],
    ["Arial Hebrew", "13.0d1e1",True,True],
    ["Arial Hebrew Bold", "13.0d1e1",True,True],
    ["Arial Hebrew Light", "13.0d1e1",True,True],
    ["Arial Hebrew Scholar", "13.0d1e1", False, True],
    ["Arial Hebrew Scholar Bold", "13.0d1e1", False, True],
    ["Arial Hebrew Scholar Light", "13.0d1e1", False, True],
    ["Arial Italic", "Version 5.00.2x",True,True],
    ["Arial Narrow", "Version 2.38.1x", False, True],
    ["Arial Narrow Bold", "Version 2.38.1x", False, True],
    ["Arial Narrow Bold Italic", "Version 2.38.1x", False, True],
    ["Arial Narrow Italic", "Version 2.38.1x", False, True],
    ["Arial Rounded MT Bold", "Version 1.51x",True,True],
    ["Arial Unicode MS", "Version 1.01x", False, True],
    ["Avenir Black", "13.0d3e1",True,True],
    ["Avenir Black Oblique", "13.0d3e1",True,True],
    ["Avenir Book", "13.0d3e1",True,True],
    ["Avenir Book Oblique", "13.0d3e1",True,True],
    ["Avenir Heavy", "13.0d3e1",True,True],
    ["Avenir Heavy Oblique", "13.0d3e1",True,True],
    ["Avenir Light", "13.0d3e1",True,True],
    ["Avenir Light Oblique", "13.0d3e1",True,True],
    ["Avenir Medium", "13.0d3e1",True,True],
    ["Avenir Medium Oblique", "13.0d3e1",True,True],
    ["Avenir Next Bold", "13.0d1e10",True,True],
    ["Avenir Next Bold Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Bold", "13.0d1e10",True,True],
    ["Avenir Next Condensed Bold Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Demi Bold", "13.0d1e10",True,True],
    ["Avenir Next Condensed Demi Bold Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Heavy", "13.0d1e10",True,True],
    ["Avenir Next Condensed Heavy Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Medium", "13.0d1e10",True,True],
    ["Avenir Next Condensed Medium Italic", "13.0d1e10",True,True],
    ["Avenir Next Condensed Regular", "13.0d1e10",True,True],
    ["Avenir Next Condensed Ultra Light", "13.0d1e10",True,True],
    ["Avenir Next Condensed Ultra Light Italic", "13.0d1e10",True,True],
    ["Avenir Next Demi Bold", "13.0d1e10",True,True],
    ["Avenir Next Demi Bold Italic", "13.0d1e10",True,True],
    ["Avenir Next Heavy", "13.0d1e10",True,True],
    ["Avenir Next Heavy Italic", "13.0d1e10",True,True],
    ["Avenir Next Italic", "13.0d1e10",True,True],
    ["Avenir Next Medium", "13.0d1e10",True,True],
    ["Avenir Next Medium Italic", "13.0d1e10",True,True],
    ["Avenir Next Regular", "13.0d1e10",True,True],
    ["Avenir Next Ultra Light", "13.0d1e10",True,True],
    ["Avenir Next Ultra Light Italic", "13.0d1e10",True,True],
    ["Avenir Oblique", "13.0d3e1",True,True],
    ["Avenir Roman", "13.0d3e1",True,True],
    ["Ayuthaya", "13.0d1e7", False, True],
    ["Baghdad Regular", "13.0d1e5", False, True],
    ["Bangla MN", "14.0d1e2", False, True],
    ["Bangla MN Bold", "14.0d1e2", False, True],
    ["Bangla Sangam MN", "14.0d1e1", False, True],
    ["Bangla Sangam MN Bold", "14.0d1e1", False, True],
    ["Baskerville", "13.0d1e10",True,True],
    ["Baskerville Bold", "13.0d1e10",True,True],
    ["Baskerville Bold Italic", "13.0d1e10",True,True],
    ["Baskerville Italic", "13.0d1e10",True,True],
    ["Baskerville SemiBold", "13.0d1e10",True,True],
    ["Baskerville SemiBold Italic", "13.0d1e10",True,True],
    ["Beirut Regular", "13.0d1e6", False, True],
    ["Big Caslon Medium", "13.0d1e11", False, True],
    ["Bodoni 72 Bold", "13.0d2e1",True,True],
    ["Bodoni 72 Book", "13.0d2e1",True,True],
    ["Bodoni 72 Book Italic", "13.0d2e1",True,True],
    ["Bodoni 72 Oldstyle Bold", "13.0d2e1",True,True],
    ["Bodoni 72 Oldstyle Book", "13.0d2e1",True,True],
    ["Bodoni 72 Oldstyle Book Italic", "13.0d2e1",True,True],
    ["Bodoni 72 Smallcaps Book", "13.0d2e1",True,True],
    ["Bodoni Ornaments", "13.0d2e1",True,True],
    ["Bradley Hand Bold", "14.0d0e1",True,True],
    ["Brush Script MT Italic", "Version 1.52x 1", False, True],
    ["Chalkboard", "13.0d1e2", False, True],
    ["Chalkboard Bold", "13.0d1e2", False, True],
    ["Chalkboard SE Bold", "13.0d1e2",True,True],
    ["Chalkboard SE Light", "13.0d1e2",True,True],
    ["Chalkboard SE Regular", "13.0d1e2",True,True],
    ["Chalkduster", "13.0d2e1",True,True],
    ["Charter Black", "14.0d2e1",True,True],
    ["Charter Black Italic", "14.0d2e1",True,True],
    ["Charter Bold", "14.0d2e1",True,True],
    ["Charter Bold Italic", "14.0d2e1",True,True],
    ["Charter Italic", "14.0d2e1",True,True],
    ["Charter Roman", "14.0d2e1",True,True],
    ["Cochin", "13.0d2e1",True,True],
    ["Cochin Bold", "13.0d2e1",True,True],
    ["Cochin Bold Italic", "13.0d2e1",True,True],
    ["Cochin Italic", "13.0d2e1",True,True],
    ["Copperplate", "13.0d1e2",True,True],
    ["Copperplate Bold", "13.0d1e2",True,True],
    ["Copperplate Light", "13.0d1e2",True,True],
    ["Corsiva Hebrew", "13.0d1e4", False, True],
    ["Corsiva Hebrew Bold", "13.0d1e4", False, True],
    ["Courier", "13.0d1e1",True,True],
    ["Courier Bold", "13.0d1e1",True,True],
    ["Courier Bold Oblique", "13.0d1e1",True,True],
    ["Courier New", "Version 5.00.2x",True,True],
    ["Courier New Bold", "Version 5.00.2x",True,True],
    ["Courier New Bold Italic", "Version 5.00x",True,True],
    ["Courier New Italic", "Version 5.00.1x",True,True],
    ["Courier Oblique", "13.0d1e1",True,True],
    ["DIN Alternate Bold", "13.0d3e1",True,True],
    ["DIN Condensed Bold", "14.0d1e1",True,True],
    ["Damascus Bold", "13.0d3e9",True,True],
    ["Damascus Light", "13.0d3e9",True,True],
    ["Damascus Medium", "13.0d3e9",True,True],
    ["Damascus Regular", "13.0d3e9",True,True],
    ["Damascus Semi Bold", "13.0d3e9",True,True],
    ["DecoType Naskh Regular", "14.0d0e1", False, True],
    ["Devanagari MT", "13.0d1e3", False, True],
    ["Devanagari MT Bold", "13.0d1e3", False, True],
    ["Devanagari Sangam MN", "14.0d1e12",True,True],
    ["Devanagari Sangam MN Bold", "14.0d1e12",True,True],
    ["Didot", "13.0d1e3",True,True],
    ["Didot Bold", "13.0d1e3",True,True],
    ["Didot Italic", "13.0d1e3",True,True],
    ["Diwan Kufi Regular", "13.0d2e1", False, True],
    ["Diwan Thuluth Regular", "13.0d1e5", False, True],
    ["Euphemia UCAS", "13.0d1e2",True,True],
    ["Euphemia UCAS Bold", "13.0d1e2",True,True],
    ["Euphemia UCAS Italic", "13.0d1e2",True,True],
    ["Farah Regular", "13.0d2e3",True,True],
    ["Farisi Regular", "13.0d1e3", False, True],
    ["Futura Bold", "13.0d1e3",True,True],
    ["Futura Condensed ExtraBold", "13.0d1e3",True,True],
    ["Futura Condensed Medium", "13.0d1e3",True,True],
    ["Futura Medium", "13.0d1e3",True,True],
    ["Futura Medium Italic", "13.0d1e3",True,True],
    ["GB18030 Bitmap", "13.0d1e1", False, True],
    ["Galvji", "14.0d1e3",True,True],
    ["Galvji Bold", "14.0d1e3",True,True],
    ["Galvji Bold Oblique", "14.0d1e3", False, True],
    ["Galvji Oblique", "14.0d1e3", False, True],
    ["Geeza Pro Bold", "14.0d1e4",True,True],
    ["Geeza Pro Regular", "14.0d1e4",True,True],
    ["Geneva", "13.0d2e1", False, True],
    ["Georgia", "Version 5.00x 4",True,True],
    ["Georgia Bold", "Version 5.00x 4",True,True],
    ["Georgia Bold Italic", "Version 5.00x 4",True,True],
    ["Georgia Italic", "Version 5.00x 4",True,True],
    ["Gill Sans", "13.0d1e4",True,True],
    ["Gill Sans Bold", "13.0d1e4",True,True],
    ["Gill Sans Bold Italic", "13.0d1e4",True,True],
    ["Gill Sans Italic", "13.0d1e4",True,True],
    ["Gill Sans Light", "13.0d1e4",True,True],
    ["Gill Sans Light Italic", "13.0d1e4",True,True],
    ["Gill Sans SemiBold", "13.0d1e4",True,True],
    ["Gill Sans SemiBold Italic", "13.0d1e4",True,True],
    ["Gill Sans UltraBold", "13.0d1e4",True,True],
    ["Gujarati MT", "13.0d1e2", False, True],
    ["Gujarati MT Bold", "13.0d1e2", False, True],
    ["Gujarati Sangam MN", "14.0d2e1", False, True],
    ["Gujarati Sangam MN Bold", "14.0d2e1", False, True],
    ["Gurmukhi MN", "14.0d1e2", False, True],
    ["Gurmukhi MN Bold", "14.0d1e2", False, True],
    ["Gurmukhi MT", "13.0d1e4", False, True],
    ["Gurmukhi Sangam MN", "14.0d3e1", False, True],
    ["Gurmukhi Sangam MN Bold", "14.0d3e1", False, True],
    ["Heiti SC Light", "13.0d1e1", False, True],
    ["Heiti SC Medium", "13.0d1e1", False, True],
    ["Heiti TC Light", "13.0d1e1", False, True],
    ["Heiti TC Medium", "13.0d1e1", False, True],
    ["Helvetica", "15.0d1e3",True,True],
    ["Helvetica Bold", "15.0d1e3",True,True],
    ["Helvetica Bold Oblique", "15.0d1e3",True,True],
    ["Helvetica Light", "15.0d1e3",True,True],
    ["Helvetica Light Oblique", "15.0d1e3",True,True],
    ["Helvetica Neue", "15.0d1e1",True,True],
    ["Helvetica Neue Bold", "15.0d1e1",True,True],
    ["Helvetica Neue Bold Italic", "15.0d1e1",True,True],
    ["Helvetica Neue Condensed Black", "15.0d1e1",True,True],
    ["Helvetica Neue Condensed Bold", "15.0d1e1",True,True],
    ["Helvetica Neue Italic", "15.0d1e1",True,True],
    ["Helvetica Neue Light", "15.0d1e1",True,True],
    ["Helvetica Neue Light Italic", "15.0d1e1",True,True],
    ["Helvetica Neue Medium", "15.0d1e1",True,True],
    ["Helvetica Neue Medium Italic", "15.0d1e1",True,True],
    ["Helvetica Neue Thin", "15.0d1e1",True,True],
    ["Helvetica Neue Thin Italic", "15.0d1e1",True,True],
    ["Helvetica Neue UltraLight", "15.0d1e1",True,True],
    ["Helvetica Neue UltraLight Italic", "15.0d1e1",True,True],
    ["Helvetica Oblique", "15.0d1e3",True,True],
    ["Herculanum", "13.0d1e2", False, True],
    ["Hiragino Maru Gothic ProN W4", "15.0d1e2",True,True],
    ["Hiragino Mincho ProN W3", "15.0d1e2",True,True],
    ["Hiragino Mincho ProN W6", "15.0d1e2",True,True],
    ["Hiragino Sans GB W3", "13.0d2e3", False, True],
    ["Hiragino Sans GB W6", "13.0d2e3", False, True],
    ["Hiragino Sans W0", "13.0d2e7", False, True],
    ["Hiragino Sans W1", "13.0d2e7", False, True],
    ["Hiragino Sans W2", "13.0d2e7", False, True],
    ["Hiragino Sans W3", "15.0d1e5",True,True],
    ["Hiragino Sans W4", "13.0d2e7", False, True],
    ["Hiragino Sans W5", "13.0d2e7", False, True],
    ["Hiragino Sans W6", "15.0d1e5",True,True],
    ["Hiragino Sans W7", "15.0d1e5", False, True],
    ["Hiragino Sans W8", "13.0d2e7", False, True],
    ["Hiragino Sans W9", "13.0d2e7", False, True],
    ["Hoefler Text", "14.0d1e2",True,True],
    ["Hoefler Text Black", "14.0d1e2",True,True],
    ["Hoefler Text Black Italic", "14.0d1e2",True,True],
    ["Hoefler Text Italic", "14.0d1e2",True,True],
    ["Hoefler Text Ornaments", "13.0d2e20", False, True],
    ["ITF Devanagari Bold", "14.0d3e6", False, True],
    ["ITF Devanagari Book", "14.0d3e6", False, True],
    ["ITF Devanagari Demi", "14.0d3e6", False, True],
    ["ITF Devanagari Light", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Bold", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Book", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Demi", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Light", "14.0d3e6", False, True],
    ["ITF Devanagari Marathi Medium", "14.0d3e6", False, True],
    ["ITF Devanagari Medium", "14.0d3e6", False, True],
    ["Impact", "Version 5.00x", False, True],
    ["InaiMathi", "13.0d1e5", False, True],
    ["InaiMathi Bold", "13.0d1e5", False, True],
    ["Kailasa Bold", "13.0d1e3",True,True],
    ["Kailasa Regular", "13.0d1e3",True,True],
    ["Kannada MN", "14.0d1e6", False, True],
    ["Kannada MN Bold", "14.0d1e6", False, True],
    ["Kannada Sangam MN", "14.0d2e4",True,True],
    ["Kannada Sangam MN Bold", "14.0d2e4",True,True],
    ["Kefa Bold", "13.0d1e3", False, True],
    ["Kefa Regular", "13.0d1e3",True,True],
    ["Khmer MN", "14.0d1e1", False, True],
    ["Khmer MN Bold", "14.0d1e1", False, True],
    ["Khmer Sangam MN", "14.0d1e9",True,True],
    ["Kohinoor Bangla", "14.0d2e3",True,True],
    ["Kohinoor Bangla Bold", "14.0d2e3", False, True],
    ["Kohinoor Bangla Light", "14.0d2e3",True,True],
    ["Kohinoor Bangla Medium", "14.0d2e3", False, True],
    ["Kohinoor Bangla Semibold", "14.0d2e3",True,True],
    ["Kohinoor Devanagari Bold", "14.0d4e1", False, True],
    ["Kohinoor Devanagari Light", "14.0d4e1",True,True],
    ["Kohinoor Devanagari Medium", "14.0d4e1", False, True],
    ["Kohinoor Devanagari Regular", "14.0d4e1",True,True],
    ["Kohinoor Devanagari Semibold", "14.0d4e1",True,True],
    ["Kohinoor Gujarati Bold", "14.0d2e16",True,True],
    ["Kohinoor Gujarati Light", "14.0d2e16",True,True],
    ["Kohinoor Gujarati Regular", "14.0d2e16",True,True],
    ["Kohinoor Telugu", "14.0d1e3",True,True],
    ["Kohinoor Telugu Bold", "14.0d1e3", False, True],
    ["Kohinoor Telugu Light", "14.0d1e3",True,True],
    ["Kohinoor Telugu Medium", "14.0d1e3",True,True],
    ["Kohinoor Telugu Semibold", "14.0d1e3", False, True],
    ["Kokonor Regular", "13.0d1e3", False, True],
    ["Krungthep", "14.0d1e1", False, True],
    ["KufiStandardGK Regular", "13.0d1e11", False, True],
    ["Lao MN", "14.0d1e9", False, True],
    ["Lao MN Bold", "14.0d1e9", False, True],
    ["Lao Sangam MN", "14.0d1e6",True,True],
    ["Lucida Grande", "15.0d1e1", False, True],
    ["Lucida Grande Bold", "15.0d1e1", False, True],
    ["Luminari", "13.0d1e2", False, True],
    ["Malayalam MN", "14.0d1e6", False, True],
    ["Malayalam MN Bold", "14.0d1e6", False, True],
    ["Malayalam Sangam MN", "14.0d1e1",True,True],
    ["Malayalam Sangam MN Bold", "14.0d1e1",True,True],
    ["Marker Felt Thin", "13.0d1e1",True,True],
    ["Marker Felt Wide", "13.0d1e1",True,True],
    ["Menlo Bold", "14.0d1e1",True,True],
    ["Menlo Bold Italic", "14.0d1e1",True,True],
    ["Menlo Italic", "14.0d1e1",True,True],
    ["Menlo Regular", "14.0d1e1",True,True],
    ["Microsoft Sans Serif", "Version 5.00.1x", False, True],
    ["Mishafi Gold Regular", "13.0d2e1", False, True],
    ["Mishafi Regular", "13.0d2e1",True,True],
    ["Monaco", "15.0d1e2", False, True],
    ["Mshtakan", "14.0d1e1", False, True],
    ["Mshtakan Bold", "14.0d1e1", False, True],
    ["Mshtakan BoldOblique", "14.0d1e1", False, True],
    ["Mshtakan Oblique", "14.0d1e1", False, True],
    ["MuktaMahee Bold", "14.0d1e18", False, True],
    ["MuktaMahee Light", "14.0d1e18", False, True],
    ["MuktaMahee Medium", "14.0d1e18", False, True],
    ["MuktaMahee Regular", "14.0d1e18", False, True],
    ["MuktaMahee SemiBold", "14.0d1e18", False, True],
    ["Muna Black", "13.0d1e4", False, True],
    ["Muna Bold", "13.0d1e4", False, True],
    ["Muna Regular", "13.0d1e4", False, True],
    ["Myanmar MN", "14.0d1e2", False, True],
    ["Myanmar MN Bold", "14.0d1e2", False, True],
    ["Myanmar Sangam MN", "14.0d1e8",True,True],
    ["Myanmar Sangam MN Bold", "14.0d1e8",True,True],
    ["Nadeem Regular", "13.0d1e3", False, True],
    ["New Peninim MT", "13.0d1e4", False, True],
    ["New Peninim MT Bold", "13.0d1e4", False, True],
    ["New Peninim MT Bold Inclined", "13.0d1e4", False, True],
    ["New Peninim MT Inclined", "13.0d1e4", False, True],
    ["Noteworthy Bold", "13.0d1e11",True,True],
    ["Noteworthy Light", "13.0d1e11",True,True],
    ["Noto Nastaliq Urdu", "14.0d2e19",True,True],
    ["Noto Nastaliq Urdu Bold", "14.0d2e19",True,True],
    ["Noto Sans Javanese Regular", "Version 2.000", False, True],
    ["Noto Sans Kannada Black", "14.0d1e7", False, True],
    ["Noto Sans Kannada Bold", "14.0d1e7",True,True],
    ["Noto Sans Kannada ExtraBold", "14.0d1e7", False, True],
    ["Noto Sans Kannada ExtraLight", "14.0d1e7", False, True],
    ["Noto Sans Kannada Light", "14.0d1e7",True,True],
    ["Noto Sans Kannada Medium", "14.0d1e7", False, True],
    ["Noto Sans Kannada Regular", "14.0d1e7",True,True],
    ["Noto Sans Kannada SemiBold", "14.0d1e7", False, True],
    ["Noto Sans Kannada Thin", "14.0d1e7", False, True],
    ["Noto Sans Myanmar Black", "14.0d4e1", False, True],
    ["Noto Sans Myanmar Bold", "14.0d4e1",True,True],
    ["Noto Sans Myanmar ExtraBold", "14.0d4e1", False, True],
    ["Noto Sans Myanmar ExtraLight", "14.0d4e1", False, True],
    ["Noto Sans Myanmar Light", "14.0d4e1",True,True],
    ["Noto Sans Myanmar Medium", "14.0d4e1", False, True],
    ["Noto Sans Myanmar Regular", "14.0d4e1",True,True],
    ["Noto Sans Myanmar SemiBold", "14.0d4e1", False, True],
    ["Noto Sans Myanmar Thin", "14.0d4e1", False, True],
    ["Noto Sans Oriya", "14.0d1e2",True,True],
    ["Noto Sans Oriya Bold", "14.0d1e2",True,True],
    ["Optima Bold", "13.0d1e2",True,True],
    ["Optima Bold Italic", "13.0d1e2",True,True],
    ["Optima ExtraBlack", "13.0d1e2",True,True],
    ["Optima Italic", "13.0d1e2",True,True],
    ["Optima Regular", "13.0d1e2",True,True],
    ["Oriya MN", "14.0d1e6", False, True],
    ["Oriya MN Bold", "14.0d1e6", False, True],
    ["Oriya Sangam MN", "14.0d1e2", False, True],
    ["Oriya Sangam MN Bold", "14.0d1e2", False, True],
    ["PT Mono", "13.0d2e4", False, True],
    ["PT Mono Bold", "13.0d2e4", False, True],
    ["PT Sans", "13.0d3e2", False, True],
    ["PT Sans Bold", "13.0d3e2", False, True],
    ["PT Sans Bold Italic", "13.0d3e2", False, True],
    ["PT Sans Caption", "13.0d3e2", False, True],
    ["PT Sans Caption Bold", "13.0d3e2", False, True],
    ["PT Sans Italic", "13.0d3e2", False, True],
    ["PT Sans Narrow", "13.0d3e2", False, True],
    ["PT Sans Narrow Bold", "13.0d3e2", False, True],
    ["PT Serif", "13.0d2e1", False, True],
    ["PT Serif Bold", "13.0d2e1", False, True],
    ["PT Serif Bold Italic", "13.0d2e1", False, True],
    ["PT Serif Caption", "13.0d2e1", False, True],
    ["PT Serif Caption Italic", "13.0d2e1", False, True],
    ["PT Serif Italic", "13.0d2e1", False, True],
    ["Palatino", "15.0d2e2",True,True],
    ["Palatino Bold", "15.0d2e2",True,True],
    ["Palatino Bold Italic", "15.0d2e2",True,True],
    ["Palatino Italic", "15.0d2e2",True,True],
    ["Papyrus", "13.0d1e2",True,True],
    ["Papyrus Condensed", "13.0d1e2",True,True],
    ["Party LET Plain", "13.0d1e2",True, False],
    ["Phosphate Inline", "13.0d1e2", False, True],
    ["Phosphate Solid", "13.0d1e2", False, True],
    ["PingFang HK Light", "15.0d2e5",True,True],
    ["PingFang HK Medium", "15.0d2e5",True,True],
    ["PingFang HK Regular", "15.0d2e5",True,True],
    ["PingFang HK Semibold", "15.0d2e5",True,True],
    ["PingFang HK Thin", "15.0d2e5",True,True],
    ["PingFang HK Ultralight", "15.0d2e5",True,True],
    ["PingFang SC Light", "15.0d2e5",True,True],
    ["PingFang SC Medium", "15.0d2e5",True,True],
    ["PingFang SC Regular", "15.0d2e5",True,True],
    ["PingFang SC Semibold", "15.0d2e5",True,True],
    ["PingFang SC Thin", "15.0d2e5",True,True],
    ["PingFang SC Ultralight", "15.0d2e5",True,True],
    ["PingFang TC Light", "15.0d2e5",True,True],
    ["PingFang TC Medium", "15.0d2e5",True,True],
    ["PingFang TC Regular", "15.0d2e5",True,True],
    ["PingFang TC Semibold", "15.0d2e5",True,True],
    ["PingFang TC Thin", "15.0d2e5",True,True],
    ["PingFang TC Ultralight", "15.0d2e5",True,True],
    ["Plantagenet Cherokee", "13.0d1e3", False, True],
    ["Raanana", "13.0d1e3", False, True],
    ["Raanana Bold", "13.0d1e3", False, True],
    ["Rockwell", "13.0d2e1",True,True],
    ["Rockwell Bold", "13.0d2e1",True,True],
    ["Rockwell Bold Italic", "13.0d2e1",True,True],
    ["Rockwell Italic", "13.0d2e1",True,True],
    ["STIXGeneral Bold", "Version 1.1.0", False, True],
    ["STIXGeneral BoldItalic", "Version 1.1.0", False, True],
    ["STIXGeneral Italic", "Version 1.1.0", False, True],
    ["STIXGeneral Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsD Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsD Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsSm Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsSm Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUp Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUp Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUpD Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUpD Regular", "Version 1.1.0", False, True],
    ["STIXIntegralsUpSm Bold", "Version 1.1.0", False, True],
    ["STIXIntegralsUpSm Regular", "Version 1.1.0", False, True],
    ["STIXNonUnicode Bold", "Version 1.1.0", False, True],
    ["STIXNonUnicode BoldItalic", "Version 1.1.0", False, True],
    ["STIXNonUnicode Italic", "Version 1.1.0", False, True],
    ["STIXNonUnicode Regular", "Version 1.1.0", False, True],
    ["STIXSizeFiveSym Regular", "Version 1.1.0", False, True],
    ["STIXSizeFourSym Bold", "Version 1.1.0", False, True],
    ["STIXSizeFourSym Regular", "Version 1.1.0", False, True],
    ["STIXSizeOneSym Bold", "Version 1.1.0", False, True],
    ["STIXSizeOneSym Regular", "Version 1.1.0", False, True],
    ["STIXSizeThreeSym Bold", "Version 1.1.0", False, True],
    ["STIXSizeThreeSym Regular", "Version 1.1.0", False, True],
    ["STIXSizeTwoSym Bold", "Version 1.1.0", False, True],
    ["STIXSizeTwoSym Regular", "Version 1.1.0", False, True],
    ["STIXVariants Bold", "Version 1.1.0", False, True],
    ["STIXVariants Regular", "Version 1.1.0", False, True],
    ["STSong", "13.0d3e2", False, True],
    ["Sana Regular", "13.0d1e4", False, True],
    ["Sathu", "14.0d1e1", False, True],
    ["Savoye LET Plain:1.0", "13.0d2e4",True,True],
    ["Shree Devanagari 714", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Bold", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Bold Italic", "13.0d2e1", False, True],
    ["Shree Devanagari 714 Italic", "13.0d2e1", False, True],
    ["SignPainter-HouseScript", "14.0d1e1", False, True],
    ["SignPainter-HouseScript Semibold", "14.0d1e1", False, True],
    ["Silom", "14.0d1e1", False, True],
    ["Sinhala MN", "14.0d1e1", False, True],
    ["Sinhala MN Bold", "14.0d1e1", False, True],
    ["Sinhala Sangam MN", "14.0d1e2",True,True],
    ["Sinhala Sangam MN Bold", "14.0d1e2",True,True],
    ["Skia Black", "13.0d1e54", False, True],
    ["Skia Black Condensed", "13.0d1e54", False, True],
    ["Skia Black Extended", "13.0d1e54", False, True],
    ["Skia Bold", "13.0d1e54", False, True],
    ["Skia Condensed", "13.0d1e54", False, True],
    ["Skia Extended", "13.0d1e54", False, True],
    ["Skia Light", "13.0d1e54", False, True],
    ["Skia Light Condensed", "13.0d1e54", False, True],
    ["Skia Light Extended", "13.0d1e54", False, True],
    ["Skia Regular", "13.0d1e54", False, True],
    ["Snell Roundhand", "15.0d1e1",True,True],
    ["Snell Roundhand Black", "15.0d1e1",True,True],
    ["Snell Roundhand Bold", "15.0d1e1",True,True],
    ["Songti SC Black", "14.0d0e1", False, True],
    ["Songti SC Bold", "14.0d0e1", False, True],
    ["Songti SC Light", "14.0d0e1", False, True],
    ["Songti SC Regular", "14.0d0e1", False, True],
    ["Songti TC Bold", "14.0d0e1", False, True],
    ["Songti TC Light", "14.0d0e1", False, True],
    ["Songti TC Regular", "14.0d0e1", False, True],
    ["Sukhumvit Set Bold", "13.0d1e6", False, True],
    ["Sukhumvit Set Light", "13.0d1e", False, True],
    ["Sukhumvit Set Medium", "13.0d1e6", False, True],
    ["Sukhumvit Set Semi Bold", "13.0d1e6", False, True],
    ["Sukhumvit Set Text", "13.0d1e6", False, True],
    ["Sukhumvit Set Thin", "13.0d1e6", False, True],
    ["Symbol", "13.0d2e2",True,True],
    ["Tahoma", "Version 5.01.2x", False, True],
    ["Tahoma Bold", "Version 5.01.1x", False, True],
    ["Tamil MN", "14.0d1e7", False, True],
    ["Tamil MN Bold", "14.0d1e7", False, True],
    ["Tamil Sangam MN", "14.0d1e15",True,True],
    ["Tamil Sangam MN Bold", "14.0d1e15",True,True],
    ["Telugu MN", "14.0d1e2", False, True],
    ["Telugu MN Bold", "14.0d1e2", False, True],
    ["Telugu Sangam MN", "14.0d1e4", False, True],
    ["Telugu Sangam MN Bold", "14.0d1e4", False, True],
    ["Thonburi", "13.0d1e1",True,True],
    ["Thonburi Bold", "13.0d1e1",True,True],
    ["Thonburi Light", "13.0d1e1",True,True],
    ["Times Bold", "15.0d2e1", False, True],
    ["Times Bold Italic", "15.0d2e1", False, True],
    ["Times Italic", "15.0d2e1", False, True],
    ["Times New Roman", "Version 5.01.3x",True,True],
    ["Times New Roman Bold", "Version 5.01.3x",True,True],
    ["Times New Roman Bold Italic", "Version 5.00.3x",True,True],
    ["Times New Roman Italic", "Version 5.00.3x",True,True],
    ["Times Roman", "15.0d2e1", False, True],
    ["Trattatello", "13.0d2e2", False, True],
    ["Trebuchet MS", "Version 5.00x",True,True],
    ["Trebuchet MS Bold", "Version 5.00x",True,True],
    ["Trebuchet MS Bold Italic", "Version 5.00x",True,True],
    ["Trebuchet MS Italic", "Version 5.00x",True,True],
    ["Verdana", "Version 5.01x",True,True],
    ["Verdana Bold", "Version 5.01x",True,True],
    ["Verdana Bold Italic", "Version 5.01x",True,True],
    ["Verdana Italic", "Version 5.01x",True,True],
    ["Waseem Light", "13.0d1e2", False, True],
    ["Waseem Regular", "13.0d1e2", False, True],
    ["Webdings", "Version 5.00x", False, True],
    ["Wingdings", "Version 5.00x", False, True],
    ["Wingdings 2", "Version 1.55x", False, True],
    ["Wingdings 3", "Version 1.55x", False, True],
    ["Zapf Dingbats", "13.0d1e2",True,True],
    ["Zapfino", "13.0d1e2",True,True]
    ]