regex = r"\s(ExtraLight|ExtraBlack|Bold|Italic|Light|Demi|Inclined|Oblique|SemiBold|Thin|UltraLight|ExtraBold|Medium|Regular|Heavy)"

List = ["Al Bayan_Bold",
"Al Bayan Plain",
"Al Nile",
"Al Nile_Bold",
"Al Tarikh_Regular",
"American Typewriter",
"American Typewriter_Bold",
"American Typewriter Condensed",
"American Typewriter Condensed_Bold",
"American Typewriter Condensed_Light",
"American Typewriter_Light",
"American Typewriter_Semibold",
"Andale Mono",
"Apple Braille",
"Apple Braille Outline 6 Dot",
"Apple Braille Outline 8 Dot",
"Apple Braille Pinpoint 6 Dot",
"Apple Braille Pinpoint 8 Dot",
"Apple Chancery",
"Apple SD Gothic Neo_Bold",
"Apple SD Gothic Neo_Heavy",
"Apple SD Gothic Neo_Light",
"Apple SD Gothic Neo_Medium",
"Apple SD Gothic Neo_Regular",
"Apple SD Gothic Neo_SemiBold",
"Apple SD Gothic Neo_Thin",
"Apple SD Gothic Neo_UltraLight",
"Apple SD GothicNeo_ExtraBold",
"Apple Symbols",
"AppleGothic_Regular",
"AppleMyungjo_Regular",
"Arial",
"Arial Black",
"Arial_Bold",
"Arial_Bold_Italic",
"Arial Hebrew",
"Arial Hebrew_Bold",
"Arial Hebrew_Light",
"Arial Hebrew Scholar",
"Arial Hebrew Scholar_Bold",
"Arial Hebrew Scholar_Light",
"Arial_Italic",
"Arial Narrow",
"Arial Narrow_Bold",
"Arial Narrow_Bold_Italic",
"Arial Narrow_Italic",
"Arial Rounded MT Bold",
"Arial Unicode MS",
"Avenir_Black",
"Avenir_Black_Oblique",
"Avenir_Book",
"Avenir_Book_Oblique",
"Avenir_Heavy",
"Avenir_Heavy_Oblique",
"Avenir_Light",
"Avenir_Light_Oblique",
"Avenir_Medium",
"Avenir_Medium_Oblique",
"Avenir Next_Bold",
"Avenir Next_Bold_Italic",
"Avenir Next Condensed_Bold",
"Avenir Next Condensed_Bold_Italic",
"Avenir Next Condensed_Demi_Bold",
"Avenir Next Condensed_Demi_Bold_Italic",
"Avenir Next Condensed_Heavy",
"Avenir Next Condensed_Heavy_Italic",
"Avenir Next Condensed_Italic",
"Avenir Next Condensed_Medium",
"Avenir Next Condensed_Medium_Italic",
"Avenir Next Condensed_Regular",
"Avenir Next Condensed Ultra_Light",
"Avenir Next Condensed Ultra_Light_Italic",
"Avenir Next_Demi_Bold",
"Avenir Next_Demi_Bold_Italic",
"Avenir Next_Heavy",
"Avenir Next_Heavy_Italic",
"Avenir Next_Italic",
"Avenir Next_Medium",
"Avenir Next_Medium_Italic",
"Avenir Next_Regular",
"Avenir Next Ultra_Light",
"Avenir Next Ultra_Light_Italic",
"Avenir_Oblique",
"Avenir Roman",
"Ayuthaya",
"Baghdad_Regular",
"Bangla MN",
"Bangla MN_Bold",
"Bangla Sangam MN",
"Bangla Sangam MN_Bold",
"Baskerville",
"Baskerville_Bold",
"Baskerville_Bold_Italic",
"Baskerville_Italic",
"Baskerville_SemiBold",
"Baskerville_SemiBold_Italic",
"Beirut_Regular",
"Big Caslon_Medium",
"Bodoni 72_Bold",
"Bodoni 72_Book",
"Bodoni 72_Book_Italic",
"Bodoni 72 Oldstyle_Bold",
"Bodoni 72 Oldstyle_Book",
"Bodoni 72 Oldstyle_Book_Italic",
"Bodoni 72 Smallcaps_Book",
"Bodoni Ornaments",
"Bradley Hand_Bold",
"Brush Script MT_Italic",
"Chalkboard",
"Chalkboard_Bold",
"Chalkboard SE_Bold",
"Chalkboard SE_Light",
"Chalkboard SE_Regular",
"Chalkduster",
"Charter_Black",
"Charter_Black_Italic",
"Charter_Bold",
"Charter_Bold_Italic",
"Charter_Italic",
"Charter_Roman",
"Cochin",
"Cochin_Bold",
"Cochin_Bold_Italic",
"Cochin_Italic",
"Comic Sans MS",
"Comic Sans MS_Bold",
"Copperplate",
"Copperplate_Bold",
"Copperplate_Light",
"Corsiva Hebrew",
"Corsiva Hebrew_Bold",
"Courier",
"Courier_Bold",
"Courier_Bold_Oblique",
"Courier New",
"Courier New_Bold",
"Courier New_Bold_Italic",
"Courier New_Italic",
"Courier_Oblique",
"DIN Alternate_Bold",
"DIN Condensed_Bold",
"Damascus_Bold",
"Damascus_Light",
"Damascus_Medium",
"Damascus_Regular",
"Damascus Semi_Bold",
"DecoType Naskh_Regular",
"Devanagari MT",
"Devanagari MT_Bold",
"Devanagari Sangam MN",
"Devanagari Sangam MN_Bold",
"Didot",
"Didot_Bold",
"Didot_Italic",
"Diwan Kufi_Regular",
"Diwan Thuluth_Regular",
"Euphemia UCAS",
"Euphemia UCAS_Bold",
"Euphemia UCAS_Italic",
"Farah_Regular",
"Farisi_Regular",
"Futura_Bold",
"Futura Condensed_ExtraBold",
"Futura Condensed_Medium",
"Futura_Medium",
"Futura_Medium_Italic",
"GB18030 Bitmap",
"Galvji",
"Galvji_Bold",
"Galvji_Bold_Oblique",
"Galvji_Oblique",
"Geeza Pro_Bold",
"Geeza Pro_Regular",
"Geneva",
"Georgia",
"Georgia_Bold",
"Georgia_Bold_Italic",
"Georgia_Italic",
"Gill Sans",
"Gill Sans_Bold",
"Gill Sans_Bold_Italic",
"Gill Sans_Italic",
"Gill Sans_Light",
"Gill Sans_Light_Italic",
"Gill Sans_SemiBold",
"Gill Sans_SemiBold_Italic",
"Gill Sans UltraBold",
"Gujarati MT",
"Gujarati MT_Bold",
"Gujarati Sangam MN",
"Gujarati Sangam MN_Bold",
"Gurmukhi MN",
"Gurmukhi MN_Bold",
"Gurmukhi MT",
"Gurmukhi Sangam MN",
"Gurmukhi Sangam MN_Bold",
"Heiti SC_Light",
"Heiti SC_Medium",
"Heiti TC_Light",
"Heiti TC_Medium",
"Helvetica",
"Helvetica_Bold",
"Helvetica_Bold_Oblique",
"Helvetica_Light",
"Helvetica_Light_Oblique",
"Helvetica Neue",
"Helvetica Neue_Bold",
"Helvetica Neue_Bold_Italic",
"Helvetica Neue Condensed_Black",
"Helvetica Neue Condensed_Bold",
"Helvetica Neue_Italic",
"Helvetica Neue_Light",
"Helvetica Neue_Light_Italic",
"Helvetica Neue_Medium",
"Helvetica Neue_Medium_Italic",
"Helvetica Neue_Thin",
"Helvetica Neue_Thin_Italic",
"Helvetica Neue_UltraLight",
"Helvetica Neue_UltraLight_Italic",
"Helvetica_Oblique",
"Herculanum",
"Hiragino Maru Gothic ProN_W4",
"Hiragino Mincho ProN_W3",
"Hiragino Mincho ProN_W6",
"Hiragino Sans GB_W3",
"Hiragino Sans GB_W6",
"Hiragino Sans_W0",
"Hiragino Sans_W1",
"Hiragino Sans_W2",
"Hiragino Sans_W3",
"Hiragino Sans_W4",
"Hiragino Sans_W5",
"Hiragino Sans_W6",
"Hiragino Sans_W7",
"Hiragino Sans_W8",
"Hiragino Sans_W9",
"Hoefler Text",
"Hoefler Text_Black",
"Hoefler Text_Black_Italic",
"Hoefler Text_Italic",
"Hoefler Text Ornaments",
"ITF Devanagari_Bold",
"ITF Devanagari_Book",
"ITF Devanagari_Demi",
"ITF Devanagari_Light",
"ITF Devanagari Marathi_Bold",
"ITF Devanagari Marathi_Book",
"ITF Devanagari Marathi_Demi",
"ITF Devanagari Marathi_Light",
"ITF Devanagari Marathi_Medium",
"ITF Devanagari_Medium",
"Impact",
"InaiMathi",
"InaiMathi_Bold",
"Kailasa_Bold",
"Kailasa_Regular",
"Kannada MN",
"Kannada MN_Bold",
"Kannada Sangam MN",
"Kannada Sangam MN_Bold",
"Kefa_Bold",
"Kefa_Regular",
"Khmer MN",
"Khmer MN_Bold",
"Khmer Sangam MN",
"Kohinoor Bangla",
"Kohinoor Bangla_Bold",
"Kohinoor Bangla_Light",
"Kohinoor Bangla_Medium",
"Kohinoor Bangla_Semibold",
"Kohinoor Devanagari_Bold",
"Kohinoor Devanagari_Light",
"Kohinoor Devanagari_Medium",
"Kohinoor Devanagari_Regular",
"Kohinoor Devanagari_Semibold",
"Kohinoor Gujarati_Bold",
"Kohinoor Gujarati_Light",
"Kohinoor Gujarati_Medium",
"Kohinoor Gujarati_Regular",
"Kohinoor Gujarati_Semibold",
"Kohinoor Telugu",
"Kohinoor Telugu_Bold",
"Kohinoor Telugu_Light",
"Kohinoor Telugu_Medium",
"Kohinoor Telugu_Semibold",
"Kokonor_Regular",
"Krungthep",
"KufiStandardGK_Regular",
"Lao MN",
"Lao MN_Bold",
"Lao Sangam MN",
"Lucida Grande",
"Lucida Grande_Bold",
"Luminari",
"Malayalam MN",
"Malayalam MN_Bold",
"Malayalam Sangam MN",
"Malayalam Sangam MN_Bold",
"Marker Felt_Thin",
"Marker Felt_Wide",
"Menlo_Bold",
"Menlo_Bold_Italic",
"Menlo_Italic",
"Menlo_Regular",
"Microsoft Sans Serif",
"Mishafi Gold_Regular",
"Mishafi_Regular",
"Monaco",
"Mshtakan",
"Mshtakan_Bold",
"Mshtakan_BoldOblique",
"Mshtakan_Oblique",
"MuktaMahee_Bold",
"MuktaMahee_ExtraBold",
"MuktaMahee_ExtraLight",
"MuktaMahee_Light",
"MuktaMahee_Medium",
"MuktaMahee_Regular",
"MuktaMahee_SemiBold",
"Muna_Black",
"Muna_Bold",
"Muna_Regular",
"Myanmar MN",
"Myanmar MN_Bold",
"Myanmar Sangam MN",
"Myanmar Sangam MN_Bold",
"Nadeem_Regular",
"New Peninim MT",
"New Peninim MT_Bold",
"New Peninim MT_Bold_Inclined",
"New Peninim MT_Inclined",
"Noteworthy_Bold",
"Noteworthy_Light",
"Noto Nastaliq Urdu",
"Noto Nastaliq Urdu_Bold",
"Noto Sans Javanese_Regular",
"Noto Sans Kannada_Black",
"Noto Sans Kannada_Bold",
"Noto Sans Kannada_ExtraBold",
"Noto Sans Kannada_ExtraLight",
"Noto Sans Kannada_Light",
"Noto Sans Kannada_Medium",
"Noto Sans Kannada_Regular",
"Noto Sans Kannada_SemiBold",
"Noto Sans Kannada_Thin",
"Noto Sans Myanmar_Black",
"Noto Sans Myanmar_Bold",
"Noto Sans Myanmar_ExtraBold",
"Noto Sans Myanmar_ExtraLight",
"Noto Sans Myanmar_Light",
"Noto Sans Myanmar_Medium",
"Noto Sans Myanmar_Regular",
"Noto Sans Myanmar_SemiBold",
"Noto Sans Myanmar_Thin",
"Noto Sans Oriya",
"Noto Sans Oriya_Bold",
"Noto Serif Myanmar_Black",
"Noto Serif Myanmar_Bold",
"Noto Serif Myanmar_ExtraBold",
"Noto Serif Myanmar_ExtraLight",
"Noto Serif Myanmar_Light",
"Noto Serif Myanmar_Medium",
"Noto Serif Myanmar_Regular",
"Noto Serif Myanmar_SemiBold",
"Noto Serif Myanmar_Thin",
"Optima_Bold",
"Optima_Bold_Italic",
"Optima_ExtraBlack",
"Optima_Italic",
"Optima_Regular",
"Oriya MN",
"Oriya MN_Bold",
"Oriya Sangam MN",
"Oriya Sangam MN_Bold",
"PT Mono",
"PT Mono_Bold",
"PT Sans",
"PT Sans_Bold",
"PT Sans_Bold_Italic",
"PT Sans Caption",
"PT Sans Caption_Bold",
"PT Sans_Italic",
"PT Sans Narrow",
"PT Sans Narrow_Bold",
"PT Serif",
"PT Serif_Bold",
"PT Serif_Bold_Italic",
"PT Serif Caption",
"PT Serif Caption_Italic",
"PT Serif_Italic",
"Palatino",
"Palatino_Bold",
"Palatino_Bold_Italic",
"Palatino_Italic",
"Papyrus",
"Papyrus_Condensed",
"Phosphate_Inline",
"Phosphate_Solid",
"PingFang HK_Light",
"PingFang HK_Medium",
"PingFang HK_Regular",
"PingFang HK_Semibold",
"PingFang HK_Thin",
"PingFang HK_Ultralight",
"PingFang SC_Light",
"PingFang SC_Medium",
"PingFang SC_Regular",
"PingFang SC_Semibold",
"PingFang SC_Thin",
"PingFang SC_Ultralight",
"PingFang TC_Light",
"PingFang TC_Medium",
"PingFang TC_Regular",
"PingFang TC_Semibold",
"PingFang TC_Thin",
"PingFang TC_Ultralight",
"Plantagenet Cherokee",
"Raanana",
"Raanana_Bold",
"Rockwell",
"Rockwell_Bold",
"Rockwell_Bold_Italic",
"Rockwell_Italic",
"STIXGeneral-Bold",
"STIXGeneral-BoldItalic",
"STIXGeneral-Italic",
"STIXGeneral-Regular",
"STIXIntegralsD-Bold",
"STIXIntegralsD-Regular",
"STIXIntegralsSm-Bold",
"STIXIntegralsSm-Regular",
"STIXIntegralsUp-Bold",
"STIXIntegralsUp-Regular",
"STIXIntegralsUpD-Bold",
"STIXIntegralsUpD-Regular",
"STIXIntegralsUpSm-Bold",
"STIXIntegralsUpSm-Regular",
"STIXNonUnicode-Bold",
"STIXNonUnicode-BoldItalic",
"STIXNonUnicode-Italic",
"STIXNonUnicode-Regular",
"STIXSizeFiveSym-Regular",
"STIXSizeFourSym-Bold",
"STIXSizeFourSym-Regular",
"STIXSizeOneSym-Bold",
"STIXSizeOneSym-Regular",
"STIXSizeThreeSym-Bold",
"STIXSizeThreeSym-Regular",
"STIXSizeTwoSym-Bold",
"STIXSizeTwoSym-Regular",
"STIXVariants-Bold",
"STIXVariants-Regular",
"STSong",
"Sana_Regular",
"Sathu",
"Savoye LET Plain:1.0",
"Shree Devanagari 714",
"Shree Devanagari 714_Bold",
"Shree Devanagari 714_Bold_Italic",
"Shree Devanagari 714_Italic",
"SignPainter-HouseScript",
"SignPainter-HouseScript_Semibold",
"Silom",
"Sinhala MN",
"Sinhala MN_Bold",
"Sinhala Sangam MN",
"Sinhala Sangam MN_Bold",
"Skia_Black",
"Skia_Black_Condensed",
"Skia_Black_Extended",
"Skia_Bold",
"Skia Condensed",
"Skia Extended",
"Skia_Light",
"Skia_Light_Condensed",
"Skia_Light_Extended",
"Skia_Regular",
"Snell Roundhand",
"Snell Roundhand_Black",
"Snell Roundhand_Bold",
"Songti SC_Black",
"Songti SC_Bold",
"Songti SC_Light",
"Songti SC_Regular",
"Songti TC_Bold",
"Songti TC_Light",
"Songti TC_Regular",
"Sukhumvit Set_Bold",
"Sukhumvit Set_Light",
"Sukhumvit Set_Medium",
"Sukhumvit Set Semi_Bold",
"Sukhumvit Set Text",
"Sukhumvit Set_Thin",
"Symbol",
"Tahoma",
"Tahoma_Bold",
"Tamil MN",
"Tamil MN_Bold",
"Tamil Sangam MN",
"Tamil Sangam MN_Bold",
"Telugu MN",
"Telugu MN_Bold",
"Telugu Sangam MN",
"Telugu Sangam MN_Bold",
"Thonburi",
"Thonburi_Bold",
"Thonburi_Light",
"Times_Bold",
"Times_Bold_Italic",
"Times_Italic",
"Times New Roman",
"Times New Roman_Bold",
"Times New Roman_Bold_Italic",
"Times New Roman_Italic",
"Times Roman",
"Trattatello",
"Trebuchet MS",
"Trebuchet MS_Bold",
"Trebuchet MS_Bold_Italic",
"Trebuchet MS_Italic",
"Verdana",
"Verdana_Bold",
"Verdana_Bold_Italic",
"Verdana_Italic",
"Waseem_Light",
"Waseem_Regular",
"Webdings",
"Wingdings",
"Wingdings 2",
"Wingdings 3",
"Zapf Dingbats",
"Zapfino"]

docList = [
"Academy Engraved LET Plain",
"Al Firat_Regular",
"Al Khalil_Bold",
"Al Khalil_Regular",
"Al Rafidain Al Fanni",
"Al Rafidain_Regular",
"Algiers_Regular",
"Asphalt_Medium",
"Athelas_Bold",
"Athelas_Bold_Italic",
"Athelas_Italic",
"Athelas_Regular",
"Balega_Regular",
"Bank Gothic_Light",
"Bank Gothic_Medium",
"Basra_Bold",
"Basra_Regular",
"Bebas Neue",
"Blackmoor LET Plain:2.0",
"BlairMdITC TT_Medium",
"Bodoni 72_Bold",
"Bodoni 72_Book",
"Bodoni 72_Book_Italic",
"Bodoni 72 Oldstyle_Bold",
"Bodoni 72 Oldstyle_Book",
"Bodoni 72 Oldstyle_Book_Italic",
"Bodoni 72 Smallcaps_Book",
"Bodoni Ornaments",
"Book Antiqua",
"Book Antiqua_Bold",
"Book Antiqua_Bold_Italic",
"Book Antiqua_Italic",
"Bookman Old Style",
"Bookman Old Style_Bold",
"Bookman Old Style_Bold_Italic",
"Bookman Old Style_Italic",
"Bordeaux Roman_Bold LET Plain",
"Bradley Hand_Bold",
"Braganza",
"Capitals",
"Carlito",
"Carlito_Bold",
"Carlito_Bold_Italic",
"Carlito_Italic",
"Century Gothic",
"Century Gothic_Bold",
"Century Gothic_Bold_Italic",
"Century Gothic_Italic",
"Century Schoolbook",
"Century Schoolbook_Bold",
"Century Schoolbook_Bold_Italic",
"Century Schoolbook_Italic",
"Charcoal CY",
"Dear Joe Four",
"Dear Joe Four Small",
"Dear Joe Four Small_Semibold",
"Dijla_Regular",
"Druk_Bold",
"Druk_Bold_Italic",
"Druk_Heavy",
"Druk_Heavy_Italic",
"Druk_Medium",
"Druk_Medium_Italic",
"Druk Super",
"Druk Super_Italic",
"Druk Text_Bold",
"Druk Wide_Bold",
"Druk Wide_Bold_Italic",
"Druk Wide_Medium",
"Druk Wide_Medium_Italic",
"Fakt Slab Stencil Pro_Medium",
"Forgotten Futurist_Bold",
"Forgotten Futurist_Bold_Italic",
"Forgotten Futurist_Italic",
"Forgotten Futurist_Regular",
"Forgotten Futurist Shadow",
"Garamond",
"Garamond_Bold",
"Garamond_Bold_Italic",
"Garamond_Italic",
"Geneva CY",
"Helvetica CY_Bold",
"Helvetica CY_BoldOblique",
"Helvetica CY_Oblique",
"Helvetica CY_Plain",
"Hiragino Kaku Gothic Pro_W3",
"Hiragino Kaku Gothic Pro_W6",
"Hiragino Kaku Gothic ProN_W3",
"Hiragino Kaku Gothic ProN_W6",
"Hiragino Kaku Gothic Std_W8",
"Hiragino Kaku Gothic StdN_W8",
"Hiragino Maru Gothic Pro_W4",
"Hiragino Mincho Pro_W3",
"Hiragino Mincho Pro_W6",
"Hopper Script_Regular",
"Iowan Old Style_Black",
"Iowan Old Style_Black_Italic",
"Iowan Old Style_Bold",
"Iowan Old Style_Bold_Italic",
"Iowan Old Style_Italic",
"Iowan Old Style_Roman",
"Iowan Old Style_Titling",
"Jazz LET Plain:1.0",
"Journal Sans New Inline",
"Koufi Abjadi_Regular",
"Laimoon_Regular",
"Lantinghei TC_Extralight",
"Marion_Bold",
"Marion_Italic",
"Marion_Regular",
"Mona Lisa Solid ITC TT",
"Nisan_Regular",
"Noto Sans Armenian_Black",
"Noto Sans Armenian_Bold",
"Noto Sans Armenian_ExtraBold",
"Noto Sans Armenian_ExtraLight",
"Noto Sans Armenian_Light",
"Noto Sans Armenian_Medium",
"Noto Sans Armenian_Regular",
"Noto Sans Armenian_SemiBold",
"Noto Sans Armenian_Thin",
"Noto Sans Avestan_Regular",
"Noto Sans Bamum_Regular",
"Noto Sans Batak_Regular",
"Noto Sans Brahmi_Regular",
"Noto Sans Buginese_Regular",
"Noto Sans Buhid_Regular",
"Noto Sans Carian_Regular",
"Noto Sans Chakma_Regular",
"Noto Sans Cham_Regular",
"Noto Sans Coptic_Regular",
"Noto Sans Cuneiform_Regular",
"Noto Sans Cypriot_Regular",
"Noto Sans Egyptian Hieroglyphs_Regular",
"Noto Sans Glagolitic_Regular",
"Noto Sans Gothic_Regular",
"Noto Sans Hanunoo_Regular",
"Noto Sans Imperial Aramaic_Regular",
"Noto Sans Inscriptional Pahlavi_Regular",
"Noto Sans Inscriptional Parthian_Regular",
"Noto Sans Kaithi_Regular",
"Noto Sans Kayah Li_Regular",
"Noto Sans Kharoshthi_Regular",
"Noto Sans Lepcha_Regular",
"Noto Sans Limbu_Regular",
"Noto Sans Linear B_Regular",
"Noto Sans Lisu_Regular",
"Noto Sans Lycian_Regular",
"Noto Sans Lydian_Regular",
"Noto Sans Mandaic_Regular",
"Noto Sans Meetei Mayek_Regular",
"Noto Sans Mongolian",
"Noto Sans NKo_Regular",
"Noto Sans New Tai Lue_Regular",
"Noto Sans Ogham_Regular",
"Noto Sans Ol Chiki_Regular",
"Noto Sans Old_Italic_Regular",
"Noto Sans Old Persian_Regular",
"Noto Sans Old South Arabian_Regular",
"Noto Sans Old Turkic_Regular",
"Noto Sans Osmanya_Regular",
"Noto Sans PhagsPa_Regular",
"Noto Sans Phoenician_Regular",
"Noto Sans Rejang_Regular",
"Noto Sans Runic_Regular",
"Noto Sans Samaritan_Regular",
"Noto Sans Saurashtra_Regular",
"Noto Sans Shavian_Regular",
"Noto Sans Sundanese_Regular",
"Noto Sans Syloti Nagri_Regular",
"Noto Sans Syriac_Regular",
"Noto Sans Tagalog_Regular",
"Noto Sans Tagbanwa_Regular",
"Noto Sans Tai Le_Regular",
"Noto Sans Tai Tham",
"Noto Sans Tai Viet_Regular",
"Noto Sans Thaana_Regular",
"Noto Sans Tifinagh_Regular",
"Noto Sans Ugaritic_Regular",
"Noto Sans Vai_Regular",
"Noto Sans Yi_Regular",
"Noto Sans Zawgyi_Black",
"Noto Sans Zawgyi_Bold",
"Noto Sans Zawgyi_ExtraBold",
"Noto Sans Zawgyi_ExtraLight",
"Noto Sans Zawgyi_Light",
"Noto Sans Zawgyi_Medium",
"Noto Sans Zawgyi_Regular",
"Noto Sans Zawgyi_SemiBold",
"Noto Sans Zawgyi_Thin",
"Noto Serif Balinese_Regular",
"Party LET Plain",
"PortagoITC TT",
"Princetown LET",
"Raya_Regular",
"Santa Fe LET Plain:1.0",
"Scheme-Bold",
"SchoolHouse Cursive B",
"SchoolHouse Printed A",
"Seravek",
"Seravek_Bold",
"Seravek_Bold_Italic",
"Seravek_ExtraLight",
"Seravek_ExtraLight_Italic",
"Seravek_Italic",
"Seravek_Light",
"Seravek_Light_Italic",
"Seravek_Medium",
"Seravek_Medium_Italic",
"Somer_Regular",
"Stone Sans ITC TT_Bold",
"Stone Sans Sem ITC TT Semi",
"Stone Sans Sem ITC TT SemiIta",
"Superclarendon_Black",
"Superclarendon_Black_Italic",
"Superclarendon_Bold",
"Superclarendon_Bold_Italic",
"Superclarendon_Italic",
"Superclarendon_Light",
"Superclarendon_Light_Italic",
"Superclarendon_Regular",
"Synchro LET",
"The Hand Serif_Semibold",
"Tw Cen MT",
"Tw Cen MT_Bold",
"Tw Cen MT_Bold_Italic",
"Tw Cen MT_Italic",
"Type Embellishments One LET Embellishments One LET Plain:1.0",
"Yaziji_Regular",
"Zawra_Bold",
"Zawra_Heavy",
]